### ISSUE TITLE
Does fmdb support WAL(Write-Ahead Logging)??

### ISSUE THREAD

**Issue by KorolZhu** [ccgus/fmdb#252]

**Comment by SpecialCyCi** [comment]
@ccgus 
However, setting wal mode is only working ing sqlite3_exec.

**Comment by ccgus** [comment]
How are you testing this?

**Comment by ccgus** [comment]
Ie- FMDB calls sqlite3_exec with it's methods- is something else getting in the way?

**Comment by yogesh-zendrive** [comment]
Any way of setting WAL mode using FMDB?
