### ISSUE TITLE
Unable to use FMDB in a Swift framework

### ISSUE THREAD

**Issue by mharper** [ccgus/fmdb#309]
Although it appears this problem was solved at one point in time, the proposed solution that defines sqlite3 as a module thus allowing the import of `sqlite3.h` in FMDB no longer seems to work after Xcode 6.0.1.

http://programmingthomas.com/blog/2014/7/23/sqlite-in-swift-frameworks

Error is:
```
...FMDB.framework/Headers/FMDatabase.h:2:9: error: include of non-modular header inside framework module 'FMDB.FMDatabase'
#import "sqlite3.h"
```

Note that this is not a situation where you can use a bridging header file as the desired artifact is a framework.

**Comment by cillyfly** [comment]
I have the same problem with you. and I set "Allow Non-modular Includes in Framework Modules" in both my framework and my project.then clean and build. It's ok.

**Comment by tmu** [comment]
I'm using Cocoapods 0.36 beta, and I couldn't get this to compile by enabling  "Allow Non-modular Includes in Framework Modules" (I enabled in all 4: FMDB Target in Pods, Pods project itself, App target, and App Project. I also tried different combinations and cleaned in between builds

**Comment by mortenholmgaard** [comment]
I have same problem after 0.36 pods is no longer in beta and the new pods requirement: use_frameworks!

**Comment by Kirow** [comment]
Same problem here :(

**Comment by felipesabino** [comment]
Any news on this issue? I am facing same problem with cocoapods version `0.36.0`

**Comment by robertmryan** [comment]
I've been able to call FMDB from a Swift framework, by putting FMDB in its own framework. Then any Swift framework can use that separate FMDB framework. This involves a few annoying little changes in FMDB to remove non-modular includes (namely `#import <sqlite3.h>`) from the FMDB headers, as illustrated in pull request https://github.com/ccgus/fmdb/pull/353. NB: Please consider that pull request to be highly speculative, as I'd much rather find a way to do this without having to make any non-backward compatible changes to FMDB (as modest as they are)!

Note, if you build a separate FMDB framework, make sure to flag the headers as being public as [discussed here](http://stackoverflow.com/a/24317456/1271826). But you can only do that once you excise the FMDB headers of all `sqlite3.h` dependencies as illustrated in pull request.

**Comment by Kirow** [comment]
Now using
```Ruby
use_frameworks!
pod 'FMDB', :git => 'https://github.com/robertmryan/fmdb.git'
```
works for me, thanks.

**Comment by macu** [comment]
@Kirow I am doing the same for now, thanks for providing link to @robertmryan's branch. Will wait for upstream updates before next app release.

**Comment by nateuni** [comment]
Robert is this still the temporary fix to pull from: https://github.com/robertmryan/fmdb.git?

**Comment by robertmryan** [comment]
Yep. 

At some point, I'm hoping it will be merged in as a branch of the main repo, but not yet.

**Comment by nateuni** [comment]
Now I am getting FMDB doesn't have member named "intForQuery". I had this before switching over to pods but it was resolved by an update to the repo (off memory). How should I tackle this?

**Comment by robertmryan** [comment]
Unfortunately, at the time of writing, a framework can be either Objective-C or Swift, but not both. So, if you've built the Objective-C-based framework, you still have to manually include the `FMDatabaseAdditionsVariadic.swift` extension (in the `Swift extensions` folder in the `extra` folder) in your Swift targets.

**Comment by nateuni** [comment]
Q: http://stackoverflow.com/questions/30216524/cocoapods-swift-and-fmdb-cipher-are-these-three-currently-compatible , I will delete this after Rob see's it. Sorry I didn't know how else to contact him.

**Comment by felipesabino** [comment]
@nateuni did you check the contact info on his gh profile? 

http://contact.robertmryan.com/ ...

**Comment by MrArtichaut** [comment]
Any news on this issue ? The fix from @robertmryan  works but can we hope to see it merge in the main repo ?

**Comment by vvit** [comment]
Agree, the merging would be nice.

**Comment by davidman** [comment]
Hi all, I was able to get rid of the annoying error: 'include of non-modular header inside framework module 'FMDB' on my FMDB + SQLCipher project by changing all the `#import  "sqlite.h"` to `#import <SQLCipher/sqlite3.h>` since my Pods project contains the FMDB and the SQLCipher pods separately. 

BTW: My podfile just included this line: `pod 'FMDB/SQLCipher'`

<img width="609" alt="screen shot 2015-08-26 at 11 50 58 pm" src="https://cloud.githubusercontent.com/assets/860166/9512830/5354a230-4c4d-11e5-9e8a-e1bd5105712e.png">

**Comment by mishagray** [comment]
If you are using carthage you can try my branch here:
https://github.com/ccgus/fmdb/pull/402

**Comment by gblotter** [comment]
Here's a post install script that I've been running, which @stephanheilner forwarded on to me.  Just swap out "SQLCipher" with whichever Submodule you choose to pull down via Cocoapods.
``  
post_install do |installer|
		Dir['Pods/*/**/*.h'].each { |f|
			oldFile = File.read(f)
			newFile = oldFile.gsub(/"sqlite3.h"/, '<SQLCipher/sqlite3.h>')
			File.open(f, "w") { |file|
				file << newFile
			}
		}
end  
``

**Comment by stephanheilner** [comment]
FWIW, this is a total hack. But until we can come up with a real fix that work across the various subspecs, this works. We could add the hack to each subspec, but still, there must be a better way to solve this...

**Comment by phatblat** [comment]
Ran into permission issues when applying this hack, so here's a version that enables write perms on the file before overwriting.

```ruby
post_install do |installer|
    Dir['Pods/*/**/*.h'].each { |file|
        search_text = %q["sqlite3.h"]
        replace_text = '<SQLCipher/sqlite3.h>'

        oldFile = File.read(file)
        if oldFile.include? search_text
            puts "#{file} includes #{search_text}"

            File.chmod(0604, file) # rw----r--
            newFile = oldFile.gsub(/#{search_text}/, replace_text)
            File.open(file, "w") { |file|
                file << newFile
            }
        end
    }
end
```

**Comment by robertmryan** [comment]
I'm going to close this pull request as it appears we can use FMDB as a framework using the main `master` branch in Xcode 8. The problem seems to be resolved now.

**Comment by sunil-chayagol** [comment]
'FMDB/FMDB.h' file not found

above is the problem i am facing when i try to build. please anyone suggest a way.
