### ISSUE TITLE
[feature] Compatibility with Carthage dependency manager

### ISSUE THREAD

**Issue by dodikk** [ccgus/fmdb#324]
Carthage is intended to be the simplest way to add frameworks to your Cocoa application.
Carthage builds your dependencies and provides you with binary frameworks, but you retain full control over your project structure and setup. Carthage does not automatically modify your project files or your build settings.
https://github.com/Carthage/Carthage

**Scenario :**
As an iOS/Mac developer
I want to use fmdb as a dynamic framework
So that no linker conflicts take place between my shared logic and third-party frameworks depending on fmdb.

**Acceptance criteria :**
1. There should be a framework target for both iOS and OS X
2. There should be two **public schemes** for each target mentioned in [1]
3. There must be a semantic versioning compatible tag 
4. The frameworks must be successfully built by carthage

``` bash
echo ' github "ccgus/fmdb" ' > ./Cartfile
carthage update
```

5). It should be still possible to use fmdb as a static library (changes from `#import ""` to `#import <>` do not affect backward compatibility, I guess).

**Comment by ctava** [comment]
would love FMdb to be available via carthage. it is so much better than cocoapods.

# FMdb
github "ccgus/fmdb" == 2.5.0


otherwise, it seems like ESDatabaseWrapper may steal your thunder:

https://github.com/dodikk/ESDatabaseWrapper/commit/d0f7ac8de503807bf50a68bfb64186f2dc4cf98b

**Comment by ccgus** [comment]
I have a  thunder?

At any rate, if someone really really wants it, they'll have to send a (hopefully very simple) patch my way.

**Comment by benkraus** [comment]
I would really love to see this compatible with Carthage. I'll make a patch and send it your way.

**Comment by kirb** [comment]
Another +1; current project is inconsistently using multiple dependency managers just for fmdb. :/

**Comment by kirb** [comment]
https://github.com/kirb/fmdb/tree/carthage

Wouldn't consider this done yet because I can't seem to get Carthage to build a product, and the fmdb Xcode project doesn't yet have modular schemes to replicate CocoaPods subspecs. If you want to do that yourself, you just have to mark schemes as shared and then they'll be usable via Carthage. Click Manage Schemes here:

![image](https://cloud.githubusercontent.com/assets/773309/7589164/56aa39a4-f900-11e4-80c7-3d0153af05f6.png)

… then tick Shared as needed here:

![image](https://cloud.githubusercontent.com/assets/773309/7589178/6ae9a544-f900-11e4-8406-44380ef71642.png)

**Comment by aventurella** [comment]
+1 for this as well

**Comment by Rupert-RR** [comment]
Another +1!

**Comment by amywtlin** [comment]
plus one!

**Comment by lukescott** [comment]
Need this as well. Carthage is far simpler than Cocoapods. You just create a framework in Xcode and share the scheme. I'm actually removing Cocoapods from my project because of this.

**Comment by hiber** [comment]
+1

**Comment by apbendi** [comment]
+1

**Comment by zetasq** [comment]
+1

**Comment by pfeilbr** [comment]
+1

**Comment by pkalisz** [comment]
+1

**Comment by andrewjackman** [comment]
+1

**Comment by ruipfcosta** [comment]
+1

**Comment by samidalouche** [comment]
+1

**Comment by jj0b** [comment]
+1

**Comment by johngoren** [comment]
Oh  my god so much +1

**Comment by robertmryan** [comment]
We've added Carthage support to 2.6.

A few observations from my testing:

1. When you install Carthage, you can either use Homebrew or download the PKG. Unfortunately, at this point, the HomeBrew version is outdated (v2.8), which has issues. [Get the latest PKG.](https://github.com/Carthage/Carthage/releases)

2. I found that, for iOS, I had to use the ’copy-frameworks’ approach described in the [README](https://github.com/Carthage/Carthage/blob/master/README.md).

3. Note, just like the old `swiftFrameworks` branch, this removes `sqlite3.h` from the public headers and removes references to SQLite types from the various methods and properties. So, if you're doing anything contingent on those types, some modest changes might be necessary (e.g. casting). For most apps, though, this should shouldn't manifest itself.

**Comment by ivan-konov** [comment]
+1

**Comment by maciekish** [comment]
+1

**Comment by robertmryan** [comment]
@maciekish - I'm not sure if I understand the `+1` comment. Are you saying that you like that FMDB offers Carthage compatibility? Or are you under the mistaken impression that it doesn't support Carthage and were expressing hope that it would.

To clarify, FMDB supports Carthage installs. As dodkik said, assuming you have [the latest Carthage](https://github.com/Carthage/Carthage/releases) installed, you can just do the following from the command line:

```
echo ' github "ccgus/fmdb" ' > ./Cartfile
carthage update
```

And then you can just follow the steps outlined in [Getting Started](https://github.com/Carthage/Carthage#getting-started) on the Carthage README.

**Comment by dodikk** [comment]
> you can just do the following from the command line:
> And then you can just follow the steps outlined in Getting Started on the Carthage README.

It might be a good idea to add the mentioned instructions to the readme of FMDB. And carthage compatibility badge too. Even though they are that easy (you do have some descriptions for cocoapods steps).

**Comment by robertmryan** [comment]
> It might be a good idea to add the mentioned instructions to the readme of FMDB. And carthage compatibility badge too. Even though they are that easy (you do have some descriptions for cocoapods steps).

Agreed. 

It’s already in progress. I’m just dotting a few i’s and crossing a few t’s.
