### ISSUE TITLE
when same column name in 2 tables, such as select A.col1, B.col1 from A ,B, resultDictionary is wrong

### ISSUE THREAD

**Issue by isee15** [ccgus/fmdb#329]
- (NSDictionary *)resultDictionary {

    NSUInteger num_cols = (NSUInteger) sqlite3_data_count([_statement statement]);

    if (num_cols > 0) {
        NSMutableDictionary *dict = [NSMutableDictionary dictionaryWithCapacity:num_cols];

        int columnCount = sqlite3_column_count([_statement statement]);

        int columnIdx = 0;
        for (columnIdx = 0; columnIdx < columnCount; columnIdx++) {
======
columnIdx=0,1 columnName  will be same
======
            NSString *columnName = [NSString stringWithUTF8String:sqlite3_column_name([_statement statement], columnIdx)];

            id objectValue = [self objectForColumnIndex:columnIdx];
            [dict setObject:objectValue forKey:columnName];
        }

        return dict;
    }
    else {
        NSLog(@"Warning: There seem to be no columns in this set.");
    }

    return nil;
}

**Comment by ccgus** [comment]
Can you please provide a code sample as described in the "Reporting bugs" section of the readme?

**Comment by isee15** [comment]
void FMDBReportABugFunction() {
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    NSString *dbPath = [documentsDirectory stringByAppendingPathComponent:@"bugreportsample.db"];
    // delete the old db if it exists
    NSFileManager *fileManager = [NSFileManager defaultManager];
    [fileManager removeItemAtPath:dbPath error:nil];
    
    FMDatabaseQueue *queue = [FMDatabaseQueue databaseQueueWithPath:dbPath];
    
    [queue inDatabase:^(FMDatabase *db) {
        BOOL worked = [db executeUpdate:@"create table test1(a,b);"];
        worked = [db executeUpdate:@"create table test2(a,c);"];

        worked = [db executeUpdate:@"insert into test1 values (1,2);"];
        worked = [db executeUpdate:@"insert into test2 values (3,2);"];
        //FMDBQuickCheck(worked);
        
        FMResultSet *rs = [db executeQuery:@"select test1.a,test2.a from test1,test2 where test1.b = test2.c;"];
        if ([rs next]) {
            NSDictionary *result = rs.resultDictionary;
            NSLog(@"%@",result);
            //{a = 3;}
            //there's only one column in result
        }
        [rs close];
    }];
    
    [queue close];
    
}

**Comment by ccgus** [comment]
FMDB is using the column names that SQLite hands to it, so I believe the behavior is correct.

However, this is easily solved by changing the query to something like this:
select test1.a as col1, test2.a as col2 from test1, test2 where test1.b = test2.c;
