### ISSUE TITLE
FMDBAdditions in Swift not found in Xcode.

### ISSUE THREAD

**Issue by nateuni** [ccgus/fmdb#336]
I am porting some existing code over to swift. I am using FMDB in swift and everything has been good so far, but I do not have access to FMDatabaseAdditions methods in my project in spite of having access to everything else (FMResultSet, FMDatabasePool and so on).

1. I have the bridging-header file with the #import "FMDB" statement and it has the includes for all the other FMDB files.
2. I have looked in my build phases and I can see FMDatabaseAdditions.m in the "Compile Sources" and I have moved it to the top of the list.
3. I have cleaned.. 

Still xCode doesn't recognise it or its methods.

Any ideas?

**Comment by robertmryan** [comment]
Perhaps you can show us sample code that illustrates the problem. I use `FMDatabaseAdditions` methods from Swift without incident.

**Comment by nateuni** [comment]
![screen shot 2015-01-23 at 9 27 40 pm](https://cloud.githubusercontent.com/assets/405559/5873071/b5c42982-a346-11e4-9c44-0374baa084ca.png)
![screen shot 2015-01-23 at 9 28 20 pm](https://cloud.githubusercontent.com/assets/405559/5873079/db22178e-a346-11e4-8b16-73755473eb2b.png)
![screen shot 2015-01-23 at 9 31 45 pm](https://cloud.githubusercontent.com/assets/405559/5873121/4f4a5716-a347-11e4-9abc-fd91f0f8c8b3.png)

My understanding is as long as I have the import FMDB.h in the bridging-header then I should be able to access all of its includes (I can see everything else but FMDatabaseAdditions). This code worked perfectly in objective-c. I am not sure what the issue is. 

Note I have added FMDB by dragging (copying) them in, would that be an issue?

**Comment by robertmryan** [comment]
1. Yes, if you have FMDB.h in your bridging header, it should make FMDB methods (including the additions) available from your code. For example, this works fine:

        let db = FMDatabase(path: path)
        db.open()
        
        if let rs = db.executeQuery("select * from test", withArgumentsInArray: nil) {
            while rs.next() {
                let identifier = rs.intForColumn("id")
                let string = rs.stringForColumn("x")

                println("\(identifier): \(string)")
            }
            rs.close()
        }

2. You should not have foundation in your bridging header, though.

3. Your screen snapshot shows the compile sources, bridging header, and some sample code. But your sample code doesn't illustrate any valid FMDatabaseAdditions code that doesn't compile properly. I was hoping you could share some FMDatabaseAdditions code that wasn't compiling (but also illustrating that the `FMDatabase` class was compiling fine).

 Show us code sample with actual compiler errors.

4. You say 

 > Note I have added FMDB by dragging (copying) them in, would that be an issue?

 No, that wouldn't be an issue. That's how I usually add it to my project. The only trick that I've noticed is that you can't just drag the `src/fmdb` folder, but rather you have to drag the individual files. You can select all of them at once, and drag them over together, but if you drag the folder rather than the `.m` and `.h` files, I find it doesn't prompt you to add the bridging header file.

**Comment by robertmryan** [comment]
Unrelated to your problem at hand, but I often like to drag in `FMDatabaseVariadic.swift` from `src/extra/Swift Extensions`, too. Consider a code sample like this:

    if let rs = db.executeQuery("select * from test", withArgumentsInArray: nil) {
        // do something
    }

With `FMDatabaseVariadic.swift`, that can then be simplified to:

    if let rs = db.executeQuery("select * from test") {
        // do something
    }

**Comment by nateuni** [comment]
Ok I will drag that file in.. 

Here in the screenshots is where I am trying to access the intForQuery() 

![screen shot 2015-01-23 at 10 18 34 pm](https://cloud.githubusercontent.com/assets/405559/5873746/da3f54a6-a34d-11e4-9184-1bdfb55ef6c0.png)
![screen shot 2015-01-23 at 10 18 44 pm](https://cloud.githubusercontent.com/assets/405559/5873745/da30a92e-a34d-11e4-8125-f8811ef29b27.png)

**Comment by robertmryan** [comment]
I notice that some of the FMDatabaseAdditions methods work fine. For example:

    if db.tableExists("test") {
        println("test table exists")
    } else {
        println("test table doesn't exist")
    }

It looks like Swift is having issues with the variadic methods within the category. This is a known problem with Swift, but while I created the variadic rendition of `executeQuery` and `executeUpdate`, I didn't do so for the FMDatabaseAdditions methods. I will take care of this.

Thanks for bringing it to our attention.

**Comment by nateuni** [comment]
Yes correct, I do have access to tableExists().

No problem, thanks for your help. 

I don't know what the variadic rendition is bud? Where can I go have a poke around so I know what is going on? I like to educate myself.

**Comment by robertmryan** [comment]
Variadic methods are those that take an optional number of parameters. If you search online for "swift objective-c variadic", you'll probably find references.

If you want, you can try adding [`FMDatabaseAdditionsVariadic.swift`](https://github.com/robertmryan/fmdb/blob/master/src/extra/Swift%20extensions/FMDatabaseAdditionsVariadic.swift) to your project and see if that works for you. Note, this is a preliminary pull request, subject to Gus's review/approval. This is _not_ part of the production release of FMDB. But, still, if you want to take a look at it, feel free.

**Comment by nateuni** [comment]
Thanks, will do. Much appreciated.

**Comment by robertmryan** [comment]
@ccgus This issue is resolved and should be closed.
