### ISSUE TITLE
FMDB insert error if query contain ' single quotes. eg) Let's 

### ISSUE THREAD

**Issue by maradkar** [ccgus/fmdb#345]
Hello I am FMDB framework in mu iOS Application, I am facing some issue while insertion if query contain single quotes letter,please help to solve this issue, I have in entire app.

**Comment by robertmryan** [comment]
Use `?` placeholders in your SQL and that generally addresses this sort of problem.

    NSString *author = @"Liam O'Flaherty";
    BOOL success = [db executeUpdate:@"insert into authors (name) values (?)", author];

By using the `?` placeholders, you address the typical problem associated with quotation marks in SQL.

If you're still having other problems, please update your question with a more complete example. We need the smallest possible, reproducible example of the problem.

**Comment by robertmryan** [comment]
@ccgus I believe this issue should be closed.

**Comment by maradkar** [comment]
Thanks for comments ccGus, but how it will work for update.and it showing error when I use (?)in my query

**Comment by robertmryan** [comment]
We cannot help you unless you include simple, reproducible example of your problem.

**Comment by RajChanchal** [comment]
I tried the above method but looks like there is some issue:
`BOOL inserted = [database executeUpdate:@"INSERT INTO Expense (exp_date,exp_cat_id,exp_subcat_id,exp_amount,exp_note) VALUES (?, ?, ?,?,?)",expense.ExpenseDate, expense.ExpenseCatID,expense.ExpenseSubcatID,expense.ExpenseAmount,expense.ExpenseNotes];`

Following are types of each parameter:
exp_date: NSDate
exp_cat_id: NSInteger
exp_subcat_id: NSInteger
exp_amount: NSInteger
exp_note: NSString

Attached is the screenshot of the Expense table:
<img width="741" alt="screen shot 2016-06-20 at 9 52 47 am" src="https://cloud.githubusercontent.com/assets/7058465/16183581/cd0a0e20-36cc-11e6-84e5-467c45ce56cd.png">

Following is the screenshot of where the app crashes in FMDatabase.m class:
<img width="939" alt="screen shot 2016-06-20 at 9 57 06 am" src="https://cloud.githubusercontent.com/assets/7058465/16183620/7b66ef4c-36cd-11e6-85e5-dfe09216aa79.png">

**Comment by robertmryan** [comment]
@RajChanchal - As the documentation for [`executeUpdate`](http://ccgus.github.io/fmdb/html/Classes/FMDatabase.html#//api/name/executeUpdate:) says, you cannot use `executeUpdate` with fundamental data types, like `NSInteger`.

You could wrap the `NSInteger` values in `@(...)` to make those `NSInteger` parameters be passed as `NSNumber` objects instead, e.g.:

```objc
BOOL inserted = [database executeUpdate:@"INSERT INTO Expense (exp_date, exp_cat_id, exp_subcat_id, exp_amount ,exp_note) VALUES (?, ?, ?, ?, ?)",expense.ExpenseDate, @(expense.ExpenseCatID), @(expense.ExpenseSubcatID), @(expense.ExpenseAmount), expense.ExpenseNotes]; 
```
