### ISSUE TITLE
fmdb not compiling in xcode 6.2

### ISSUE THREAD

**Issue by almas73** [ccgus/fmdb#349]
Just updated to Xcode 6.2, tried to build the project, and it failed because if this error in fmdb:

![screen shot 2015-03-09 at 4 51 52 pm](https://cloud.githubusercontent.com/assets/1211509/6566884/9b0b8942-c67c-11e4-9938-624ebeacc960.png)

**Comment by almas73** [comment]
fixed by getting latest version...

**Comment by chudasaarjun** [comment]
i am facing problem in xcode 6.2
