### ISSUE TITLE
INSTR function not working

### ISSUE THREAD

**Issue by oErangaPrasad** [ccgus/fmdb#351]
its gives an error - no such function: INSTR

it would be great if you can fix it.
thanks for good work.

**Comment by robertmryan** [comment]
Perhaps you can provide simple example that reproduces the problem you describe.

**Comment by oErangaPrasad** [comment]
This is my Query

SELECT SUBSTR(Email_Address, INSTR(Email_Address, '@') + 1) AS DomainId, COUNT(*) AS DomainCount from MESSAGE group by SUBSTR(Email_Address, INSTR(Email_Address, '@') + 1);

I want to get Domain count from the database.
ex - yahoo.com 5, google.com 3 like that

**Comment by robertmryan** [comment]
Hmm, that SQL works fine for me...

**Comment by robertmryan** [comment]
This code:

    db.executeUpdate("create table MESSAGE (Email_Address text)")
    db.executeUpdate("insert into MESSAGE (Email_Address) values (?)", "foo@google.com")
    db.executeUpdate("insert into MESSAGE (Email_Address) values (?)", "bar@google.com")
    
    if let rs = db.executeQuery("SELECT SUBSTR(Email_Address, INSTR(Email_Address, '@') + 1) AS DomainId, COUNT(*) AS DomainCount from MESSAGE group by SUBSTR(Email_Address, INSTR(Email_Address, '@') + 1);") {
        while rs.next() {
            println(rs.resultDictionary())
        }
    } else {
        println(db.lastErrorMessage())
    }

That generated this output:

    [DomainId: google.com, DomainCount: 2]

I'm sure an Objective-C rendition would work equally well. FMDB really doesn't do any thing with the SQL, itself, so there must be something else going on here. 

Perhaps you can share the actual code in which you use FMDB to perform the above SQL and which generates that error.

**Comment by oErangaPrasad** [comment]
I have updated the latest code and Its not working for me. Im using Xcode 6.1 SDK 8.1
but  [db lastErrorMessage] gives no such function: INSTR. any idea how to fix it ?
Thanks for your time.

**Comment by robertmryan** [comment]
My test was on iOS 8.2. when I repeated on iOS 8.1, I see the problem you describe. 

This is a SQLite version problem, not an FMDB problem.

See http://stackoverflow.com/a/27860706/1271826.

**Comment by oErangaPrasad** [comment]
Ohh thanks robert. So I have to look for another solution. Thanks for your time. really appreciate your support.

**Comment by robertmryan** [comment]
Looks like some folks do `ltrim` of all characters other than `@` which is cute alternative approach. Alternatively, SQLite (and FMDB) give you the capability to implement you own SQL functions (see http://stackoverflow.com/a/27576609/1271826 for example). Good luck!

**Comment by oErangaPrasad** [comment]
Thanks robert. I fixed it in Objective-C. Keep up the good work!

**Comment by robertmryan** [comment]
For the benefit of future readers, if you are supporting an older SQLite version, you can define your own `_INSTR` function like so:

    [db makeFunctionNamed:@"_INSTR" maximumArguments:2 withBlock:^(sqlite3_context *context, int argc, sqlite3_value **argv) {
        @autoreleasepool {
            if (argc != 2) {
                sqlite3_result_error(context, [@"wrong number of arguments to function _INSTR()" cStringUsingEncoding:NSUTF8StringEncoding], SQLITE_ERROR);
            } else if (sqlite3_value_type(argv[0]) == SQLITE_NULL || sqlite3_value_type(argv[1]) == SQLITE_NULL) {
                sqlite3_result_null(context);
            } else {
                NSString *stringToSearch    = [NSString stringWithUTF8String:(const char *)sqlite3_value_text(argv[0])];
                NSString *stringToSearchFor = [NSString stringWithUTF8String:(const char *)sqlite3_value_text(argv[1])];
                NSRange range = [stringToSearch rangeOfString:stringToSearchFor];
                int location = range.location == NSNotFound ? 0 : (int)(range.location + 1);
                sqlite3_result_int(context, location);
            }
        }
    }];

In Swift, that is:

    db.makeFunctionNamed("_INSTR", maximumArguments: 2) { context, argc, argv in
        autoreleasepool {
            if argc != 2 {
                sqlite3_result_error(context, "wrong number of arguments to function _INSTR()".cStringUsingEncoding(NSUTF8StringEncoding), SQLITE_ERROR)
            } else if sqlite3_value_type(argv[0]) == SQLITE_NULL || sqlite3_value_type(argv[1]) == SQLITE_NULL {
                sqlite3_result_null(context)
            } else {
                let stringToSearch = NSString(UTF8String: UnsafePointer<Int8>(sqlite3_value_text(argv[0])))
                let stringToSearchFor = NSString(UTF8String: UnsafePointer<Int8>(sqlite3_value_text(argv[1])))
                if stringToSearch != nil && stringToSearchFor != nil {
                    let range = stringToSearch!.rangeOfString(stringToSearchFor!)
                    let location = range.location == NSNotFound ? 0 : (range.location + 1)
                    sqlite3_result_int(context, Int32(location))
                } else {
                    sqlite3_result_null(context)
                }
            }
        }
    }

**Comment by robertmryan** [comment]
@ccgus I think this issue should be closed.
