### ISSUE TITLE
FMResultSet at Index

### ISSUE THREAD

**Issue by mrhaxic** [ccgus/fmdb#357]
Hi

When I have a lot of rows with FMResultSet can I get the second row or something like this

[row atindexPath:indexPath.row]

without [row next] 

?

**Comment by ccgus** [comment]
Nope, it's not really the way SQLite works.

**Comment by mrhaxic** [comment]
is there any way to do this ? just a hint

**Comment by ccgus** [comment]
There are ways to alter your query for this.  You'll want to lookup SQLite specific info, since it has nothing to do with FMDB.

**Comment by barefeettom** [comment]
This wrapper for FMDB might be of help to you:
https://github.com/BareFeetWare/BFWQuery
It's intended to make SQLite databases accessible via familiar array syntax, while taking care of the "next" syntax for you.

**Comment by mrhaxic** [comment]
@barefeettom this what im looking for, Thanks alot.
