### ISSUE TITLE
NSLog noise - Particularly "Could not find index for..."

### ISSUE THREAD

**Issue by josephlord** [ccgus/fmdb#358]
I may have missed a parameter or build setting but even with logsErrors and traceExecution both false there is a lot of logging noise from FMDB in the app I'm working on. Particularly "Could not find index for..." which doesn't seem like a severe error always appears. (If this really is an error rather than a note that it might be worth considering for performance reasons please let me know.)

I do wonder if this should be a separate setting as I'm not sure that it fits either in errors or execution trace.

I can send a pull request if you would like but I thought it was worth checking the intention and design first.

**Comment by ccgus** [comment]
FMDB will log things when "unexpected" things happen.  If you have an example of that not happening, then a sample reproducing that would be awesome.

The "Could not find index…" bit sounds like a query that could use some cleaning up.

**Comment by josephlord** [comment]
The log comes from https://github.com/ccgus/fmdb/blob/master/src/fmdb/FMDatabase.m#L809 and https://github.com/ccgus/fmdb/blob/fc7805386eafaec89aa424a06b5ed8ad085a8604/src/fmdb/FMDatabase.m#L991

Both of these cases seem not to be conditional on anything and while the queries could possibly be cleaned up (and/or fully indexed) I don't think it is an error not to be fully indexed (although it may be a bad idea). If it is an error then the log message could be clearer about that. E.g. "executeQuery error: all dictionaryArgs must be indexed. No index for xxx". I'll might have time to make a test case tomorrow.

**Comment by ccgus** [comment]
That's a legit log in FMDB's opinion.  You're asking for something that's not there.  Maybe in the future it could return an error instead, but for now, you need to make sure that you're asking for keys that exist.

**Comment by josephlord** [comment]
Apologies. I think I've just figured out what I was missing. The warning is when the dictionary has unnecessary items in. I thought it was saying that the DB column was not indexed rather than the dictionary value is not needed in the query. I don't know if others might be confused as I was if so it might be worth changing the wording of the message. Up to you.

Thanks for your help. Happy for you to close.
