### ISSUE TITLE
Swift: 'sqlite_int64' is not convertible to 'Int'

### ISSUE THREAD

**Issue by nawar** [ccgus/fmdb#359]
Apple recommends using `Int` when developing with iPhone. However, iPhone 5 is known to be 32-bit and returns Int32. However, `lastInsertId` with **fmdb** returns `sqlite_int64` which is not exactly the same and causing the compile to complain on the mere idea of casting this into `Int`

    let lastId = db.lastInsertId() as Int // Compiler error: 'sqlite_int64' is not convertible to 'Int'

Any idea on how to go about this?

**Comment by nawar** [comment]
Never mind. I was doing it wrong.

**Comment by BigTigerTeeth** [comment]
How to solve it?

**Comment by robertmryan** [comment]
@BigTigerTeeth - It is an `Int64`. So use it as an `Int64` and don't try to cast it to an `Int`.
