### ISSUE TITLE
Can't Insert Dictionary (JSON) into DB

### ISSUE THREAD

**Issue by mikewalkerjr** [ccgus/fmdb#362]
I'm attempting to insert a JSON object into my DB. I'm using swift 1.2. I have read that for NSDictionary, the parameter must be prefixed with a colon. Here is the code that I have after opening the DB:

    let insertSQL = "INSERT OR REPLACE INTO filters (memberId,name,data) VALUES (\(memberId), \(filterId), :\(json))"         
    let result = db.executeUpdate(insertSQL, withArgumentsInArray: nil)

When I run the code, I get the following error:

    "DB Error: 1 "unrecognized token ":""

Am I not putting the prefixed colon in the correct spot?

**Comment by robertmryan** [comment]
It's not entirely clear to me what you were trying to do, i.e., why that colon is there. But, I notice that you're doing string interpolation, which I would not advise. I'd suggest using placeholders. You can either use `?` placeholders with an array of arguments:

    let insertSQL = "INSERT OR REPLACE INTO filters (memberId, name, data) VALUES (?, ?, ?)"
    let result = db.executeUpdate(insertSQL, withArgumentsInArray: [memberId, filterId, json])

Or you can use named parameters with a dictionary of values:

    let insertSQL = "INSERT OR REPLACE INTO filters (memberId, name, data) VALUES (:memberId, :filterId, :json)"
    let result = db.executeUpdate(insertSQL, withParameterDictionary: ["memberId" : memberId, "filterId" : filterId, "json" : json])

In terms of storing a dictionary in the database as JSON string, while I might not be inclined to do it that way, neither FMDB nor SQLite care what values you insert. But it should either be the `String` or `NSData` representation of the JSON, but not an array/dictionary.

**Comment by robertmryan** [comment]
[Re-reading your question, I think I now understand what your intent was, so I've deleted previous comment, which was likely to only introduce confusion, and am going to start over.]

The discussion about using colons with dictionaries of values is related to how placeholders are represented in the SQL. It is not used for inserting an entire dictionary in for a value in the SQL.

By way of example, the colon syntax can be used if you had three values you wanted to insert in the database and they were stored in a dictionary, you could insert them like so:

    let insertSQL = "INSERT OR REPLACE INTO foo (a, b, c) VALUES (:x, :y, :z)"
    let result = db.executeUpdate(insertSQL, withParameterDictionary: ["x" : someVariable, "y" : someOtherVariable, "z" : thirdVariable])

The `:x` in the SQL, for example, tells SQLite (and FMDB) to look up the corresponding value in the dictionary using `x` as the key.

Typically, though, you'd just use the `?` placeholder syntax:

    let insertSQL = "INSERT OR REPLACE INTO foo (a, b, c) VALUES (?, ?, ?)"
    let result = db.executeUpdate(insertSQL, withArgumentsInArray: [someVariable, someOtherVariable, thirdVariable])

But the key point here is that this colon-syntax is not for inserting entire dictionaries in a table. It's for looking up a single string, number, `NSDate` or `NSData` object in a dictionary when replacing a placeholder string in the SQL. You cannot insert entire dictionaries/arrays as a single value. Technically, you certainly could save JSON string/`NSData` object before you decoded it with `JSONObjectWithData`, but that's not a practice I'd personally recommend, though that's up to you.

**Comment by mikewalkerjr** [comment]
Thank you I was just confused then. The placeholder syntax did the trick.

**Comment by robertmryan** [comment]
Very good.

By the way, if I didn't make this clear, when inserting values in SQL, you generally want to use one of the above placeholder patterns (usually `?` placeholder with `withArgumentsInArray` permutation). You should generally avoid using Swift string interpolation (i.e. the `\(variable)` syntax) or Objective-C `stringWithFormat`. Using the placeholders is far more robust.

**Comment by iTofu** [comment]
@robertmryan Thank you!
