### ISSUE TITLE
DB is not created

### ISSUE THREAD

**Issue by leekyungmoon** [ccgus/fmdb#364]
When my app is launched first, I create my db.
- (void)createDatabaseStructure{
  NSString *queryPath = [[NSBundle mainBundle] pathForResource:@"DBStructureGenerator" ofType:@"sql"];
  NSString *queryString = [NSString stringWithContentsOfFile:queryPath encoding:NSUTF8StringEncoding error:nil];
  if([db open]){
      [db executeQuery:queryString];
      NSLog(@"create & db open true");
      [db close];
  }else{
      //[db releaseSavePointWithName:<#(NSString *)#> error:<#(NSError *__autoreleasing *)#>]
  }
  }

and my DBStructureGenerator.sql is below : 
/*
  DBStructureGenerator.sql
*/

CREATE TABLE IF NOT EXISTS `usercart` (
  `id` INTEGER NOT NULL,
  `productid` INTEGER NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `campaignid` INTEGER NOT NULL,
  `startdate` DATETIME NULL,
  `enddate` DATETIME NULL,
  `martid` INTEGER NOT NULL,
  `martname` TEXT NOT NULL,
  `price` INTEGER NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE UNIQUE INDEX IF NOT EXISTS id_UNIQUE ON usercart(id);
CREATE UNIQUE INDEX IF NOT EXISTS productid_UNIQUE ON usercart(productid);

//

but when I execute query , i got an error DB Error: 1 "no such table: usercart"

Is there something missing?

**Comment by robertmryan** [comment]
OK, your code sample (just so we can read it; in the future, indent your code samples with four spaces and it will be formatted properly) is:

    - (void)createDatabaseStructure {
        NSString *queryPath = [[NSBundle mainBundle] pathForResource:@"DBStructureGenerator" ofType:@"sql"];
        NSString *queryString = [NSString stringWithContentsOfFile:queryPath encoding:NSUTF8StringEncoding error:nil];
        if ([db open]) {
            [db executeQuery:queryString]; NSLog(@"create & db open true");
            [db close];
        } else {
            //[db releaseSavePointWithName:<#(NSString *)#> error:<#(NSError *__autoreleasing *)#>]
        }
    }

A couple of issues:

1. You don't show the instantiation of `db`, nor do you show any response in either the `if` block or the `else` block, so we have no way of knowing whether your SQL to create the table was even reached.

2. You are not checking the response code from the `executeQuery` call. If it failed, did you look at `[db lastErrorMessage]` string? That will tell you precisely what went wrong.

3. You are calling `executeQuery`. That's for returning `FMResultSet` (e.g. from a `SELECT` statement). Whenever updating the database you'd generally use `executeUpdate`.

 But in this case, it looks like you're performing a series of SQL statements in a single call. In that case, you'd actually use `executeStatements`.

There are other issues, but those are the key ones, IMHO.

**Comment by clemensg** [comment]
Even better, use syntax highlighting for multi-line code fragments: https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting:
```objc
- (void)createDatabaseStructure {
    NSString *queryPath = [[NSBundle mainBundle] pathForResource:@"DBStructureGenerator" ofType:@"sql"];
    NSString *queryString = [NSString stringWithContentsOfFile:queryPath encoding:NSUTF8StringEncoding error:nil];
    if ([db open]) {
        [db executeQuery:queryString]; 
        NSLog(@"create & db open true");
        [db close];
    } else {
        //[db releaseSavePointWithName:<#(NSString *)#> error:<#(NSError *__autoreleasing *)#>]
    }
}
```

@LeeKyungMoon
I'd recommend using `FMDatabaseQueue` and executing the SQL statements in a transaction (`[queue inTransaction:^(FMDatabase *db, BOOL *rollback) { ...`). In this block you execute the `CREATE TABLE ..` query (with `executeUpdate`) and create the the two indices. In case anything goes wrong, just set `*rollback = YES` and return. And always check return values and print error messages.

Or just use https://github.com/layerhq/FMDBMigrationManager ;-)
