### ISSUE TITLE
why use `dispatch_sync` instead of `dispatch_async` in FMDatabaseQueue.m's inDatabase: method?

### ISSUE THREAD

**Issue by lzyy** [ccgus/fmdb#370]
in [FMDatabaseQueue's inDatabase: method](https://github.com/ccgus/fmdb/blob/master/src/fmdb/FMDatabaseQueue.m#L139)

```
- (void)inDatabase:(void (^)(FMDatabase *db))block {
    /* Get the currently executing queue (which should probably be nil, but in theory could be another DB queue
     * and then check it against self to make sure we're not about to deadlock. */
    
    dispatch_sync(_queue, ^() {
    //...
```

use `dispatch_sync` will block current thread, but the method seems to be an async operation which is big pitfall to newbies. why use `dispatch_sync` instead of `dispatch_async` + serial queue ?

**Comment by ccgus** [comment]
FMDB, as it's API works, is currently serial.  Existing code expects it to work that way, and changing it to async would break everything. 

In the future however, I really want to add async versions of the calls.
