### ISSUE TITLE
Improve documentation about FMDatabaseQueue

### ISSUE THREAD

**Issue by jschmid** [ccgus/fmdb#373]
By reading the documentation I misinterpreted something. This is not a request for help, but rather a request to improve the documentation for others that might get in the same path.

The [README](https://github.com/ccgus/fmdb/blob/c4d0ae7bd6df5e234cfe3faedc661252cb048a58/README.markdown#using-fmdatabasequeue-and-thread-safety) and the [source](https://github.com/ccgus/fmdb/blob/c4d0ae7bd6df5e234cfe3faedc661252cb048a58/src/fmdb/FMDatabaseQueue.h#L16) of `FMDatabaseQueue` state:

> Using a single instance of FMDatabase from multiple threads at once is a bad idea. **It has always been OK to make a FMDatabase object per thread**. Just don't share a single instance across threads.

Which lead me to believe that I could create two `FMDatabase` instances with the *same* database file, as long as I manage the threading stuff correctly. I came to this because I wanted to have a `FMDatabaseQueue` to write and one `FMDatabaseQueue` to read without having to wait for the write blocks to have executed on the queue. 

This is apparently [not the case](http://stackoverflow.com/a/30079185/183665), you should only create one `FMDatabase` per database file. 

Now, is that right? You **cannot** have two `FMDatabase` instances with the *same* database file? If so, should you/we improve the documentation to state that clearly?

**Comment by ccgus** [comment]
You're mixing up FMDatabase and FMDatabaseQueue.  You can have two FMDatabases, but you still have to be a bit careful for file-level locks.

My recommendation is to not use two FMDatabases, but rather just a single Queue.

**Comment by jschmid** [comment]
Well... as I said, the goal was not to ask for help but to point out that the documentation could be improved.

Thanks anyway :)
