### ISSUE TITLE
NULL values are returned as @"(null)" instead of nil by FMResultSet stringForColumn

### ISSUE THREAD

**Issue by erolbaykal** [ccgus/fmdb#378]
``` ObjectiveC
- (NSString*)stringForColumnIndex:(int)columnIdx {

    if (sqlite3_column_type([_statement statement], columnIdx) == SQLITE_NULL || (columnIdx < 0)) {
        return nil;
    }

    const char *c = (const char *)sqlite3_column_text([_statement statement], columnIdx);

    if (!c) {
        // null row.
        return nil;
    }

    return [NSString stringWithUTF8String:c];
}
```

Not sure what is going on here, but instead of nil, I get @"(null)" string literal.

**Comment by robertmryan** [comment]
Are you using zero-based index number? Have you looked at `lastErrorMessage`?

**Comment by tinkerjyc** [comment]
Thx a lot. 
I have solved my problem. 
I might send you a mail by mistake.
Whatever, thank you. 
 Best wish.


蒋燚铖 tinker





--
发自我的网易邮箱手机智能版



在 2015-06-04 20:18:59，"Rob Ryan" <notifications@github.com> 写道：


Are you using zero-based index number? Have you looked at lastErrorMessage?

**Comment by lzcuriosity** [comment]
您的邮件已经收到，我会尽快查阅，谢谢！Best Wishes!
