### ISSUE TITLE
Problem with release code.

### ISSUE THREAD

**Issue by adzy2k6** [ccgus/fmdb#396]
I am having an issue with fmdb. When i test my app in debug mode, my database, tables and entries are all created successfully. They are stored in a file in the libraries directory.

When I create an archive in release mode, and install it ad-hoc, the database file is created successfully, but the table creation fails, and the app crashes.

**Comment by robertmryan** [comment]
Perhaps share your code for building that path. Also, if the database is created and the table creation fails, what is the `[db lastErrorMessage]`?

**Comment by adzy2k6** [comment]
I have just added that to the code and checked. It says "out of memory". To get the path, I am using let path = NSSearchPathFordirectoriesInDomains(.LibraryDirectory, .UserDomainMask, true)[0] as! String (I am using Swift for development of this app). The out of memory error appears to happen after my code to create the tables. The table code follows the pattern of:

if !database.tableExists(DatabaseManager.TableName){

}

**Comment by adzy2k6** [comment]
I have just added that to the code and checked. It says "out of memory". To get the path, I am using let path = NSSearchPathFordirectoriesInDomains(.LibraryDirectory, .UserDomainMask, true)[0] as! String (I am using Swift for development of this app). The out of memory error appears to happen after my code to create the tables. The table code follows the pattern of:

if !database.tableExists(DatabaseManager.TableName){
let created = db.executeUpdate(DatabaseManager.TableCreateString, withArgumentsInArray: nil)
}

Curiously, it passes if an assert statement is placed within that if statement, which suggests to me that the code is skipped over. This same code works when the debug version is ran. DatabaseManager is a class that holds the fmdb database, and defines constants for use with the tables.

**Comment by adzy2k6** [comment]
it just occurred to me that more than one path could be returned from that method, and may be different between the two versions. I am going to try that out when i get a chance to work on it.

**Comment by robertmryan** [comment]
By the way, the "out of memory" is a bit misleading. You'll get that if either the database wasn't opened at all or if the open failed. If the open failed, you'd see a "error opening" message followed by some number. Did you see that? Did `open` return true?

**Comment by adzy2k6** [comment]
I have found the issue. Thank you for your comment, it helped me cotton on. The code to open the database was in an assert statement for debugging purposes. When put into release mode, then that line of code never got called anymore. It was a silly mistake on my part. I will add some more robust error checking around the code now, with some proper warnings.There shouldn't be more issues with normal operation now though.

Thank you for your help. Sorry if i wasted too much of your time.

**Comment by robertmryan** [comment]
No problem. You might want to "close" this issue now that you've resolved the problem.
