### ISSUE TITLE
Optimization in cachedStatementForQuery

### ISSUE THREAD

**Issue by wqyfavor** [ccgus/fmdb#407]
In my test with cacheStatement value as YES. I found that [NSSet objectsPassingTest] cost time that cannot be ignored. I know that statements with the same query sql should be cached in a set. But in most cases this set contains only one statement that is not occupied. 

This is my modification. I hope that this will be accepted by main branch.

```
- (FMStatement*)cachedStatementForQuery:(NSString*)query {

    NSMutableSet* statements = [_cachedStatements objectForKey:query];

    FMStatement* aStatement = [statements anyObject]; // select any one
    if (![aStatement inUse])
        return aStatement; // most cases
    else if ([statements count] == 1)
        return nil;

    return [[statements objectsPassingTest:^BOOL(FMStatement* statement, BOOL *stop) {

        *stop = ![statement inUse];
        return *stop;

    }] anyObject];
}
```

**Comment by wqyfavor** [comment]
@ccgus

**Comment by wqyfavor** [comment]
Profile with the same test cases.

Use original code
<img width="783" alt="screen shot 2015-09-18 at 4 03 36 pm" src="https://cloud.githubusercontent.com/assets/113776/9954937/8ae456da-5e1f-11e5-8548-c832b063facb.png">


With my modification
<img width="797" alt="screen shot 2015-09-18 at 4 04 30 pm" src="https://cloud.githubusercontent.com/assets/113776/9954964/c8e44a58-5e1f-11e5-8043-6db22898e9dd.png">

**Comment by ccgus** [comment]
Am I missing the pull request, or is it just the code snippet above?

**Comment by wqyfavor** [comment]
just codes above. I have already added to FMDB in my project. It works well.
