### ISSUE TITLE
Apple is using FMDB

### ISSUE THREAD

**Issue by modLX4** [ccgus/fmdb#409]
Apple is using FMDB in iOS 9 for their news app. Keep it up guys

-Febin Babu
![fmdb_result](https://cloud.githubusercontent.com/assets/12533332/10026000/eb0d2ca2-617c-11e5-88a9-8284cea97017.jpg)

**Comment by chandanankush** [comment]
congrats, keep it up guys

**Comment by ccgus** [comment]
Danke.
