### ISSUE TITLE
crash FMDBBlockSQLiteCallBackFunction

### ISSUE THREAD

**Issue by gongtao** [ccgus/fmdb#414]
I used FMDB in private dispatch_queue blocks, and received crash logs. I did not use any functions that contain FMDBBlockSQLiteCallBackFunction function. I used [FMDatabaseQueue inDatabase:] function to access database.

Crashed: com.xiaomi.micloud.sdk.contact.queue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000000000000

Thread : Crashed: com.xiaomi.micloud.sdk.contact.queue
0  libsystem_c.dylib              0x00000001979e96ac strlen + 12
1  MicIOSHelper                   0x00000001001e6f34 FMDBBlockSQLiteCallBackFunction + 213448
2  MicIOSHelper                   0x00000001001e6f34 FMDBBlockSQLiteCallBackFunction + 213448
3  MicIOSHelper                   0x00000001001e97b0 FMDBBlockSQLiteCallBackFunction + 223812
4  MicIOSHelper                   0x00000001001e8604 FMDBBlockSQLiteCallBackFunction + 219288
5  MicIOSHelper                   0x000000010020509c FMDBBlockSQLiteCallBackFunction + 336688
6  CoreFoundation                 0x000000018568d140 __NSArrayEnumerate + 484
7  MicIOSHelper                   0x0000000100204788 FMDBBlockSQLiteCallBackFunction + 334364
8  MicIOSHelper                   0x00000001002052dc FMDBBlockSQLiteCallBackFunction + 337264
9  MicIOSHelper                   0x000000010007e3fc -[MCRootViewController requestMiCloudChangedContacts:source:isEstimate:success:fail:] (MCRootViewController.m:319)
10 MicIOSHelper                   0x000000010007d70c __38-[MCRootViewController viewDidAppear:]_block_invoke (MCRootViewController.m:177)
11 libdispatch.dylib              0x000000019798d994 _dispatch_call_block_and_release + 24
12 libdispatch.dylib              0x000000019798d954 _dispatch_client_callout + 16
13 libdispatch.dylib              0x00000001979980a4 _dispatch_queue_drain + 1448
14 libdispatch.dylib              0x0000000197990a5c _dispatch_queue_invoke + 132
15 libdispatch.dylib              0x000000019799a318 _dispatch_root_queue_drain + 720
16 libdispatch.dylib              0x000000019799bc4c _dispatch_worker_thread3 + 108
17 libsystem_pthread.dylib        0x0000000197b6d22c _pthread_wqthread + 816
18 libsystem_pthread.dylib        0x0000000197b6cef0 start_wqthread + 4

**Comment by ccgus** [comment]
Well, something is calling it - com.xiaomi.micloud.sdk.contact.queue.  Looks like a 3rd party SDK
