### ISSUE TITLE
Problem with Swift 2.1

### ISSUE THREAD

**Issue by panagorn** [ccgus/fmdb#420]
Hello how can i use fmdb with swift 2.1 i get some errors. It was just fine with swift 1

**Comment by robertmryan** [comment]
What errors did you get? It works fine for me.

**Comment by panagorn** [comment]
NSSearchPathForDirectoriesInDomains(.DocumentDirectory,
            .UserDomainMask, true)
        
        let docsDir = dirPaths[0] 
        
        let databasePath = docsDir.stringByAppendingPathComponent(
            "contacts.db")

to the stringByAppendingPathComponent it says is unavailable

**Comment by robertmryan** [comment]
This is not a FMDB issue. This is a general Cocoa API issue. `stringByAppendingByPathComponent` doesn't exist on `String` class. You can use `NSString`, or use the newer `NSURL` methods:

    let documents = try! NSFileManager.defaultManager().URLForDirectory(.DocumentDirectory, inDomain: .UserDomainMask, appropriateForURL: nil, create: false)
    let fileURL = documents.URLByAppendingPathComponent("contacts.db")
    let db = FMDatabase(path: fileURL.path)

**Comment by panagorn** [comment]
ok thank you
