### ISSUE TITLE
Throwing errors?

### ISSUE THREAD

**Issue by robertmryan** [ccgus/fmdb#422]
Gus, I was thinking of implementing renditions of `executeUpdate` and `executeQuery` which have an `NSError **` parameter as their last parameter, something like:

```
- (FMResultSet *)executeQuery:(NSString *)sql values:(NSArray *)arguments error:(NSError * __autoreleasing *)error {
    FMResultSet *rs = [self executeQuery:sql withArgumentsInArray:arguments orDictionary:nil orVAList:nil];
    if (!rs && error) {
        *error = [self lastError];
    }
    return rs;
}

- (BOOL)executeUpdate:(NSString*)sql values:(NSArray *)arguments error:(NSError * __autoreleasing *)error {
    return [self executeUpdate:sql error:error withArgumentsInArray:arguments orDictionary:nil orVAList:nil];
}
```

The virtue of this is that it automatically permits the throwing of errors in Swift, e.g.:

```swift
do {
    try database.executeUpdate("create table test(x text, y text, z text)", values: nil)
    try database.executeUpdate("insert into test (x, y, z) values (?, ?, ?)", values: ["a", "b", "c"])
    try database.executeUpdate("insert into test (x, y, z) values (?, ?, ?)", values: ["e", "f", "g"])
    let rs = try database.executeQuery("select x, y, z from test", values: nil)
    while rs.next() {
        let x = rs.stringForColumn("x")
        let y = rs.stringForColumn("y")
        let z = rs.stringForColumn("z")
        print("x = \(x); y = \(y); z = \(z)")
    }
} catch let error as NSError {
    print("failed: \(error.localizedDescription)")
}
```

The only annoyance is that I had to use a unique name (I couldn't use `executeQuery:argumentsInArray:error:` because that conflicted with the existing `executeQuery:argumentsInArray:`), so I used `values`, instead. I actually like the `executeQuery:values:error:` name quite a bit, but it deviates (by necessity) from your existing method names. And it shortens the method down enough that it largely obviates the need for the Swift categories that I wrote before.

But before I submitted a pull request, I wanted to get your take on this. Thoughts?

**Comment by ccgus** [comment]
My initial thought was that there is a tiny chance that it would return the wrong error in a multithreaded environment- and it could!  BUT, not if the developer was using the queue properly.

So, sure- let's add this for the swift folks.

And, I'm wondering if maybe we can enforce this call to only happen if the queue is being used.  Maybe set a flag that says "hey, I'm currently operating in a queue, so it's all good", and otherwise fail if it isn't?

Thoughts on that?

**Comment by robertmryan** [comment]
I'm not sure that's necessary, because if if they were misusing FMDB like that, this becomes a race condition issue in _all_ error handling throughout FMDB, not just here. If you want, we could add a `@warning` to this effect in the comment for these methods, but then you would probably want to also add a similar `@warning` in _all_ methods that return error references. 

Anyway, I'll do a pull request for this and you can review.

**Comment by robertmryan** [comment]
See pull request https://github.com/ccgus/fmdb/pull/424.
