### ISSUE TITLE
FMDB with TvOS

### ISSUE THREAD

**Issue by combi83** [ccgus/fmdb#432]
Hi, I have a big problem about the use of FMDB with Apple Tv, in particular i can't open db in Apple TV app, while in the simulator everything is ok.
The error when i try to open db is: "error opening!: 14".
Do you know how to fix this problem?

Thank you

**Comment by angelcasado** [comment]
@combi83 There is a good chance that FMDB is trying to save the sqlite3 db file to storage which is forbidden on most tvOS apps.

**Comment by michalzelinka** [comment]
Yup, tvOS permits only **Caches** folder to work with (in other words, with read-write permissions). The only exception is `NSUserDefaults` storage located in **Library/Preferences**, which may be used up to 512 kB of size. Other locations like **Documents** or **Library** are sort of forbidden to work with on this platform.

**Comment by GLinnik21** [comment]
@ccgus We've actually been able to successfully use FMDB and SQLite on tvOS without any issues - we've demonstrated this in our [fork](https://github.com/appmetrica/appmetrica-sdk-ios/tree/main/AppMetrica_FMDB). Essentially, all that's needed to support this platform is just to add the appropriate flag for CocoaPods and SPM. Do you have any further developments on this?

**Comment by ccgus** [comment]
I'll ping @incanus, since he's graciously taken over the CocoaPods work.

**Comment by incanus** [comment]
To my knowledge (and trials) it doesn't look like we have to change the project `fmdb.xcodeproj` to explicitly support tvOS. I was able to add a line to the podspec to allow it to lint: 

```diff
--- a/FMDB.podspec
+++ b/FMDB.podspec
@@ -10,6 +10,7 @@ Pod::Spec.new do |s|
   s.ios.deployment_target = '11.0'
   s.osx.deployment_target = '10.13'
   s.watchos.deployment_target = '7.0'
+  s.tvos.deployment_target = '16.0'
   s.default_subspec = 'standard'
 
   # use the built-in library version of sqlite3
```

Then run this: 

```bash
$ pod spec lint --verbose --allow-warnings --fail-fast --platforms=tvos
```

@ccgus If you want to build upon https://github.com/ccgus/fmdb/issues/860#issuecomment-2028814619 and run with it, we might be able to get this in alongside the podspec version change, re-tag 2.7.10, and call this "experimental tvOS podspec support".

**Comment by GLinnik21** [comment]
> ```diff
>    s.ios.deployment_target = '11.0'
>    s.osx.deployment_target = '10.13'
>    s.watchos.deployment_target = '7.0'
> +  s.tvos.deployment_target = '16.0'
> ```

I think the tvOS deployment target should actually match that of iOS since tvOS is basically the same OS with some libraries missing.

**Comment by ccgus** [comment]
> I think the tvOS deployment target should actually match that of iOS since tvOS is basically the same OS with some libraries missing.

I'll defer to @incanus on that, since he's the one building it and putting git up.

**Comment by ccgus** [comment]
> @ccgus If you want to build upon [#860 (comment)](https://github.com/ccgus/fmdb/issues/860#issuecomment-2028814619) and run with it, we might be able to get this in alongside the podspec version change, re-tag 2.7.10, and call this "experimental tvOS podspec support".

Is re-tagging a thing we should do? Wouldn't that kind of screw up the releases? Or is it OK since we're just messing with pod files?

**Comment by incanus** [comment]
Re: deployment target, I'll take what @GLinnik21 says — I pulled the version I specified out of thin air, as `N - 1` from the latest version. 

For tagging, it probably doesn't technically matter. I think anyone using the podspec from the repo directly on disk would notice the version mismatch anyway and fix it in their working copy? We can probably roll this all into one since also, any tvOS issues would likely only pop up if someone else was linting the spec like I am (and why would they?)

**Comment by incanus** [comment]
Further, tvOS 11.0 appears to lint just fine. 

```diff
diff --git a/FMDB.podspec b/FMDB.podspec
index 88434e2..dbd6849 100644
--- a/FMDB.podspec
+++ b/FMDB.podspec
@@ -10,6 +10,7 @@ Pod::Spec.new do |s|
   s.ios.deployment_target = '11.0'
   s.osx.deployment_target = '10.13'
   s.watchos.deployment_target = '7.0'
+  s.tvos.deployment_target = '11.0'
   s.default_subspec = 'standard'
 
   # use the built-in library version of sqlite3
```

Using: 

```bash
$ pod spec lint --verbose --allow-warnings --fail-fast --platforms=tvos
```

**Comment by GLinnik21** [comment]
I agree. It would be a terrible idea to patch some code while SPM has a cache. But if the change is just 1 line in `podspec` that doesn't affect SPM users anyway, it's fine to move the tag.

**Comment by ccgus** [comment]
Alrighty, I've moved the tag!

**Comment by incanus** [comment]
Ok, published 2.7.10! For reference, since my working copy already had the tag, I had to `git tag -d 2.7.10` and then `git pull` to re-bring it down in the new spot. 

```bash
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  FMDB (2.7.10) successfully published
 📅  April 2nd, 18:20
 🌎  https://cocoapods.org/pods/FMDB
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

**Comment by GLinnik21** [comment]
Thank you very much, but it seems that you forgot to downgrade the tvOS version to 11.0 and pushed the changes with 16.0. 
Thank you for understanding and making the required adjustments.

**Comment by incanus** [comment]
Ah, sorry about that. I don't have commit access here, just CocoaPods push access, and I meant to be more explicit about asking @ccgus to hit that before release, but with two tickets involved I lost the thread. @ccgus will need to make those changes, but now since we're pushed, I think it will have to be a new release/tag & another push. 🫤

What about this plan of action for now? 

1. @ccgus can update the tvOS deployment target in the podspec to be ready for the next release
1. @GLinnik21 Can you just use a local checkout of FMDB with a locally-modified or forked tvOS for now? You can change the deployment target and then use `path => '/path/to/local/fmdb'`

**Comment by GLinnik21** [comment]
> 2\. @GLinnik21 Can you just use a local checkout of FMDB with a locally-modified or forked podspec for now? You can change the deployment target and then use `path => '/path/to/local/fmdb'` in your app/framework.

Yeah, I'll keep using our fork until the next release. Our project is an open-source library, so we can't use `path` in podspec.

**Comment by GLinnik21** [comment]
> I agree. It would be a terrible idea to patch some code while SPM has a cache. But if the change is just 1 line in `podspec` that doesn't affect SPM users anyway, it's fine to move the tag.

I guess I was wrong. #867

**Comment by incanus** [comment]
>  it seems that you forgot to downgrade the tvOS version to 11.0 and pushed the changes with 16.0

@ccgus took care of this with 2695b213425be46922692af27870fc97fcad89f7, release imminent, so closing here.
