### ISSUE TITLE
How do I perform a FTS on Chinese text?

### ISSUE THREAD

**Issue by neowinston** [ccgus/fmdb#433]
I'm trying a FTS on Chinese text. So far I've tried like so, with no results:

```
'CFStringRef SimplifiedChinese_LocaleIdentifier = CFSTR("zh-Hans");
CFLocaleRef chineseLocale = CFLocaleCreate(NULL, SimplifiedChinese_LocaleIdentifier);


g_simpleTok = [[FMSimpleTokenizer alloc] initWithLocale:chineseLocale];
[FMDatabase registerTokenizer:g_simpleTok withKey:@"simple"];'
```

**Comment by lauthu** [comment]
@neowinston have a look of this post: [http://hustlzp.com/post/2016/02/ios-full-text-search-using-sqlite-fts4](url)

**Comment by neowinston** [comment]
Please close this issue. It's already been solved a while back. Thanks!
