### ISSUE TITLE
FMDatabaseQueue is Blocking the main thread. 

### ISSUE THREAD

**Issue by BlindArcher** [ccgus/fmdb#436]
Hi, my app is stuck while I execute a updatestatus method from a background thread. I am executing it from a background thread, but somehow main thread getting blocked. Here is the method.

    -(void)updateStatus {
    
        if(isCalculating)return;
    
        isCalculating = YES;
        NSMutableArray *tableList = [[NSMutableArray alloc] init];
    
        [[IssMANAppDelegate appDelegate].dbQueue inDatabase:^(FMDatabase *db) {
            FMResultSet *resultsSet = [db executeQuery:@"SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"];
            while ([resultsSet next]){
                [tableList addObject:[resultsSet stringForColumn:@"name"]];
            }
            [resultsSet close];
        }];
    
        __block int totalRow = 0;
        __block int pendingRow = 0;
        //  totalPhotoRow = 0;
        __block int pendingPhotoRow = 0;
        __block int pendingDataDownload = 0;
        __block int pendingPhotoDownload = 0;
    
        //    __block NSInteger pendingPhotoRow = 0;
        [[IssMANAppDelegate appDelegate].dbQueue inDatabase:^(FMDatabase *db) {
            FMResultSet *resultSet = nil;
            resultSet = [db executeQuery:@"SELECT COUNT(*) C FROM media_content, media WHERE \
                     media.pk_id = media_content.media_pk_id AND \
                     media.status = 'active' AND \
                     media_content.is_dirty = 1"];
        
            while([resultSet next]){
                pendingPhotoRow = [resultSet intForColumn:@"C"];
            }
            [resultSet close];
        }];
    
    //    pendingPhotoRow = [MediaDAO getPendingUploadImages];
        for(int k=0;k<tableList.count;k++) {
        
            NSString* tableName = (NSString*) [tableList objectAtIndex:k];
        
            if([tableName isEqualToString:@"settings"])continue;
            if([tableName isEqualToString:@"sqlite_sequence"])continue;
            if([tableName isEqualToString:@"temp_purchased_transactions"])continue;
            if([tableName isEqualToString:@"latest_project_report_issue"])continue;
            if([tableName isEqualToString:@"role"])continue;
            if([tableName isEqualToString:@"event_type"])continue;
            if([tableName isEqualToString:@"rel_role_event_type_notification_type"])continue;
            if([tableName isEqualToString:@"rel_user_product"])continue;
            if([tableName isEqualToString:@"media_content"])continue;
        
            [[IssMANAppDelegate appDelegate].dbQueue inDatabase:^(FMDatabase *db) {
                NSString* sql = NULL;
                if([ISSManDBManager columnExists:@"status" inTableWithName:tableName andDB:db]) {
                
                    sql = [NSString stringWithFormat:@"SELECT COUNT(*) C FROM %@ where status <> 'deleted'",tableName];
                }
                else if([ISSManDBManager columnExists:@"sender_status" inTableWithName:tableName andDB:db]) {
                
                    sql = [NSString stringWithFormat:@"SELECT COUNT(*) C FROM %@ where sender_status <> 'deleted'",tableName];
                }
                else {
                
                    sql = [NSString stringWithFormat:@"SELECT COUNT(*) C FROM %@",tableName];
                }
            
                FMResultSet *resultSet = [db executeQuery:sql];
            
                while([resultSet next]) {
                    int rowCount = [resultSet intForColumn:@"C"];
                    if([tableName isEqualToString:@"media_content"]) {
    //                    totalPhotoRow += rowCount;
                    }
                    else {
                        totalRow += rowCount;
                    }
                }
            
                if([ISSManDBManager columnExists:@"status" inTableWithName:tableName andDB:db]) {
                    sql = [NSString stringWithFormat:@"SELECT COUNT(*) C FROM %@ WHERE is_dirty = 1 and status <> 'deleted'",tableName];
                }
                else if([ISSManDBManager columnExists:@"sender_status" inTableWithName:tableName andDB:db]) {
                    sql = [NSString stringWithFormat:@"SELECT COUNT(*) C FROM %@ WHERE is_dirty = 1 and sender_status <> 'deleted'",tableName];
                }
                else {
                    sql = [NSString stringWithFormat:@"SELECT COUNT(*) C FROM %@ WHERE is_dirty = 1",tableName];
                }
                resultSet = [db executeQuery:sql];
            
                while([resultSet next]) {
                    NSInteger rowCount = [resultSet intForColumn:@"C"];
                    pendingRow += rowCount;
                }
                [resultSet close];
            }];
        }
    
        [[IssMANAppDelegate appDelegate].dbQueue inDatabase:^(FMDatabase *db) {
    
            NSString* sql = NULL;
            sql = [NSString stringWithFormat:@"SELECT COUNT(media.pk_id) C \
               FROM media, media_content \
               WHERE \
               media.pk_id = media_content.media_pk_id AND \
               media.status = 'active' AND \
               media.update_date_time > media_content.last_sync_time"];
        
            FMResultSet *resultingSet = [db executeQuery:sql];
        
            while ([resultingSet next]) {
            
                int rowCount = [resultingSet intForColumn:@"C"];
                pendingPhotoDownload += rowCount;
            }
            [resultingSet close];
        
            NSString *sqlQuery = [NSString stringWithFormat:@"SELECT COUNT(pk_id) C FROM rel_user_product"];
            FMResultSet *resultsSets = [db executeQuery:sqlQuery];
        
        
            while([resultsSets next]) {
            
                int rowCount = [resultsSets intForColumn:@"C"];
                pendingDataDownload += rowCount;
            }
            [resultsSets close];
        }];
    
        double ratio = 0.0;
        if(totalRow)ratio = (double)pendingRow / (double)totalRow * 100.0;
    
        ratio = floor(100.0 - ratio);
        double downloadRation = 0.0;
        if(pendingDataDownload) downloadRation = 100.0;
    
        isCalculating = NO;
    
        NSMutableDictionary* syncStatusDic = [[NSMutableDictionary alloc] init];
        [syncStatusDic setObject:[NSNumber numberWithInt:totalRow] forKey:TOTAL_ROW];
        [syncStatusDic setObject:[NSNumber numberWithInt:pendingRow] forKey:PENDING_ROW];
        [syncStatusDic setObject:[NSNumber numberWithInt:pendingPhotoRow] forKey:PENDING_PHOTO];
        [syncStatusDic setObject:[NSNumber numberWithInt:pendingDataDownload] forKey:PENDING_DATA_DOWNLOAD];
        [syncStatusDic setObject:[NSNumber numberWithInt:pendingPhotoDownload] forKey:PENDING_PHOTO_DOWNLOAD];
    
        [self.delegate updateSyncStatusValues: [NSDictionary dictionaryWithDictionary:syncStatusDic]];
    }

This method is blocking my UI, though I start it from a background thread and using only one instance of FMDatabaseQueue.

**Comment by ccgus** [comment]
The inDatabase: method doesn't do anything in the background or async.  So if you're calling this method on the main thread, it'll be executed on the main thread.  So make sure updateStatus is called on a background thread.

**Comment by robertmryan** [comment]
If you try use `inDatabase` from the main thread while `updateStatus` is busy doing `inDatabase` calls from another thread, that main thread's attempt will block until `updateStatus` exits its `inDatabase` call. The entire purpose of `FMDatabaseQueue` is to synchronize attempts to interact with the database simultaneously from different threads. 

But I don't see anything here that would block the `FMDatabaseQueue` for very long. So unless you're calling this a lot, I'm hard pressed to see how this would affect the main thread significantly. How long does this `updateStatus` call take?

**Comment by BlindArcher** [comment]
It takes almost 40 sec to complete. And I am calling this from a background thread. My approach is as follow 

Account page (a background thread starts and call synStatus class) > Sync status (a timer starts every 20 sec and call SyncStatusOperationQueue) > SyncStatusOperationQueue (updateStatus method is called)

I started my call from a background thread, after that a NSOperation class which will also runs in background as per my understanding, and in that NSOperation's subclass syncStatus is called.

**Comment by robertmryan** [comment]
OK, first, 40 seconds to run is a lot. If accessing database from multiple threads, you have to get in and out far more quickly than that. So I'd use time profiler in Xcode's Instruments to identify which call is causing the greatest delay. Once you find the offending queries, I'd use SQLite's `EXPLAIN` to identify the source of the bottleneck. For example, you might want to add indexes that match your `WHERE` clause. 

Also, when I read that you're triggering something every 20 seconds, that raises red flags, too.

But this isn't the right forum to be diagnosing this. This forum is for raising issues about FMDB itself, not for debugging your use of FMDB. I'd suggest your posting your questions to either http://stackoverflow.com or http://codereview.stackexchange.com.
