### ISSUE TITLE
DB Error: 1 "near "LIMIT": syntax error"

### ISSUE THREAD

**Issue by nanom1t** [ccgus/fmdb#445]
Hello.

I get an error "DB Error: 1 "near "LIMIT": syntax error" in SQL queries with limits:

DELETE FROM table WHERE id = '1'
UPDATE tabke SET column='test' WHERE id = '1' LIMIT 1

Thanks

**Comment by mro** [comment]
there is IMO no `LIMIT` for `UPDATE`: https://www.sqlite.org/lang_update.html

**Comment by nanom1t** [comment]
Ok, thanks for quick reply.
