### ISSUE TITLE
No such module FMDB in SWIFT project

### ISSUE THREAD

**Issue by RyanKim01** [ccgus/fmdb#448]
This is a duplicate #392 and I just wanted to bring it up again since it seems like there is something going on with master branch. Not sure whether master branch works in Objective-C, but it clearly does not work in Swift project. I tried installing it with cocoapods. 

If anyone knows what's going on, please let me know.

**Comment by daffodilistic** [comment]
Master branch seems okay, but only on CocoaPods 0.39.0. Upgrading to CocoaPods 1.0.0.beta.4 breaks FMDB

**Comment by joepasq** [comment]
@daffodilistic I'm seeing this issue with a Swift project on cocoa pods 1.2.1 and Xcode 8.3.3. Has this been improved?

**Comment by robertmryan** [comment]
What version of FMDB did CocoaPods fetch for you? It should have (at the time I'm writing this) retrieved FMDB 2.7.2.

If you got an old version you might try updating Cocoapods:

```bash
$ pod update
```

**Comment by joepasq** [comment]
@robertmryan cocoa pods had downloaded 2.5. I just updated to 2.7.2 and it appears to be fixed. It must have been that I had not updated the local cocoa pods repository in a while. Thank you!
