### ISSUE TITLE
Outdated readme

### ISSUE THREAD

**Issue by tirrorex** [ccgus/fmdb#449]
Hello, i'm trying to use the data sanitization part of the readme for my swift project but it seems outdated, methods like executeUpdateWithFormat are not there, simple update method is not there either, what do you guys use for multiple types query?

**Comment by robertmryan** [comment]
I agree that this section is, stylistically, a bit dated. We can take a look at that.

Having said that, I would personally advise against `executeUpdateWithFormat`, entirely, but especially from Swift. I would suggest sticking with `executeUpdate` with `values` when using Swift 2, as shown in the [Swift section](https://github.com/ccgus/fmdb#swift) of the readme. It's the most concise format from Swift and offers error handling.

But if there are particular examples that you think would be especially valuable, feel free to leave them in a further comment here. We'll take a look and consider incorporating it into our revision.

**Comment by ccgus** [comment]
Yea, I wouldn't use executeUpdateWithFormat - we'll be removing that in 3.0, one of these days.

**Comment by tirrorex** [comment]
That's the thing, i don't see the "values" option, i have array, dictionnary and VAList. Unless of course by values you meant VAList.

**Comment by robertmryan** [comment]
Do I infer from your other question that you asked and subsequently closed that you found it? Make sure you have the latest version.

**Comment by tirrorex** [comment]
I closed it because i forgot i already had one issue opened T_T, no point of having both, if the latest version is 2.5 i already have it, didn't set a particular version in the podfile

**Comment by robertmryan** [comment]
I've bumped the podspec and tagged the release, so if you update your CocoaPods, you should see the `values` rendition. Check and let us know.

**Comment by tirrorex** [comment]
I specified  pod 'FMDB', :git => 'https://github.com/ccgus/fmdb.git' otherwise the version stayed at 2.5, but i still cannot get the new methods, is there a special branch to specify maybe?

**Comment by robertmryan** [comment]
I just updated it a few hours ago. When you update your cocoapods, do you not get the update?

**Comment by tirrorex** [comment]
By specifying the github source i got the 2.5.2 version "Installing FMDB 2.5.2 (was 2.5)" but no new methods
![screen shot 2015-12-23 at 12 55 19](https://cloud.githubusercontent.com/assets/8297740/11976035/7adeb41a-a974-11e5-9274-25d6f78b3c0a.png)

**Comment by robertmryan** [comment]
Can you look at the FMDB headers and compare to https://github.com/ccgus/fmdb/blob/master/src/fmdb/FMDatabase.h. Do you not have the values method that exists there? You might need to "Clean" and. "Build"

**Comment by tirrorex** [comment]
I assume this "- (BOOL)executeUpdate:(NSString*)sql values:(NSArray *)values error:(NSError * __autoreleasing *)error;" is the method?
By clean do you mean cleaning the project? If so it will have to wait, my project use j2ojb-c so i have about 1.5go to redownload after every clean and my current connection doesn't allow it

**Comment by robertmryan** [comment]
By "Clean" I simply mean choosing "Clean" from Xcode's "Product" menu. When you update code (esp outside of Xcode), you have to give it a chance to rebuild its cached data associated with that code. Either choose "Clean" and "Build" from "Product" menu, or, in extreme cases, find the derived data folder (found by going to "locations" tab in Xcode's preferences), quit Xcode, empty that derived data folder, and then restart Xcode.

**Comment by tirrorex** [comment]
Yup that's what i thought, could you keep the issue open the time i got a connection strong enough to do that please? I will update once i got the chance to do it, it should indeed fix the problem since the headers are good

**Comment by robertmryan** [comment]
I'm not following why you have to wait. "Clean" erases intermediate compilation files, not stuff you've downloaded. But, if, out of abundance of caution, you'd rather wait until you have access to a high speed connection, feel free.

**Comment by tirrorex** [comment]
Because i cannot rebuild without rebuilding jre and it has to download 1.5gB, cleaning the project cleans everything so..

**Comment by tirrorex** [comment]
Updating the issue.
After cleaning and rebuild i got the non-modular header issue preventing me from building and having auto-completion, workaround by putting fmdb and pods in public does not work anymore.
![screen shot 2015-12-28 at 09 21 50](https://cloud.githubusercontent.com/assets/8297740/12015941/9f81a560-ad44-11e5-992f-1dec71ece0f2.png)

**Comment by robertmryan** [comment]
We're working on version 2.6 which integrating that `swiftFramework` into the main branch (it's not 100% backward compatible, which is why we've been cautious about rolling that out, but the non-modular header is such a big deal that we think it's worth it). 

Until that point, if you have to use the `swiftFramework`, then use `executeUpdate:withArgumentsInArray:`.

**Comment by tirrorex** [comment]
Okay, will wait for the next version then, have a good day
