### ISSUE TITLE
Recommended Swift primitive type mapping for INTEGER primary key?

### ISSUE THREAD

**Issue by rlaferla** [ccgus/fmdb#452]
What is the recommended Swift primitive type mapping for INTEGER primary keys?  What FMResultSet method should I call to retrieve it?

e.g.

```
CREATE TABLE IF NOT EXISTS MYRECORD ('id' INTEGER PRIMARY KEY,  'name' TEXT)

class MyRecord {
  var id: Int
  var name: String
}
```

but

```
myrecord.id = rs.intForColumn("id")
```

 yields the error message:

```
Cannot assign value of type 'Int32' to type 'Int!'
```

should I use:

```
myrecord.id = (Int)(rs.intForColumn("id"))
```
or should I change the primitive type to Int32?

**Comment by rlaferla** [comment]
ANSWER:

Swift:  Int
FMDB:  rs.longForColumn("id")

**Comment by robertmryan** [comment]
Regarding rationale, see https://github.com/ccgus/fmdb/issues/291#issuecomment-166688509.
