### ISSUE TITLE
inDeferredTransaction example in Swift?

### ISSUE THREAD

**Issue by rlaferla** [ccgus/fmdb#453]
Is there an inDeferredTransaction example in Swift?

**Comment by robertmryan** [comment]
The syntax is identical to `inTransaction`.

**Comment by rlaferla** [comment]
Can you show me a simple example?  I think it's the mutable pointer that's confusing me.

**Comment by robertmryan** [comment]
Here's an example:

    queue.inTransaction { db, rollback in
        do {
            try db.executeUpdate("INSERT INTO myTable VALUES (?)", values: [1])
            try db.executeUpdate("INSERT INTO myTable VALUES (?)", values: [2])
            try db.executeUpdate("INSERT INTO myTable VALUES (?)", values: [3])
            
            if whoopsSomethingWrongHappened {
                rollback.memory = true
                return
            }

            try db.executeUpdate("INSERT INTO myTable VALUES (?)", values: [4])
            try db.executeUpdate("INSERT INTO myTable VALUES (?)", values: [5])
        } catch {
            print(error)
        }
    }
