### ISSUE TITLE
Consequences of sqlite3.h import removals

### ISSUE THREAD

**Issue by clemensg** [ccgus/fmdb#456]
Hi, it seems that commit 7da973d694c177edc1358cfa059d1e6068c42061 removed all sqlite3 imports from the header files.
It's not just an issue for people using "raw" `sqlite3*` pointers, this breaks the build of existing Objective-C projects who relied upon constants like SQLITE_OPEN_READWRITE to be present when calling `+ (instancetype)databaseQueueWithPath:(NSString*)aPath flags:(int)openFlags;`.

Shouldn't we import sqlite3.h in those headers, containing methods with openFlags arguments, e.g. in FMDatabaseQueue.h ? Alternatively, we could redefine the constants with other names (like FMDB_OPEN_READWRITE) to avoid name clashes, but that's kind of ugly.
Otherwise, users have to add an import statement to every file where they use a FMDB method with SQLite flags.

**Comment by ccgus** [comment]
Adding #import <sqlite3.h> isn't a huge burden for this change. I think more folks were having problems getting FMDB to work correctly with swift, so it was a worthwhile tradeoff in that regards.
