### ISSUE TITLE
How Not Case sensitive for Russian?

### ISSUE THREAD

**Issue by peterhoucll** [ccgus/fmdb#460]
1. select * from group where memo like '%творог%'
I could not find any data.

2. select * from group where memo like '%Творог%'
I can find the data.

You can be resolved? Thank you.

**Comment by billymeltdown** [comment]
Hi @peterhoucll,

This isn't a bug, the problem you are trying to solve is dependent on the underlying SQLite syntax and matching, FMDB doesn't have any bearing on this. You'll need to either change your matching expression or employ something more advanced like ICU as noted in this section of the SQLite docs:

https://www.sqlite.org/lang_expr.html#like

> **Important Note:** SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression **'a' LIKE 'A'** is TRUE but **'æ' LIKE 'Æ'** is FALSE. The ICU extension to SQLite includes an enhanced version of the LIKE operator that does case folding across all unicode characters.

Hope that helps!

**Comment by peterhoucll** [comment]
Thank you for your answer.

We are looking for three days, but did not find a complete information. This seems to be a difficult thing for add ICU extended, FMDB can include this feature?

Should be a lot of people want this function, thank you very much.

**Comment by ccgus** [comment]
This isn't something that FMDB will be adding, sorry.
