### ISSUE TITLE
swift catch error

### ISSUE THREAD

**Issue by jackyzh** [ccgus/fmdb#461]
When catch error of `executeUpdate`, there will be `The operation couldn’t be completed. (Foundation._GenericObjCError error 0.)` or something like that error message. I am wondering if there is a way to make these error more obviously except logError = True.

Thank you for your awesome work.

**Comment by robertmryan** [comment]
Can you please you please share reproducible example of the problem?

**Comment by jackyzh** [comment]
when trying to insert two same object with primary key restriction, it will throw this error.

e.g: 

    create table TEST(id int primary key)
    insert into TEST (id) values (?), values: [1]
    insert into TEST (id) values (?), values: [1]

**Comment by robertmryan** [comment]
Excellent catch. Thanks. I'm a little surprised that this issue wasn't noticed earlier, as it appears to be a very longstanding bug. The `executeUpdate` was capturing errors that resulted from `sqlite3_prepare_v2` (e.g. SQL syntax errors), but not errors that occurred in `sqlite3_step` (e.g. violation of keys or the like).

This is now remedied in version 2.6.2.

So now, this code:

```swift
let documents = try! NSFileManager.defaultManager().URLForDirectory(.DocumentDirectory, inDomain: .UserDomainMask, appropriateForURL: nil, create: false)
let fileURL = documents.URLByAppendingPathComponent("test.sqlite")

let _ = try? NSFileManager.defaultManager().removeItemAtURL(fileURL)

let db = FMDatabase(path: fileURL.path!)
if !db.open() { fatalError("cannot open db") }

do {
    try db.executeUpdate("create table TEST(id int primary key)", values: nil)
    try db.executeUpdate("insert into TEST (id) values (?)", values: [1])
    try db.executeUpdate("insert into TEST (id) values (?)", values: [1])
} catch {
    print(error)
}
```

Will now generate this error:

> Error Domain=FMDatabase Code=19 "UNIQUE constraint failed: TEST.id" UserInfo={NSLocalizedDescription=UNIQUE constraint failed: TEST.id}
