### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by kenshi** [ccgus/fmdb#462]
Hello
Consult an error in the build.

 It was installed in pod 'FMDB'

If a build error occurs.

-------------------------------------------------- -
  "_OBJC_CLASS _ $ _ FMDatabaseQueue", referenced from:
objc-class-ref in DBHelper.o

ld: symbol (s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
-------------------------------------------------- ---

How do you solve?

thanks!!

**Comment by ccgus** [comment]
Add FMDatabaseQueue.m to your target.
