### ISSUE TITLE
Please update central cocaopods repo with 2.6.2

### ISSUE THREAD

**Issue by mackoj** [ccgus/fmdb#465]
Hi,

FMDB version 2.6 does not work on Cocoapods actually because the podspec is missing some information from this fix https://github.com/ccgus/fmdb/commit/ee3bf29d8cce86cc5b2108bdaa61fa05a579c766 . Please consider update the Cocoapods specs central repo.

![screen shot 2016-02-03 at 15 30 09](https://cloud.githubusercontent.com/assets/661647/12785100/08baf794-ca8b-11e5-9bfc-e16cd7177c0b.png)

Thank you

**Comment by ccgus** [comment]
You'll need to import sqlite3.h

**Comment by mackoj** [comment]
Ok thanks
