### ISSUE TITLE
lastInsertRowId returns 0

### ISSUE THREAD

**Issue by andrey-lisovskiy** [ccgus/fmdb#473]
How can I get lastInsertRowId correctly?
`[_database lastInsertRowId]` always returns 0 for me.

**Comment by andrey-lisovskiy** [comment]
I've found that lastRowId can be retrieved while connection is opened, is it correct?

**Comment by robertmryan** [comment]
Yes, `lastInsertRowId` wI'll not work if you call it after that database is closed, but works fine if you call it immediately after performing the insert.
