### ISSUE TITLE
xCode 7.3 Analysis warning in FMDatabase.m

### ISSUE THREAD

**Issue by AshrafJaddo** [ccgus/fmdb#476]
with xCode 7.3 I am seeing a new Analysis warning from FMDatabase.m 
![screen shot 2016-03-22 at 2 39 38 pm](https://cloud.githubusercontent.com/assets/10867944/13963491/f83bc110-f03b-11e5-84a1-f4dcf53e7c16.png)

should I switch the first line in setCachedStatement to
 `query =  query ? [query copy] : @""`
 or check for nil and bail out if needed.

**Comment by ccgus** [comment]
You should change your code when you call this to make sure the query isn't nil. Running the analyzer on FMDatabase in it's own project doesn't show this problem.

**Comment by frijole** [comment]
I just noticed this when running the analyzer against a project at work that includes FMDB and was hoping it was just misuse in our end, but when I opened the fmdb project from the latest release in Xcode 9.4.1 and ran the analyzer it threw the same warning in `setCachedStatement:forQuery:`

**Comment by ccgus** [comment]
Yea, looks like Xcode 9.4 has something new in it. Looking at the code, I don't see how the path will fail, but I'll fix things up so that clang-sa is quiet now
