### ISSUE TITLE
beginTransaction() creates exclusive transaction

### ISSUE THREAD

**Issue by vvit** [ccgus/fmdb#477]
Hi guys. Please check this.
We have a `beginTransaction()` method which according to its name should execute `BEGIN TRANSACTION` SQL command. Instead it executes: `BEGIN EXCLUSIVE TRANSACTION`.
Unlike `beginDeferredTransaction()` which works as expected and executes `BEGIN DEFERRED TRANSACTION`.
Is this a naming issue?
Thanks.

**Comment by ccgus** [comment]
It's historical. beginTransaction came first, and did the exclusive.

**Comment by Mattijah** [comment]
Hi @ccgus

> It's historical. beginTransaction came first, and did the exclusive.

Why does the __wrapper__ replicate at least 8 years old functionality and why is the functionality actually replicated? I have to admit it is pretty confusing. `beginTransaction()` as the name says should execute `"BEGIN TRANSACTION"` (no matter what it does). I don't think the wrapper should replicate an obsolete/changed behaviour of SQLite database. If somebody needed something like this he should not upgrade the database at first place.

I personally see this as an issue. I don't know what other people think but when I look at SQLite docs and I see that `"BEGIN TRANSACTION"` starts a `DEFERRED` transaction behaviour I would expect `beginTransaction()` to do the same. What's your opinion? 🙂

**Comment by ccgus** [comment]
I suppose it's something we can track for 3.0.
