### ISSUE TITLE
Key is wrong, but the return is Yes

### ISSUE THREAD

**Issue by xiongcaixing1986** [ccgus/fmdb#478]
FMDatabase 
- (BOOL)setKey:(NSString*)key; 
Key is wrong, but the return is Yes

**Comment by ccgus** [comment]
You'll have to debug it with your linked crypto library. FMDB doesn't provide one, so you'll need to dig into whatever it is you're using.

**Comment by xiongcaixing1986** [comment]
I  linked sqlcipher crypto library, Break point into the sqlite3_key method，But the result is wrong.
You can try
- (BOOL)setKeyWithData:(NSData *)keyData {
#ifdef SQLITE_HAS_CODEC
    if (!keyData) {
        return NO;
    }
    
    int rc = sqlite3_key(_db, [keyData bytes], (int)[keyData length]);
    
    return (rc == SQLITE_OK);
#else
#pragma unused(keyData)
    return NO;
#endif
}

**Comment by xiongcaixing1986** [comment]
https://www.zetetic.net/sqlcipher/ios-tutorial/

`- (BOOL)setKeyWithData:(NSData *)keyData {
#ifdef SQLITE_HAS_CODEC
    if (!keyData) {
        return NO;
    }
    
    int rc = sqlite3_key(_db, [keyData bytes], (int)[keyData length]);
    
    if (rc == SQLITE_OK) {
        rc = sqlite3_exec(_db, (const char*) "SELECT count(*) FROM sqlite_master;", NULL, NULL, NULL);
    }
    
    return (rc == SQLITE_OK);
#else
#pragma unused(keyData)
    return NO;
#endif
}`

**Comment by xiongcaixing1986** [comment]
https://www.zetetic.net/sqlcipher/ios-tutorial/

`
- (BOOL)setKeyWithData:(NSData *)keyData {
#ifdef SQLITE_HAS_CODEC
    if (!keyData) {
        return NO;
    }
    
    int rc = sqlite3_key(_db, [keyData bytes], (int)[keyData length]);
    
    if (rc == SQLITE_OK) {
        rc = sqlite3_exec(_db, (const char*) "SELECT count(*) FROM sqlite_master;", NULL, NULL, NULL);
    }
    
    return (rc == SQLITE_OK);
#else
#pragma unused(keyData)
    return NO;
#endif
}
`

**Comment by xiongcaixing1986** [comment]
https://www.zetetic.net/sqlcipher/ios-tutorial/

`- (BOOL)setKeyWithData:(NSData *)keyData {
#ifdef SQLITE_HAS_CODEC
    if (!keyData) {
        return NO;
    }
    
    int rc = sqlite3_key(_db, [keyData bytes], (int)[keyData length]);
    
    if (rc == SQLITE_OK) {
        rc = sqlite3_exec(_db, (const char*) "SELECT count(*) FROM sqlite_master;", NULL, NULL, NULL);
    }
    
    return (rc == SQLITE_OK);
#else
#pragma unused(keyData)
    return NO;
#endif
}`
