### ISSUE TITLE
FMDatabaseQueue must support Swift's @noescape

### ISSUE THREAD

**Issue by virl** [ccgus/fmdb#481]
FMDatabaseQueue must support Swift's @noescape for inDatabase() and inTransaction() methods.

**Comment by robertmryan** [comment]
I'm not sure about "must", but it certainly would be nice if it did, as it offers opportunities for further optimizations in the Swift code. But, AFAIK, there is no attribute setting in Objective-C to mark a method as `@noescape`, not yet at least.

**Comment by virl** [comment]
@robertmryan That can be solved by Swift-only implementation of FMDB.

The iOS world is moving to Swift.

**Comment by robertmryan** [comment]
Lol. Yes, a port to Swift would allow `@noescape`. 

There are actually far broader redesign considerations (e.g. given that `FMDatabaseQueue` is designed for multithreaded environment, which, by definition, could block, its `inDatabase` and `inTransaction` calls should be, or at least offer, asynchronous renditions, in which case they wouldn't be `@noescape`).

Anyway, I will discuss it with Gus, as there are a long list of features being considered for v3.

**Comment by virl** [comment]
@robertmryan Thanks.
