### ISSUE TITLE
Dyld Error Message:

### ISSUE THREAD

**Issue by Rjmaurya13** [ccgus/fmdb#482]
I am getting this issue when installing in my iPad with distribution profile. My application got crashed in device. I found below error in device log.

Dyld Error Message:
Dyld Message: Library not loaded: @rpath/FMDB.framework/FMDB

**Comment by ccgus** [comment]
I'm not really an expert with iOS stuff, but it looks like the FMDB framework isn't being included in your app.

**Comment by Allendar** [comment]
This likely has to do with build settings for Debug/Release. If your app even managed to build for some reason, then you're likely having an older distribution profile that does not include the headers of the framework to be included. This causes all weird stuff where your Debug builds and even your Release builds in the Simulator work totally fine, but when deployed causing random dependencies errors.

For what your error says tho; it is very unlikely that you managed to get it build and into an IPA without getting any other errors. Have you suppressed or manually adjusted build settings?

**Comment by iblacksun** [comment]
@Rjmaurya13 This is an iOS bug and fixed in iOS 9.3.2 and later. 
See https://github.com/artsy/eigen/issues/1246
