### ISSUE TITLE
add ability to use format strings with queries

### ISSUE THREAD

**Issue by mohammad-rahchamani** [ccgus/fmdb#488]
we should be able to pass values to formatted string instead of concatenating it.
like this :

`[database executeQuery:"SELECT * FROM myTable WHERE myKey = %@", myKeyString];`

**Comment by robertmryan** [comment]
Clearly, you could do:

```objc
[database executeQuery:"SELECT * FROM myTable WHERE myKey = ?", myKeyString];
```

I'm assuming you closed this because you reconsidered both this issue your the associated pull request https://github.com/ccgus/fmdb/pull/489. I agree; FMDB already has established mechanisms for binding values to placeholders in the SQL.

**Comment by mohammad-rahchamani** [comment]
I realized that. Thank you for your response.
