### ISSUE TITLE
cocoapods 1.0 default_subspecs

### ISSUE THREAD

**Issue by donileo** [ccgus/fmdb#490]
I am getting an error installing fmdb with cocoapods 1.0

[!] The `FMDB` pod failed to validate due to 1 error:
    - ERROR | attributes: Can't set `default_subspecs` attribute for subspecs (in `FMDB/standalone`).

**Comment by srivkas** [comment]
I have this issue too, this happen because only the root spec can have "default subspecs" please delete default_subspecs not in the root element. what can i do till you will fix this issue?

**Comment by ccgus** [comment]
Someone will need to submit a patch for this.

**Comment by ahti** [comment]
I think just deleting the default_subspec for the standalone subspect would cause that subspec to always be built with FTS support, which I'm not sure is desirable. I'm also not very experienced in writing podspecs so I may be wrong.

@blakewatters, you authored the last few significant commits to the podspec. Do you know what the right solution here is?

**Comment by BennettSmith** [comment]
Submitted pull request that resolves this issue.  See https://github.com/ccgus/fmdb/pull/496

**Comment by ccgus** [comment]
I've merged it- thanks @BennettSmith .
