### ISSUE TITLE
A Memory Leak

### ISSUE THREAD

**Issue by LoserForLoser** [ccgus/fmdb#497]
When I check the memory leak,There is a message in the FMDatabase.m file:Key argument to 'setObject:forKey:' cannot be nil
In this position:
- (void)setCachedStatement:(FMStatement*)statement forQuery:(NSString*)query {
    
    query = [query copy]; // in case we got handed in a mutable string...
    
    [statement setQuery:query];
    
    [_cachedStatements setObject:statement forKey:query];    <------(At here)
    
    FMDBRelease(query);
}
What should I do?

**Comment by ccgus** [comment]
Don't pass a nil query.

**Comment by mahsaniq** [comment]
You can change the following code snippet on line numbers 1063 to 1071 in FMDatabase.m file:
```
    if (_shouldCacheStatements && !cachedStmt) {
        cachedStmt = [[FMStatement alloc] init];
        
        [cachedStmt setStatement:pStmt];
        
        [self setCachedStatement:cachedStmt forQuery:sql];
        
        FMDBRelease(cachedStmt);
    }
```

TO

```
    if (_shouldCacheStatements && !cachedStmt) {
        cachedStmt = [[FMStatement alloc] init];
        
        [cachedStmt setStatement:pStmt];
        
        if (sql) {
            [self setCachedStatement:cachedStmt forQuery:sql];
        }
        
        FMDBRelease(cachedStmt);
    }
```

**Note:**
⌘ = Command
⇧ = Shift
Press ⇧+⌘+B to Analyze.

OR

Select Product -> Analyze

Hope it resolves your issue.
