### ISSUE TITLE
Newbie question regarding thread safety

### ISSUE THREAD

**Issue by mauron85** [ccgus/fmdb#505]
I was just reading sqlite docs and FMDatabaseQueue regarding thread safety.
But is FMDatabaseQueue really needed when sqlite is in Multi-thread or Serialized mode?

**Comment by ccgus** [comment]
I don't know about serialized mode, but it's needed in multithreaded mode. That (at least last I had read up on it) means you can share contexts across threads, not use use the same context on multiple threads.

**Comment by ccgus** [comment]
Just found the docs on serialized: In serialized mode, SQLite can be safely used by multiple threads with no restriction

However, I can't guarantee that FMDatabase is thread safe (I'm pretty sure it isn't, especially with caching statements). Your best bet is to just use FMDatabaseQueue

**Comment by mauron85** [comment]
If I understand it correctly using sqlite in multithreads are just fine when you don't share some db handle (connection) opened with sqlite3_open. In serialized mode, there is practically no restriction.

Just read source code of FMDB and found _db member which is basically shared sql connection. But that could be easily refactored, probably to open connection in executeQuery. Each query can have own connection (why not?).

What is the problem with caching statements?

**Comment by ccgus** [comment]
The caching statements uses a NSMutableDictionary, which isn't thread safe.

Opening a new statement every time in executeQuery isn't something we're going to do. One FMDatabase == one sqlite connection. You might look into FMDatabasePool if you want lots of connections.

**Comment by mauron85** [comment]
>Opening a new statement every time in executeQuery isn't something we're going to do.

Understand, that it is very uncommon, but is it just personal preference or is there any real argument against it?

The problem with FMDatabasePool is that is can get deadlocked (as mentioned in header file).

My point is that sqlite actually has nice lock mechanism that while one thread on separate connection is writing other get SQLITE_BUSY retval.
```
  while (continueTrying) {
    retval = sqlite_exec(db, sqlQuery, callback, 0, &msg);
    switch (retval) {
      case SQLITE_BUSY:
        Log("[%s] SQLITE_BUSY: sleeping fow a while...", threadName);
        sleep a bit... (use something like sleep(), for example)
        break;
      case SQLITE_OK:
        continueTrying = NO; // We're done
        break;
      default:
        Log("[%s] Can't execute \"%s\": %s\n", threadName, sqlQuery, msg);
        continueTrying = NO;
        break;
    }
  }
  return retval;
```

How is this handled in FMDB? Are those thread waiting for lock? If so, for how long? Asking because not obj c expert. Thank for your time and patience, hopefully not wasting it too much :-)

**Comment by ccgus** [comment]
Meant to say "opening a new connection every time". But at any rate- it's not a personal pref, it's just slower that way.

So, check out the FMDatabase source for the answers to your SQLITE_BUSY questions. That stuff is all C.

**Comment by mauron85** [comment]
I found testBusyRetryTimeout, which is basic test for SQLITE_BUSY within single thread and I understand how it works. But what happens when multiple thread will try to use FMDatabaseQueue?. I believe dispatch_sync in FMDatabaseQueue is key to answer somehow.

**Comment by ccgus** [comment]
`man dispatch_sync` gives a better answer than I could.
