### ISSUE TITLE
lowercaseString necessary?

### ISSUE THREAD

**Issue by verveadam** [ccgus/fmdb#509]
See stringForColumn, columnIndexForName inside of a FMResultSet.
```
- (int)columnIndexForName:(NSString*)columnName {
    columnName = [columnName lowercaseString];
```
While looping through a large result set and reading values, repeatedly calling lowercaseString on a column name eats into cpu cycles.

Eliminating lowercaseString got me significant performance gains.

Was this added to maintain SQLite's case insensitivity?

Reading the column by index instead of name doesn't have this performance cost. But, that pattern can easily introduce bugs if the programmer changes the sql statement without updating the column indexes.

**Comment by ccgus** [comment]
It's necessary for backwards compatibility.

Going by the index is the way to go if you want speed.
