### ISSUE TITLE
Same code , same Sqlite Database,  get different data, why?

### ISSUE THREAD

**Issue by John0079** [ccgus/fmdb#511]
same codes , same database, everything is same ,when it run on simulator , everything is ok, but when it run on a real iPhone machine, ## it get a set different data, why?
it is my code, can you tell me why?

```objc
- (void)load
{
	FMDatabase *db = [self.mDb getDatabase];
    FMResultSet *cursor = nil;

	if ([db open]) {
        cursor = [db executeQuery:@"SELECT crt, mod, scm, dty, usn, ls, conf, models, 	decks, dconf, tags FROM col"];
        
        if (![cursor next]) {
            return;
        }
                        
        self.mCrt = [cursor longForColumnIndex:0];
        self.mMod = [cursor longForColumnIndex:1];
        self.mScm = [cursor longForColumnIndex:2];
        self.mDty = [cursor intForColumnIndex:3] == 1;
        self.mUsn = [cursor intForColumnIndex:4];
        self.mLs  = [cursor longForColumnIndex:5];
        
        
        
        [cursor close];
        [db close];
    } 
}
```

in simulator : 

> "self.mCrt" = 1422129600;

in real iPhone machine :

> "self.mCrt" = -1389215;

why?

**Comment by robertmryan** [comment]
Usually I'd suspect that `NSInteger` is `long` in some platforms, and merely `int` in others (though I'm having a hard time reconciling that with the values you shared with us). Perhaps you can share you definition of `mCrt`. Is it a `NSInteger`?

**Comment by John0079** [comment]
yes ,you are right, i changed the mCrt type, and use longLongIntForColumnIndex every is ok, thank you very mach!
follow is my new code;
`- (void)load
{
    FMDatabase *db = [self.mDb getDatabase];
    FMResultSet *cursor = nil;

    if ([db open]) {
        cursor = [db executeQuery:@"SELECT crt, mod, scm, dty, usn, ls, conf, models,   decks, dconf, tags FROM col"];

        if (![cursor next]) {
            return;
        }

        int mCrt = [cursor intForColumnIndex:0];
        _long long mMod = [cursor longLongIntForColumnIndex:1];
        long long mScm = [cursor longLongIntForColumnIndex:2];_
        int mDty = [cursor intForColumnIndex:3];

        int mUsn = [cursor intForColumnIndex:4];
        int mLs  = [cursor intForColumnIndex:5];

        
        [cursor close];
        [db close];
    } 
}`

thank you @robertmryan
