### ISSUE TITLE
FMDatabaseQueue inDatabase called reentrantly when using NSNotifications

### ISSUE THREAD

**Issue by pheedsta** [ccgus/fmdb#528]
I am using FMDatabaseQueue on an application that does a lot of background database work (i.e. downloading record updates from a server etc) whilst allowing users to update the same database from the main queue. I create one FMDatabaseQueue singleton when the application loads so all database queries and updates are done through the one queue (as per the documentation this seems to be the recommended way to access the same database from multiple threads).

One of my functions posts a Notification (via NotificationCenter) _**from within**_ an FMDatabaseQueue.inTransaction call when a record is inserted / updated. Other classes (i.e. UIViewControllers) on the main thread listen for these notifications and refresh their data when they are received. To refresh, many of them call FMDatabaseQueue.inDatabase which is returning "inDatabase: was called reentrantly on the same queue, which would lead to a deadlock". In an attempt to fix this problem, I post the notification within a DispatchQueue.main.async {} block (Swift 3.0). This fixes the issue in some instances but not all.

How can I query the database via FMDatabaseQueue when a notification that has been posted from within FMDatabaseQueue.inTransaction is received? Or is there another method that would produce the same results?

**Comment by ccgus** [comment]
You'll have to provide a way to make sure reentrant calls aren't made. FMDB doesn't have a way to do this for you.
