### ISSUE TITLE
How to skip a column in insert query?

### ISSUE THREAD

**Issue by hemangshah** [ccgus/fmdb#530]
I have total 4 columns in table X. 1 of the column is primary key + auto increment, rest 3 are of TEXT type.

**This is my code & query**:

```
FMDatabase *db = [FMDatabase databaseWithPath:[self dbPath]];
[db open];
[db executeUpdate:@"INSERT INTO X VALUES (?, ?, ?)", value1, value2, value3];
[db close];
```

**But it's giving me an error after executing the query**:

> Error: table X has 4 columns but 3 values were supplied.

**How can I skip the primary key column as it's auto incremented?**

**I tried this too:**

```
FMDatabase *db = [FMDatabase databaseWithPath:[self dbPath]];
[db open];
[db executeUpdate:@"INSERT INTO X VALUES (?, ?, ?, ?)", NULL, value1, value2, value3];
[db close];
```

> But it leads to an exception in FMDB classes.

**Comment by robertmryan** [comment]
You can supply column names:

```objc
[db executeUpdate:@"INSERT INTO X (FOO, BAR, BAZ) VALUES (?, ?, ?)", value1, value2, value3];
```

Or use `NSNull`:

```objc
[db executeUpdate:@"INSERT INTO X (FOO, BAR, BAZ) VALUES (?, ?, ?, ?)", [NSNull null], value1, value2, value3];
```

I prefer the former syntax, as it is less fragile (it is not dependent upon the order that the columns are in the physical table, you can add columns to a table and it still works, etc.), but that's up to you.

**Comment by hemangshah** [comment]
@robertmryan, (lately but), thank you so much, it helped me during that period of time!
