### ISSUE TITLE
Error with FMResultSet

### ISSUE THREAD

**Issue by martinobonfiglioli** [ccgus/fmdb#532]
I got an error and I can't figure out a solution, this is my stack trace:

> 
Crashed: fmdb.<FMDatabaseQueue: 0x13e87c040>
EXC_BAD_ACCESS KERN_INVALID_ADDRESS
0  libsqlite3.dylib               0x1827f626c (null) + 60292
1  libsqlite3.dylib               0x1827f61fc (null) + 60180
2  libsqlite3.dylib               0x1827fe7b0 (null) + 11132
3  libsqlite3.dylib               0x182840000 (null) + 55920
4  libsqlite3.dylib               0x1827e9d8c (null) + 9892
5  libsqlite3.dylib               0x1827e78e0 sqlite3_step + 504
6  MusixmatchCore                 0x100bff9c0 -[FMResultSet nextWithError:] + 72
7  MusixmatchCore                 0x100bff968 -[FMResultSet next] + 48
8  MusixmatchCore                 0x100b7320c __49-[DataStore readSubtitlesFromDataStoreWithTrack:]_block_invoke + 260
9  MusixmatchCore                 0x100bfe0f8 __30-[FMDatabaseQueue inDatabase:]_block_invoke + 88
10 libdispatch.dylib              0x181d3147c _dispatch_client_callout + 16
11 libdispatch.dylib              0x181d3c480 _dispatch_barrier_sync_f_slow + 824
12 MusixmatchCore                 0x100bfe044 -[FMDatabaseQueue inDatabase:] + 312
13 MusixmatchCore                 0x100b5f45c -[DataStore inDatabaseSafe:] + 188
14 MusixmatchCore                 0x100b7304c -[DataStore readSubtitlesFromDataStoreWithTrack:] + 488
15 Musixmatch                     0x1002d0224 -[MXMLyricsManageController updateViewWithTrack:usingCache:] (MXMLyricsManageController.m:80)
16 Musixmatch                     0x10023c9ec __68-[MXMLyricsPortraitViewController matchTrackOrUpdateViewUsingCache:]_block_invoke_3 (MXMLyricsPortraitViewController.m:694)
17 libdispatch.dylib              0x181d314bc _dispatch_call_block_and_release + 24
18 libdispatch.dylib              0x181d3147c _dispatch_client_callout + 16
19 libdispatch.dylib              0x181d3f914 _dispatch_root_queue_drain + 2140
20 libdispatch.dylib              0x181d3f0b0 _dispatch_worker_thread3 + 112
21 libsystem_pthread.dylib        0x181f49470 _pthread_wqthread + 1092
22 libsystem_pthread.dylib        0x181f49020 start_wqthread + 4

Thanks in advance.

**Comment by ccgus** [comment]
Show all the backtraces please.

**Comment by martinobonfiglioli** [comment]
That's all I have to from Crashlytics:

http://crashes.to/s/bef425131e8

**Comment by ccgus** [comment]
That page has a way to show all the threads.

At any rate, thread 5 and thread 8 are both in sqlite routines. Thread 8 is not using the queue, and I'm going to guess that it's also using the same database handle as the one in the queue. That breaks the api contract, and you'll need to rework your code not to do that.
