### ISSUE TITLE
How to suppress the log output from fmdb library?

### ISSUE THREAD

**Issue by xingheng** [ccgus/fmdb#542]
Team, we've integrated this library a long time, could you please provide some solutions to disable the verbose log output from it?

Great thanks for your hard job!

**Comment by robertmryan** [comment]
You can silence some of them by turning off `logsErrors`.

@ccgus - I'm inclined to make all `NSLog` statements honor that setting. Any objection to that? Personally, I'd also be defaulting this to `false` on "release" builds, but IIRC, you weren't crazy about that idea.

**Comment by xingheng** [comment]
Close it as there is an existing PR for it.
