### ISSUE TITLE
fmdb更新二进制图片数据不能转化成图片

### ISSUE THREAD

**Issue by hanjunqiang** [ccgus/fmdb#555]
请教一个问题：fmdb更新二进制图片数据，然后获取数据转化成图片，但是图片不显示。
采用插入二进制图片数据方法可以转成图片。有什么解决方式？

**Comment by godL** [comment]
哥们  这是老外写的   你提issus  能不能用英文   你用中文   直接把老外整懵了

**Comment by mayongl** [comment]
Just translate what was asked in the first post.

Title: fmdb, image data in binary can't be transfer to image
Content:
Get a question: update image data in binary with FMDB, then get the data and transfer it to image. Somehow, the image can't be displayed. But it works with insert image data in binary. Any idea?

**Comment by ccgus** [comment]
FMDB can store image data just fine (Acorn does it many many times a day). So the problem probably resides elsewhere.
