### ISSUE TITLE
can I keep FMResultSet instanse and fetch result paging

### ISSUE THREAD

**Issue by aozhimin** [ccgus/fmdb#559]

**Comment by ccgus** [comment]
Can you explain a bit more?

**Comment by aozhimin** [comment]
@ccgus ，for example, I don't want to fetch all of results from database, howerver, I want to return a FMResultSet in my method, and interate it to paging access resultes

**Comment by aozhimin** [comment]
@ccgus ，for example, I don't want to fetch all of results from database, howerver, I want to return a FMResultSet in my method, and interate it to paging access results

**Comment by ccgus** [comment]
I'm not sure, I've not tried. You might check and see if sqlite can do this with their result set, which FMDB wraps. You'll find your answer in there most likely.

**Comment by aozhimin** [comment]
@ccgus , Thank you~
