### ISSUE TITLE
Why I Need to close db after updating or querying when use FMDataBase instance directly?

### ISSUE THREAD

**Issue by SatanWoo** [ccgus/fmdb#572]
According to #514, You mentioned that we don't have to call `[db close]` when using FMDatabaseQueue to execute update or query operation. However, (https://github.com/ccgus/fmdb#closing), you say we should close db after updating or querying.

After I reading the source code about FMDatabaseQueue, I didn't notice the difference between accessing FMDataBase by FMDatabaseQueue and accessing database manually.

Can someone help me on this topic. I'm really confused about this.

**Comment by ccgus** [comment]
If you never want to make a query during the rest of the time your app is running, then you should close it. If you plan on doing a query again at some point, keep it open. It's just basic resource management. Does that help?

**Comment by SatanWoo** [comment]
@ccgus I got it! Thanks for your answer~

**Comment by robertmryan** [comment]
Just to clarify, if you're using a queue, you don't have to close the database. If you're really entirely done with your queue, just remove your reference to that queue and the database will be closed for you when the queue is deallocated. It seems that manually closing the database and keeping the queue instance around only invites failure to recover all of the memory or, worse, accidentally using the queue again after the database was closed. No?
