### ISSUE TITLE
cocoapod

### ISSUE THREAD

**Issue by krudos** [ccgus/fmdb#588]
please update pod
i am getting FMDB (2.6.2) and i want 2.7 with
 pod 'FMDB'

**Comment by AlexPotemka** [comment]
I'm getting 2.6.2 too...
update pod pls

**Comment by ccgus** [comment]
I'm guessing it's because the tag wasn't live on GitHub. Try again- and if that doesn't work we're accepting patches.

**Comment by krudos** [comment]
i just run pod update and still getting 2.6.2
maybe have to wait or you have to put a tag for cocoapod or do something in the cocoapod webpage

**Comment by crisp** [comment]
Still not able to update to 2.7.1 nor 2.7 via pod update

**Comment by crisp** [comment]
Note: I'm using the FMDB/SQLCipher sub-spec

**Comment by robertmryan** [comment]
You should now get 2.7.2.

**Comment by crisp** [comment]
Oh super! Will validate on Monday and post results here.

Thank you

**Comment by crisp** [comment]
Seems to work. Thanks again!
