### ISSUE TITLE
Current release (2.7.1) of sub-spec FMDB/SQLCipher not available via Cocoapods

### ISSUE THREAD

**Issue by crisp** [ccgus/fmdb#592]
I get these messages when attempting a pod update FMDB/SQLCipher command:
```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `FMDB/SQLCipher (= 2.7.1)` required by `Podfile`
- `FMDB/SQLCipher (= 2.7.1)` required by `Podfile`
- `FMDB/SQLCipher (= 2.7.1)` required by `Podfile`
- `FMDB/SQLCipher (= 2.7.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `FMDB/SQLCipher (= 2.7.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

Note: 2.7.2 *does* work

**Comment by crisp** [comment]
Any updates on this?

**Comment by ccgus** [comment]
If 2.7.2 works, why not use that? I don't use SQLCipher or CocoPods, so I'm not much help there, sorry.

**Comment by crisp** [comment]
I would be happy to use 2.7.2 once it is an official release, but it's presently not listed as such. Do we have a timeline on that?

**Comment by robertmryan** [comment]
Did you do the `pod repo update` command that the error message advised?

**Comment by robertmryan** [comment]
FYI, I just tried SQLCipher and it worked fine:

```
Robs-MacBook-Pro:MyApp rryan$ pod repo update
Updating spec repo `master`
  $ /usr/bin/git -C /Users/rryan/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 8752, done.        
  remote: Compressing objects: 100% (189/189), done.        
  remote: Total 8752 (delta 3842), reused 3993 (delta 3816), pack-reused 4721        
  Receiving objects: 100% (8752/8752), 872.85 KiB | 0 bytes/s, done.
  Resolving deltas: 100% (5933/5933), completed with 1339 local objects.
  From https://github.com/CocoaPods/Specs
     4ddf6ad299c..52516dd9406  master     -> origin/master
  $ /usr/bin/git -C /Users/rryan/.cocoapods/repos/master rev-parse --abbrev-ref
  HEAD
  master
  $ /usr/bin/git -C /Users/rryan/.cocoapods/repos/master reset --hard
  origin/master
  HEAD is now at 52516dd9406 [Delete] Crisp 1.0.12

CocoaPods 1.3.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.3.0.beta.2
```

And then:

```
Robs-MacBook-Pro:MyApp rryan$ pod init
```

I then edited my `Podfile`, adding the `pod 'FMDB/SQLCipher'`:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  pod 'FMDB/SQLCipher'
end
```

And then I installed:

```
Robs-MacBook-Pro:MyApp rryan$ pod install
Analyzing dependencies
Downloading dependencies
Installing FMDB (2.7.2)
Installing SQLCipher (3.4.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `MyApp.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

[!] Automatically assigning platform osx with version 10.12 on target MyApp because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

I then opened my `MyApp.xcworkspace` and while the compiling of generated a ton of annoying warning messages, SQLCipher itself seemed to work fine. E.g. 

```swift
import Cocoa
import FMDB

let key = "x'2DD29CA851E7B56E4697B0E1F08507293D761A05CE4D1B628663F411A8086D99'";

class ViewController: NSViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let fileURL = try! FileManager.default
            .url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
            .appendingPathComponent("test.sqlite")
        
        let database = FMDatabase(url: fileURL)
        
        guard database.open() else {
            print("Unable to open database")
            return
        }
        
        database.setKey(key)
        
        do {
            try database.executeUpdate("create table test(x text, y text, z text)", values: nil)
            try database.executeUpdate("insert into test (x, y, z) values (?, ?, ?)", values: ["a", "b", "c"])
            try database.executeUpdate("insert into test (x, y, z) values (?, ?, ?)", values: ["e", "f", "g"])
            
            let rs = try database.executeQuery("select x, y, z from test", values: nil)
            while rs.next() {
                if let x = rs.string(forColumn: "x"), let y = rs.string(forColumn: "y"), let z = rs.string(forColumn: "z") {
                    print("x = \(x); y = \(y); z = \(z)")
                }
            }
        } catch {
            print("failed: \(error.localizedDescription)")
        }
        
        database.close()
    }

}
```

generated the following output:

```
x = a; y = b; z = c
x = e; y = f; z = g
```

And when I looked at the `test.sqlite` file, it seemed to be encrypted:

<img width="1179" alt="screenshot 2017-06-26 11 47 26" src="https://user-images.githubusercontent.com/1530768/27555031-422fe492-5a65-11e7-8977-b209a11d8f83.png">

**Comment by crisp** [comment]
Yes, I ran the pod repo update command. It runs successfully and applies updates. Even ran it again to be sure.

However, I still get the same errors noted above when I set the version for FMDB/SQLCipher to 2.7.1 (the *"Latest Release"* according to the releases page).

<img width="1112" alt="screen shot 2017-06-26 at 3 14 50 pm" src="https://user-images.githubusercontent.com/113344/27556100-41d0eac4-5a82-11e7-8a76-96289df7f584.png">

It *does* work if I set the version to 2.7.2.

**Comment by crisp** [comment]
Also, I get the same errors if I set the versions to 2.7. (I'm presently running on 2.6.2)

**Comment by crisp** [comment]
E.g.

Works:
```
target 'MyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  pod 'FMDB/SQLCipher', '2.7.2'
end
```

Does NOT work:
```
target 'MyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  pod 'FMDB/SQLCipher', '2.7.1'
end
```

Also does NOT work:
```
target 'MyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  pod 'FMDB/SQLCipher', '2.7'
end
```

**Comment by robertmryan** [comment]
I've updated 2.7.2 to mark it as the official release it really was. I had created 2.7.2 tag, updated CocoaPods spec, pushed spec to Cocoapods Trunk, etc., but neglected to mark it as a release. My bad.

**Comment by crisp** [comment]
That will work. Thank you

**Comment by GreatkaiOSama** [comment]
> FYI, I just tried SQLCipher and it worked fine:
> 
> ```
> $ pod repo update
> Updating spec repo `master`
>   $ /usr/bin/git -C /Users/rryan/.cocoapods/repos/master fetch origin --progress
>   remote: Counting objects: 8752, done.        
>   remote: Compressing objects: 100% (189/189), done.        
>   remote: Total 8752 (delta 3842), reused 3993 (delta 3816), pack-reused 4721        
>   Receiving objects: 100% (8752/8752), 872.85 KiB | 0 bytes/s, done.
>   Resolving deltas: 100% (5933/5933), completed with 1339 local objects.
>   From https://github.com/CocoaPods/Specs
>      4ddf6ad299c..52516dd9406  master     -> origin/master
>   $ /usr/bin/git -C /Users/rryan/.cocoapods/repos/master rev-parse --abbrev-ref
>   HEAD
>   master
>   $ /usr/bin/git -C /Users/rryan/.cocoapods/repos/master reset --hard
>   origin/master
>   HEAD is now at 52516dd9406 [Delete] Crisp 1.0.12
> 
> CocoaPods 1.3.0.beta.2 is available.
> To update use: `sudo gem install cocoapods --pre`
> [!] This is a test version we'd love you to try.
> 
> For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.3.0.beta.2
> ```
> And then:
> 
> ```
> $ pod init
> ```
> I then edited my `Podfile`, adding the `pod 'FMDB/SQLCipher'`:
> 
> ```
> # Uncomment the next line to define a global platform for your project
> # platform :ios, '9.0'
> 
> target 'MyApp' do
>   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
>   use_frameworks!
> 
>   # Pods for MyApp
>   pod 'FMDB/SQLCipher'
> end
> ```
> And then I installed:
> 
> ```
> $ pod install
> Analyzing dependencies
> Downloading dependencies
> Installing FMDB (2.7.2)
> Installing SQLCipher (3.4.1)
> Generating Pods project
> Integrating client project
> 
> [!] Please close any current Xcode sessions and use `MyApp.xcworkspace` for this project from now on.
> Sending stats
> Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
> 
> [!] Automatically assigning platform osx with version 10.12 on target MyApp because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> ```
> I then opened my `MyApp.xcworkspace` and while the compiling of SQLCipher generated a ton of annoying warning messages (I'm not sure we can do anything about that; it's not our code), SQLCipher itself seemed to work fine. E.g.
> 
> ```swift
> import Cocoa
> import FMDB
> 
> private let key = "x'2DD29CA851E7B56E4697B0E1F08507293D761A05CE4D1B628663F411A8086D99'"
> 
> class ViewController: NSViewController {
> 
>     override func viewDidLoad() {
>         super.viewDidLoad()
> 
>         let fileURL = try! FileManager.default
>             .url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
>             .appendingPathComponent("test.sqlite")
>         
>         let database = FMDatabase(url: fileURL)
>         
>         guard database.open() else {
>             print("Unable to open database")
>             return
>         }
>         
>         database.setKey(key)
>         
>         do {
>             try database.executeUpdate("create table test(x text, y text, z text)", values: nil)
>             try database.executeUpdate("insert into test (x, y, z) values (?, ?, ?)", values: ["a", "b", "c"])
>             try database.executeUpdate("insert into test (x, y, z) values (?, ?, ?)", values: ["e", "f", "g"])
>             
>             let rs = try database.executeQuery("select x, y, z from test", values: nil)
>             while rs.next() {
>                 if let x = rs.string(forColumn: "x"), let y = rs.string(forColumn: "y"), let z = rs.string(forColumn: "z") {
>                     print("x = \(x); y = \(y); z = \(z)")
>                 }
>             }
>         } catch {
>             print("failed: \(error.localizedDescription)")
>         }
>         
>         database.close()
>     }
> 
> }
> ```
> 
> generated the following output:
> 
> ```
> x = a; y = b; z = c
> x = e; y = f; z = g
> ```
> And when I looked at the `test.sqlite` file, it was appropriately encrypted:
> 
> <img alt="screenshot 2017-06-26 11 47 26" width="1179" src="https://user-images.githubusercontent.com/1530768/27555031-422fe492-5a65-11e7-8977-b209a11d8f83.png">

to use sqlcipher sub-spec FMDB/SQLCipher is necesary pay license? or it is free because is subspec of FMDB?

**Comment by GreatkaiOSama** [comment]
and type encryption method use internally fmdb using sqlcipher subspecs?
