### ISSUE TITLE
If FMDatabaseQueue is a property of singleton,When should i close FMDatabaseQueue？

### ISSUE THREAD

**Issue by Fuhanyu** [ccgus/fmdb#604]
I create a singleton instance.

    + (instancetype)shareManager {
    static dispatch_once_t token;
    static DatabaseManager *manager;
    dispatch_once(&token, ^{
        manager = [[self alloc] init];
    });
    return manager;
    }

    - (instancetype)init {
    self = [super init];
    if (self) {
        _queue = [FMDatabaseQueue databaseQueueWithPath:databasePath];
    }
    return self;
    }

i use it like this 

    - (void)queryTrackWithTrackID:(NSString *)trackID result:(void (^)(Track *_Nullable track))result {
    [self.queue inDatabase:^(FMDatabase *db) {
        //sql code
    }];
    }

But When should i close FMDatabaseQueue？

**Comment by ccgus** [comment]
You should close it if you change your schema at all (ie- create or alter tables). Otherwise, why would you want to close it?

**Comment by Fuhanyu** [comment]
Thanks, I'm not good at database , the simple code show me that '[db open]' and '[db close]' . I understand that db should close after operation. Is that doesn’t matter if i don’t close it?

**Comment by ccgus** [comment]
Don't close it after operations. I'd keep it open until your app goes to the background at least.

**Comment by Fuhanyu** [comment]
OK Thank you!
