### ISSUE TITLE
when i execute delete update, i got success result. But the row still exist？

### ISSUE THREAD

**Issue by Fuhanyu** [ccgus/fmdb#605]
I user db to excute a sql string like this
    
    NSString *delsql = [NSString stringWithFormat:@"DELETE FROM local_album WHERE id = '%@'", @"123456"];
    BOOL delsuccess = [db executeUpdate:delsql];
    NSLog(@"---delete %d", delsuccess);、

I got true.
But the row still exist.
When i change『 WHERE id = '%@' -> WHERE id = %@ 』, it works.

**Comment by ccgus** [comment]
Try:
```
[db executeUpdate:@"DELETE FROM local_album WHERE id = ?, @(1234)];
```

**Comment by stoneForRock** [comment]
if the id = 1234 row is not exist in table,you got true

**Comment by robertmryan** [comment]
1. Never use `stringWithFormat` to insert values into your SQL. Always use the syntax shown by ccgus, above, with

   - `?` placeholder in the SQL;
   - No `'` around the `?` in the SQL;
   - Pass either a `NSNumber` or `NSString` parameter after the SQL, depending upon whether you're really dealing with numbers or strings.

2. The question is whether it is a number or a string. If the ID is really a number, as suggested by the behavior shown in your original question, then use the syntax suggested by Gus:

   ```objc
   NSInteger recordID = 123456;
   BOOL delsuccess = [db executeUpdate:@"DELETE FROM local_album WHERE id = ?", @(recordID)];
   ```

   If it were a string (which does not appear to be the case in your example), you'd do:

   ```objc
   NSString recordID = @"123456";
   BOOL delsuccess = [db executeUpdate:@"DELETE FROM local_album WHERE id = ?", recordID];
   ```

3. You seem to be confused about the return value of `executeUpdate` in conjunction with a `DELETE` statement. The return value of `executeUpdate` only checks if there was an actual _error_ preparing/performing the SQL. It doesn't tell you if there simply were no records matching your `WHERE` clause.

   If you want to see how many rows were actually deleted, use [`changes`](http://ccgus.github.io/fmdb/html/Classes/FMDatabase.html#//api/name/changes).

   ```
   NSInteger recordID = 123456;
   BOOL delsuccess = [db executeUpdate:@"DELETE FROM local_album WHERE id = ?", @(recordID)];
   if (delsuccess) {
        NSLog(@"%d rows deleted", db.changes);
   } else {
        NSLog(@"delete failed %@", [db lastErrorMessage]);
   }
   ```
