### ISSUE TITLE
Support for watchOS/ tvOS

### ISSUE THREAD

**Issue by billypchan** [ccgus/fmdb#614]
Hi all,
Thanks for the great work! I have a question about FMDB support on watchOS and tvOS. I am now trying to build FMDM manually. Is there any method to install FMDB with cocoapod/ carthage?

**Comment by ccgus** [comment]
Yes, but I don't personally use it:

https://www.google.com/search?client=safari&rls=en&q=fmdb+cocoapods&ie=UTF-8&oe=UTF-8

https://cocoapods.org/pods/FMDB

**Comment by billypchan** [comment]
Hi ccgus,
Thanks for reply. I open this issue because carthage does not generate framework for watchOS. I will try to switch to cocoapod.
