### ISSUE TITLE
How to dismiss all SQLCiper warning issues? 

### ISSUE THREAD

**Issue by andrewlim7** [ccgus/fmdb#617]
May I know how can I dismiss this issue (please refer to picture) and is that okay that I solve the FMDB missing file problem via this https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27 and release to public ?
![screen shot 2017-10-13 at 10 18 06 am](https://user-images.githubusercontent.com/28426449/31527444-e486eaac-afff-11e7-9cd1-d9560f87eb84.png)

**Comment by ccgus** [comment]
Sorry, we don't support SQLCipher (I've never used it myself).
