### ISSUE TITLE
Should beginTransaction be exclusive?

### ISSUE THREAD

**Issue by robertmryan** [ccgus/fmdb#619]
I was working on some test cases for FMDB and noticed that `-[FMDatabase beginTransaction]` and <br />`-[FMDatabaseQueue inTransaction]` both do `EXCLUSIVE` transactions. Given that we want this to be a thin wrapper around SQLite, I don't think this is quite right. The [SQLite documentation](http://sqlite.org/lang_transaction.html) for `BEGIN TRANSACTION` tells us (emphasis added):

> Transactions can be deferred, immediate, or exclusive. The default transaction behavior is _deferred._

I'd suggest:

1. Change the behavior of `beginTransaction` and `inTransaction` to both perform `DEFERRED` transactions, just like `BEGIN TRANSACTION` does; and 

2. Add a new `beginExclusiveTransactions` and `inExclusiveTransaction` (analogous to the existing `beginDeferredTransaction` and `inDeferredTransaction`, but doing exclusive rather than deferred transactions) to offer the `BEGIN EXCLUSIVE TRANSACTION` behavior for those who need it.

I've got a pull request ready to go, but wanted to see if anyone had any objections before I did that. Technically, it changes the behavior of FMDB, but it seems more correct (and it's an edge case, anyway, because most multithreaded contention environments use `FMDatabaseQueue`, which largely obviates the need for the distinctions between the various transaction types).

**Comment by benasher44** [comment]
This makes sense to me! Given the change in behavior, it might be nice to call this out in readme or somewhere else prominent, if the idea is to not do a major version release.

**Comment by robertmryan** [comment]
Good point. If we decide to punt, I might just add the exclusive renditions for now (so people can explicitly adopt the exclusive behavior if they want) and add a warning to the `beginTransaction` and `inTransaction` to note that unlike SQLite’s `BEGIN TRANSACTION`, they do exclusive transactions, subject to change to the more intuitive deferred transactions in the next major release.

**Comment by benasher44** [comment]
Sounds reasonable!

**Comment by ccgus** [comment]
Sorry for the late reply (as usual, I'm a bit slow).

Punt! I think we should add the exclusive renditions, and then a warning to the beginTransaction. That way we don't break any code and the developer will get a nice little warning to know that things are going to change some day.

> "and it's an edge case, anyway, because most multithreaded contention environments use FMDatabaseQueue, which largely obviates the need for the distinctions between the various transaction types)."

I used transactions all the time in the past, not because of any multithreaded needs, but because it was made for faster code. If I was doing a bunch of updates or inserts, transactions were a great way to drastically speed that up.

**Comment by robertmryan** [comment]
Will do.

BTW, the edge case I was mentioning was not the use of transactions (which I use all the time, too), but rather the need for immediate rather than deferred transactions, a distinction which is less a performance concern than a question of how you want to deal with file lock contention issues, AFAIK.

**Comment by ccgus** [comment]
ahhhh, gotcha. 👍
