### ISSUE TITLE
columnNameToIndexMap property problem

### ISSUE THREAD

**Issue by miku1958** [ccgus/fmdb#627]
I found that FMResultSet.columnNameToIndexMap use lowercaseString to remane column, It cause many mistake when I get the dataDic from database and turn it to dataModel ,could you make a switch to turn it off or remove this?

**Comment by ccgus** [comment]
We're not going to remove it, as it would break apps.

You can create your own version of this method, using a different name and without lowercasing the string, in a category or a utility file of some sort.
