### ISSUE TITLE
Support for sqlite4

### ISSUE THREAD

**Issue by mprimeaux** [ccgus/fmdb#633]
Hi,

Are there any current plans to support sqlite4?

**Comment by ccgus** [comment]
As far as I can remember, sqlite4 was abandoned and features from it were brought back to v3.

So there are no plans to support it. I'm curious what you're after though…

**Comment by mprimeaux** [comment]
Thanks much. I didn't realize sqlite4 was abandoned.

**Comment by ccgus** [comment]
No worries. Here's a link that might shed more info: https://sqlite.org/src4/info/c0b7f14c0976ed5e

**Comment by mprimeaux** [comment]
Cheers, mate. I sincerely appreciate the context and help.
