### ISSUE TITLE
[FMDatabase getTableSchema:]: unrecognized selector

### ISSUE THREAD

**Issue by tan2547** [ccgus/fmdb#634]
0   CoreFoundation                      0x000000010a46f1ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000109b04f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a4efa34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010a3f20a8 ___forwarding___ + 1432
	4   CoreFoundation                      0x000000010a3f1a88 _CF_forwarding_prep_0 + 120
	5   vdsdf                               0x00000001091ce483 __24+[JKDBModel createTable]_block_invoke + 435
	6   vdsdf                               0x00000001091d6ef1 __46-[FMDatabaseQueue beginTransaction:withBlock:]_block_invoke + 257
	7   libdispatch.dylib                   0x000000010df2c43c _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010df33338 _dispatch_queue_barrier_sync_invoke_and_complete + 392
	9   vdsdf                               0x00000001091d6daf -[FMDatabaseQueue beginTransaction:withBlock:] + 191
	10  vdsdf                               0x00000001091d7100 -[FMDatabaseQueue inTransaction:] + 64
	11  vdsdf                               0x00000001091ce24e +[JKDBModel createTable] + 238
	12  vdsdf                               0x00000001091cd303 +[JKDBModel initialize] + 99
	13  libobjc.A.dylib                     0x0000000109b05a14 CALLING_SOME_+initialize_METHOD + 19
	14  libobjc.A.dylib                     0x0000000109b05dae _class_initialize + 276
	15  libobjc.A.dylib                     0x0000000109b0c5e7 lookUpImpOrForward + 225
	16  libobjc.A.dylib                     0x0000000109b1c3d4 _objc_msgSend_uncached + 68
	17  vdsdf                               0x00000001091c3b2b -[AHUBEventModel addEventInfo:] + 75
	18  vdsdf                               0x00000001091c329c +[AHUBEventAgent addEventInfo:] + 92
	19  vdsdf                               0x00000001091c2e5b -[UIViewController(hockLife) ahuserBehavior_viewDidAppear:] + 315
	20  UIKit                               0x000000010aacce12 -[UINavigationController viewDidAppear:] + 85
	21  UIKit                               0x000000010aa9569b -[UIViewController _setViewAppearState:isAnimating:] + 699
	22  UIKit                               0x000000010aaf480e -[UITabBarController viewDidAppear:] + 115
	23  UIKit                               0x000000010aa9569b -[UIViewController _setViewAppearState:isAnimating:] + 699
	24  UIKit                               0x000000010aa98545 __64-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]_block_invoke + 42
	25  UIKit                               0x000000010aa96839 -[UIViewController _executeAfterAppearanceBlock] + 86
	26  UIKit                               0x000000010a8f6761 _runAfterCACommitDeferredBlocks + 634
	27  UIKit                               0x000000010a8e4bc5 _cleanUpAfterCAFlushAndRunDeferredBlocks + 280
	28  UIKit                               0x000000010a905d48 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 155
	29  CoreFoundation                      0x000000010a41218c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	30  CoreFoundation                      0x000000010a3f696b __CFRunLoopDoBlocks + 203
	31  CoreFoundation                      0x000000010a3f6144 __CFRunLoopRun + 1300
	32  CoreFoundation                      0x000000010a3f59b9 CFRunLoopRunSpecific + 409
	33  GraphicsServices                    0x000000010f4449c6 GSEventRunModal + 62
	34  UIKit                               0x000000010a8ea5e8 UIApplicationMain + 159
	35  vdsdf                               0x00000001091c272f main + 111
	36  libdyld.dylib                       0x000000010dfa8d81 start + 1
	37  ???                                 0x0000000000000001 0x0 + 1

**Comment by tan2547** [comment]
when I use FMDB in my static framework ....

**Comment by ccgus** [comment]
getTableSchema is part of FMDatabaseAdditions.m. Make sure that's being compiled into your framework as well.
