### ISSUE TITLE
FMDatabase open error

### ISSUE THREAD

**Issue by Eafy** [ccgus/fmdb#635]
Hi, I use the 2.7.4 version to print Log: "API call with NULL database connection pointer". I call sequential FMDatabaseQueue -open:, then -close:, and then I can't open database any more. I found that "isOpen" did not set NO in the interface "close", which Open returning to YES again.

**Comment by Eafy** [comment]
[希伯来文.txt](https://github.com/ccgus/fmdb/files/1566896/default.txt)

**Comment by Eafy** [comment]
[Test.txt](https://github.com/ccgus/fmdb/files/1566898/Test.txt)

**Comment by robertmryan** [comment]
With `FMDatabaseQueue`, you don't have to open the database. It's opened for you automatically:

```objc
FMDatabaseQueue *queue = [[FMDatabaseQueue alloc] initWithURL:url];

[queue inDatabase:^(FMDatabase * _Nonnull db) {
    // you don't have to open the database; it's opened for you automatically
    
    [db executeUpdate:@"CREATE TABLE foo (bar TEXT)"];
    [db executeUpdate:@"INSERT INTO foo (bar) VALUES (?)", @"baz"];
    
    // You don't want to close the database this way because `FMDatabaseQueue` maintains its 
    // own database pointer; if you close this, the `FMDatabaseQueue` still has its own dangling
    // pointer to the database you closed, but it has no way of knowing that you closed it
    // unbeknownst to the queue.
    //
    // [db close];
}];

// If you _really_ wanted to close the database, you need to tell the queue to close the database
// it's keeping track of for you. But you generally wouldn't even do this. But if you close the queue's
// database, as shown below, it will now know it's closed and will reopen it when needed.

[queue close];

// Because we told the queue to close the database, it will automatically reopen it again if you
// closed it via `[[queue close]`, above.

[queue inDatabase:^(FMDatabase * _Nonnull db) {
    // this will work fine, having automatically reopened the database for you

    FMResultSet *rs = [db executeQuery:@"SELECT * FROM foo"];
    while ([rs next]) {
        NSLog(@"%@", rs.resultDictionary);
    }
}];
```

Bottom line, certainly never opening the database yourself, because the queue opens it for you. You don't generally close the queue's database, either, but if you needed to, do it like shown above. Frankly, if you have some use case where you think you need to close the queue's database, let us know why, and we might be able to offer better counsel.

**Comment by Eafy** [comment]
Thank you very much. I'm going to modify my code.
