### ISSUE TITLE
How to save a NSValue to via fmdb ?

### ISSUE THREAD

**Issue by heistings** [ccgus/fmdb#643]
Has anyone met this issue? 

I saved a NSValue to db, but got a NSString when read.

**Comment by ccgus** [comment]
FMDB doesn't bind NSValues natively, and will treat it as text: https://github.com/ccgus/fmdb/blob/master/src/fmdb/FMDatabase.m#L600

You should probably handle the serialization and deserialization yourself for this case.

**Comment by heistings** [comment]
@ccgus Thanks for your reply, and I'm glad for being clear about this issue.

I solved my problem by converting the CGRect to NSString.
