### ISSUE TITLE
Suppress log noise for debug builds

### ISSUE THREAD

**Issue by cameroncooke** [ccgus/fmdb#646]
I'm finding that fmdb is kicking out a log for every query executed and while there is the flag `_traceExecution` it still prints out the queries to the log, see: https://github.com/ccgus/fmdb/blob/master/src/fmdb/FMDatabaseQueue.m#L203

Could we get more fine grained control on what and when logs out printed. It's completely polluting the console meaning that real issues and errors are being missed.

**Comment by ccgus** [comment]
I guess you figured this out already, but it's a warning that you're not closing your result sets.
