### ISSUE TITLE
BridgingHeader.h:17:9: error: 'FMDB/FMDB.h' file not found #import <FMDB/FMDB.h>

### ISSUE THREAD

**Issue by sunil-chayagol** [ccgus/fmdb#653]
above is the problem i am facing when i try to build. please anyone suggest a way. i installed the pod and updated the pod . still i am having this problem.

**Comment by FabienBourdon** [comment]
Sam problem, did you find any solution ?

**Comment by sunil-chayagol** [comment]
are you working on creating framework.
