### ISSUE TITLE
Chaining commands in FMDB.

### ISSUE THREAD

**Issue by chrisvoronin** [ccgus/fmdb#661]
Hi guys, is this the best way of doing this?

I've forked modified it locally, because I needed to find out when transaction completes so I can do whatever is needed in the app next after transaction (which may be another inTransaction) and calling it with dispatch.

This allowed me to onTransactionResult to que up next transaction.  I couldn't find a way to do this with existing code... but I might have missed something.

Can't highlight for some reason.
My changes are:
1) beginTransaction method has a new param called "resultBlock"
2) at the end after commit, this gets dispatched via main_que

Here is what I have so far.

```

- (void)beginTransaction:(FMDBTransaction)transaction withBlock:(void (^)(FMDatabase *db, BOOL *rollback))block **onResult:(void(^)(void))resultBlock** {
    
    FMDBRetain(self);
    dispatch_sync(_queue, ^() {
        
        BOOL shouldRollback = NO;
        
        switch (transaction) {
            case FMDBTransactionExclusive:
                [[self database] beginTransaction];
                break;
            case FMDBTransactionDeferred:
                [[self database] beginDeferredTransaction];
                break;
            case FMDBTransactionImmediate:
                [[self database] beginImmediateTransaction];
                break;
        }
        
        block([self database], &shouldRollback);
        
        if (shouldRollback) {
            [[self database] rollback];
        }
        else {
            [[self database] commit];
        }
        
        **// after commit.
        dispatch_async(dispatch_get_main_queue(), ^{
            if (resultBlock)
                resultBlock();
        });**
    });
    
    FMDBRelease(self);
    
}
```

**Comment by ccgus** [comment]
This seems like something you could easily build outside FMDB, without having to modify the source. The blocks that are passed in are called synchronous- so you could even just call your block inside the block that's passed in the withBlock: param.

Maybe that's where the confusion is coming from? FMDB isn't asynchronous, so you know it's done when the call to the queue is done.

**Comment by chrisvoronin** [comment]
Thanks ccgus.  This library is the best sqLite wrappers out there.

My case is that if I try to call my block inside the block  (and that block executes another "inTransaction" call, there is a crash.  Which is why I just pulled it and modified it locally.

que inTransaction: {....  
que.inTransaction {.... }  <-- crash here.
....}

dispatch_sync(_queue, ^() { <-- this crashes inside beginTransaction.
EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

Our app (inserts a few thousand rows upon certain action from the user... yeah I know)... and user can only proceed to next screen when that is all done.  Which is why I did that additional param for onComplete.  However, wasn't sure if that's the right approach.

**Comment by chrisvoronin** [comment]
Hi CCGus,

Here is what I'm running into if I don't do a call after.

`func getIds(onResult: ([String]) -> Void) {
        
        var results:[String] = []
        
        getQue().inTransaction { db, rollback in
            do {
                
                let sql = "select itemId from items"
                let rs = try db.executeQuery(sql, values: nil)
                while rs.next() {
                    if let workOrderID = rs.string(forColumn: "itemId") {
                        results.append(workOrderID)
                    }
                }
                
                onResult(results)
                
            } catch {
                print("error \(error.localizedDescription)")
            }
        }
    }`

however, because of how transaction block works, everything stays inside the transaction and crashes on any consequent calls.  What would you recommend here?

`SqLiteDAO().getIds { (results) in
            print(results) <-- prints results
            SqLiteDAO().getIds(onResult: { (newResults) in
                print("Inside now") <-- crashes before even getting here because it's in the transaction still.
            })
        }`

**Comment by chrisvoronin** [comment]
thank you
