### ISSUE TITLE
add four COLUMN

### ISSUE THREAD

**Issue by PhoenixLeeSin** [ccgus/fmdb#675]
i want add my sql four COLUMN ' etd' ' eta' ' delayStatus'  'delayReason'  . my code like this:

    func changeTable(){
        if fmdb!.open(){
            if !fmdb!.columnExists("etd", inTableWithName: "FlightPlanDataInfo"){
                let sql  = "ALTER TABLE \("FlightPlanDataInfo") ADD COLUMN etd varchar(256) eta varchar(256) delayStatus varchar(256) delayReason varchar(256) "
                do{
                    try fmdb!.executeUpdate(sql, values: nil)
                }catch{
                    print(fmdb!.lastErrorMessage())
                }
            }
        }
    }
but it shows:syntax error .please tell me how to fix it ?  thanks a lot~~~

**Comment by 350541732** [comment]
@R4N   thanks!!! i know how to do it ~~~thanks~~~
