### ISSUE TITLE
Xcode 10 Build Error

### ISSUE THREAD

**Issue by Zeropointer11** [ccgus/fmdb#679]
In Xcode 10 the project will not compile there are missing defination of the block defined in the header files.

All Blocks in FMDatabase, FMDatabaseQueue and FMDatabasePool has in the Header at the blocks the __attribute__((noescape)) 
that was required also in the *.m file implementation at Xcode 10

**Comment by ccgus** [comment]
It's fixed in trunk.

**Comment by Zeropointer11** [comment]
And when come the next Version with the fix?
