### ISSUE TITLE
Run reentrant block inline instead of dispatching it

### ISSUE THREAD

**Issue by frowing** [ccgus/fmdb#685]
Is there any reason why `inDatabase:` couldn't run the block in line if it's a reentrant one? It already knows that it's running on the right queue so why not just run it there?

**Comment by ccgus** [comment]
Are you talking about the check in FMDatabaseQueue's inDatabase:? Or something else?

**Comment by frowing** [comment]
@ccgus yep, that very check. I've been hitting it and I was wondering why the block isn't just run (not dispatched) since we're on the right queue.

**Comment by ccgus** [comment]
Because you're eventually *going to have a bad time*. It's there to protect from deadlocks, which happen all too easily otherwise. I suppose if you really think you know what's going on, you could comment it out- but I wouldn't recommend it and FMDB hasn't been tested in that scenario.

**Comment by frowing** [comment]
But the deadlock happens when you dispatch, right? You could just call the block right there. Something like:
```
FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
if (currentSyncQueue == self) {
    block();
}
```
I guess there is a reason why this is not done but I couldn't figure out why.

**Comment by ccgus** [comment]
I can't remember the specifics right now, but I believe there was a reason why not to do this. It's been a while since I worked on that section of code.

**Comment by frowing** [comment]
@ccgus yeah I supposed so, too. Thank you!
