### ISSUE TITLE
executeUpdate is returning a () type according to swift 4.1

### ISSUE THREAD

**Issue by donileo** [ccgus/fmdb#688]
I'm executing an update like the following using FMDB 1b09eca:

`let res = try! database.executeUpdate(SQLStmt.Currency.addBaseUSDCurrency, values: nil) `

Where I expect res to be a Bool. However according to Swift it’s a () type which is weird. Swift states:
`Constant 'res' inferred to have type '()', which may be unexpected`

If try to do `let res = try! database.executeUpdate(SQLStmt.Currency.addBaseUSDCurrency, values: nil)` to see if its an unwrapping issue the same issue persists.

Swift lets me compile but the type seems to be () instead of a bool. This is preventing me from checking if the executeUpdate command was successful.

**Comment by R4N** [comment]
@donileo 

Have a look at what the Objective-C `executeUpdate:values:error:` is mapped to in swift:
![executeupdate_swift](https://user-images.githubusercontent.com/12736867/43416014-207ee106-9405-11e8-9ca1-9a7481ca8ae7.png)

You can see an how this generally handled with the swift example code on the FMDB landing page


```
        do {
            try database.executeUpdate("create table test(x text, y text, z text)", values: nil)
            try database.executeUpdate("insert into test (x, y, z) values (?, ?, ?)", values: ["a", "b", "c"])
            try database.executeUpdate("insert into test (x, y, z) values (?, ?, ?)", values: ["e", "f", "g"])
            
            let rs = try database.executeQuery("select x, y, z from test", values: nil)
            while rs.next() {
                if let x = rs.string(forColumn: "x"), let y = rs.string(forColumn: "y"), let z = rs.string(forColumn: "z") {
                    print("x = \(x); y = \(y); z = \(z)")
                }
            }
        } catch {
            print("failed: \(error.localizedDescription)")
        }

```

There's a pretty good explanation in this [SO answer](https://stackoverflow.com/a/34787941)

specifically the example of:

`-(BOOL)doSomethingWithArgument2:(int) x error:(NSError **)error;`

mapping to this:

`public func doSomethingWithArgument2(x: Int32) throws`

**Comment by R4N** [comment]
@donileo

That is pretty much identical to the previous example.  When an Objective-C method returns a BOOL and passes in an `out` error param it will map to return `()`  + `throw` as mentioned above.

**Comment by donileo** [comment]
>@donileo ...

@R4N Thanks my issue with this is that it changes how FMDB is used. In objc you while over res.nextError. In swift you cant. But I understand nothing could probable be done anyways. Closing issue...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
