### ISSUE TITLE
Swift extension on FMDatabase

### ISSUE THREAD

**Issue by donileo** [ccgus/fmdb#689]
I’m trying to extend FMDatabase’s hasOpenResultSets property to do something simple: print out a message stating how many open result sets there are. 

I do this via:
```
import FMDB

extension FMDatabase {
  override var hasOpenResultSets: Bool {
    print(<num of open result sets here>)
    return <boolean check here>
  }
}
```

Whats inside the computed property is not so important. The issue is Xcode tells me cant override hasOpenResultSets no property found.

The property is there though and public, so what can I do to properly get it to override. My reason for this extension is troubleshooting.

**Comment by R4N** [comment]
I don't believe extensions can override existing functionality

https://docs.swift.org/swift-book/LanguageGuide/Extensions.html
> NOTE
Extensions can add new functionality to a type, but they cannot override existing functionality.

**Comment by donileo** [comment]
Yea... :) I realized this yesterday. Thanks.

-- 
Adonis
