### ISSUE TITLE
FMDatabaseQueue calls “self.logsErrors”

### ISSUE THREAD

**Issue by peternlewis** [ccgus/fmdb#698]
In FMDatabaseQueue.m, in:

```
- (NSError*)inSavePoint:(__attribute__((noescape)) void (^)(FMDatabase *db, BOOL *rollback))block {
```
includes the code:

```
#else
    NSString *errorMessage = NSLocalizedStringFromTable(@"Save point functions require SQLite 3.7", @"FMDB", nil);
    if (self.logsErrors) NSLog(@"%@", errorMessage);
    return [NSError errorWithDomain:@"FMDatabase" code:0 userInfo:@{NSLocalizedDescriptionKey : errorMessage}];
#endif

```

Since FMDatabaseQueue does not actually have a logsErrors property (unless I am missing something), I presume this will not actually compile.  The code looks to have been copied unchanged and untested from FMDatabase.m.  If that is the case, and no one else has ever reported this, then you can probably safely change it to a #error pragma instead of bothering to handle the per 3.7 case.  Otherwise, it should presumably use self.database.logsErrors

**Comment by ccgus** [comment]
Thanks for spotting this! I've just pushed up a fix.
