### ISSUE TITLE
Xcode 10 beta

### ISSUE THREAD

**Issue by sathishkraj** [ccgus/fmdb#700]
Hi,
There is a compiler error when I tried to update the carthage with xcode 10 beta tool.
Is there are a working branch for xcode 10 beta?
Carthage version - 0.30.1

Thanks,
Sathish Kumar.

**Comment by wangqiwei66** [comment]
I have the same issue on Carthage 0.30.1 .
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/heping/SGMobile/Carthage/Checkouts/fmdb/fmdb.xcodeproj -scheme FMDB\ iOS -configuration Release -derivedDataPath /Users/heping/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/fmdb/2.7.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/nq/b0t5xvw97332lxh8hr_lyzzw0000gn/T/fmdb SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/heping/SGMobile/Carthage/Checkouts/fmdb)

**Comment by wxindfx** [comment]
Xcode 10 is released today, still compiled error in v2.7. But master can be compiled successfully. Would you release a new version to fix Xcode 10 compilation error?

**Comment by ccgus** [comment]
2.7.5 is up.
