### ISSUE TITLE
Error when using pod 'FMDB/SQLcipher'

### ISSUE THREAD

**Issue by BBB1n** [ccgus/fmdb#701]
Execution of pod 'FMDB/SQLCipher', '~> 2.7.2' error, yesterday no problem

System = 10.13.4
Pod version = 1.5.3

The following is the error message:

Installing FMDB (2.6.2)
Installing SQLCipher (3.4.2)
[!] /bin/bash -c
Set -e
./configure --enable-tempstore = yes --with-crypto-lib = commoncrypto CFLAGS = "- DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE = 2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999"; make sqlite3.c

Checking build system type... i386-apple-darwin17.5.0
Checking host system type... i386-apple-darwin17.5.0
Checking how to print strings... printf
Checking for gcc... clang
Rating whether the C compiler works... yes
Checking for C compiler default output file name... a.out
Checking for suffix of executables...
Checking whether we are cross compiling...
Configure: error: in `/Users/zhaowenbin/Library/Caches/CocoaPods/Pods/Release/SQLCipher/3.4.2-f9fcf':
Configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by R4N** [comment]
@BBB1n 

I just re-tested FMDB/SQLCipher pod integration using macOS 10.13.6 + Pod Version 1.5.3 and it's working fine on my end.  It's most likely something awry with your local configuration.  What Xcode version are you using?  As my colleague mentioned in the other [issue you opened](https://github.com/sqlcipher/sqlcipher/issues/278) you should examine/post the `config.log` which should provide additional details.

**Comment by BBB1n** [comment]
Thank you for your reply, I found that there may be a problem with the pod configuration. Yesterday I tried it with my own computer. Thank you again.
