### ISSUE TITLE
pod FMDB install command use 2.6 and not 2.7 - need to fix finalize warning

### ISSUE THREAD

**Issue by kmav** [ccgus/fmdb#702]
I would like to use latest FMDB in order to fix deprecated finalize warning in FMDatabase.m
The following code contained in latest FMDatabase.m was not present:
`#if ! __has_feature(objc_arc)`
`- (void)finalize {`
`    [self close];`
`    [super finalize];`
`}`
`#endif`

It was there without the compiler #if directive. 

I have in my podfile:
`pod 'FMDB'`
When I run `pod install` I get:
Using FMDB (2.6)

I changed my podfile to:
`pod 'FMDB', '2.7.2'`
Then I got:
`Installing FMDB 2.7.2 (was 2.6 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)`

Why 2.7 is not used by default?
Is it correct the 2.7.2 change that I did in my podfile?

**Comment by ccgus** [comment]
I don't use cocoapods, so I have no way to test changes. If you want to make the changes and submit a PR, feel free :)

**Comment by kmav** [comment]
Hello,
thank you for your reply.

You don't use Cocoapods? I guess that somebody else should contribute to that area and to your related documentation. Correct?
Can you try to answer at least what Cocoapods should have download: 2.6, 2.7 or 2.7.2 ? For the moment I see that without any parameters it is downloading 2.6. 
Maybe I can do a PR but, I need to know what to fix/change,... what is correct and what it is not :)

Kostas

**Comment by ccgus** [comment]
I don't use Cocoapods, someone else made the patches for it.

I don't know what it should have downloaded.

**Comment by ccgus** [comment]
Trunk is stable.

**Comment by DwayneCoussement** [comment]
@ccgus could I think you forgot to push to the new podspec with version 2.7.3 and 2.7.4, see https://cocoapods.org/pods/FMDB

**Comment by ccgus** [comment]
I try and push, and CocoaPods just throws an error about not having found any iOS simulators.

**Comment by NickGaens** [comment]
@ccgus 2.7.2 is still the latest version listed on Cocoapods, despite 2.7.5 being available. Can you please retry to push?

**Comment by ccgus** [comment]
I retried. It's still not working. Not sure WTF is up with CocoaPods not working for me.

**Comment by ccgus** [comment]
Knock yourself out:

```Validating podspec
 -> FMDB (2.7.5)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: watchos). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.
```

**Comment by ccgus** [comment]
I figured it out. You need 3 simulators installed. tv, iPhone, and watch. That's super annoying and not obvious. Anyway, it's up now. Supposedly:

 🎉  Congrats

 🚀  FMDB (2.7.5) successfully published
 📅  September 24th, 09:54
 🌎  https://cocoapods.org/pods/FMDB
 👍  Tell your friends!
