### ISSUE TITLE
Compiler warning: 'sqlite3_wal_checkpoint_v2' is only available on macOS 10.8 or newer'

### ISSUE THREAD

**Issue by sicilian-lizard** [ccgus/fmdb#709]
I got this warning:

'sqlite3_wal_checkpoint_v2' is only available on macOS 10.8 or newer' in 'FMDatabase', line number: 1490.

I am using FMDB: 2.7.5, Xcode 10.

Anything I can do to suppress the warning? 

Thanks.

**Comment by ccgus** [comment]
What version of the sdk do you have Xcode set to deploy to?

**Comment by sicilian-lizard** [comment]
It's macOS 10.10.

**Comment by ccgus** [comment]
I'm not sure why it would say that then. Maybe expand the whole build command and see exactly what is being sent to the compiler, and paste it here.

**Comment by sicilian-lizard** [comment]
Not a bug
