### ISSUE TITLE
stringForColumnIndex: sometimes returns a string of __NSCFConstantString

### ISSUE THREAD

**Issue by ameue** [ccgus/fmdb#712]

**Comment by ccgus** [comment]
Is this a problem?

**Comment by FatChou** [comment]
I do this:
id object = [[Example alloc] init];
NSString *str = [stringForColumnIndex:0];//str is not nil
[object setValue:str forKey:"exampleColumn"];

but object.exmapleColumn is @""

**Comment by FatChou** [comment]
I am confirm that there is data in this row in this table in sqlite.but
NSString *str = [rs stringForColumnIndex:0];
str is not empty

**Comment by ccgus** [comment]
I guess I'm not getting what's going on. If you can reproduce the sample as described here: https://github.com/ccgus/fmdb/#reporting-bugs , that would help a lot.

**Comment by FatChou** [comment]
ok!

**Comment by ameue** [comment]
Maybe it’s my problem with using data in the business layer.
