### ISSUE TITLE
Swift FMDatabaseQueue : on a thread to query a singleton dbqueue but makes memory leak

### ISSUE THREAD

**Issue by mic215fa** [ccgus/fmdb#718]
Hi sir,

I start a thread to execute a query function() - **getEcgServer3Data** - in a singleton dbmanager. But after getting the query result (**dataArray**) from the thread, I found this query result making  "memory leak".  This situation had been verified by the Instruments. And after I removed the query function from the thread, there will stop memory leak at once. Does the singleton dbmanager not legal in the thread?

Luke

=======================================
class ServerConnect: NSObject {

	func startUpload() {
	    uploadThread = Thread(target: self, selector: #selector(timerwork), object: nil)
	    uploadThread.start()
	}

	 @objc func timerwork() {
	 	 while {
		 	 if UploadToServer(acc: accountConnect!, pwd: defaultPasswd) {
		        Thread.sleep(forTimeInterval: 2)
		     }  else {
		     	Thread.sleep(forTimeInterval: 10)
		     } 
	     }         
	 }

	 func UploadToServer() {
	 	let dbm : DBManager = DBManager.shared
                var dataArray = dbm.getEcgServer3Data()
	 }
	 
}

class DBManager: NSObject {

	static let shared: DBManager = DBManager()
	var dbQueue:FMDatabaseQueue?

	overide init {
		pathToDatabase = documentsDirectory.appending("/\(databaseFileName)")
		dbQueue = FMDatabaseQueue(path: pathToDatabase)
	}

	 func getEcgServer3Data() -> [EcgServerInfo] {
		
		var ecgsers: [EcgServerInfo]! = [EcgServerInfo]()
		ecgsers = nil
		dbQueue?.inTransaction({ (database, rollback) in
		
			let querycmd = "select * from ecg_server_records  ;" 	
			do {
				let results:FMResultSet? = try database.executeQuery(querycmd, values: nil)
				while results!.next() {
				   ecgsers.append(results) 
				}	
			} catch {
			}

		})

		if (ecgsers == nil) {
			return [EcgServerInfo]()
		} else {
			return ecgsers
		}
    }
}

**Comment by ccgus** [comment]
I'm not aware of any memory leaks in this area. If you could point them out specifically, then that would be good to know.

What objects are being leaked from FMDB?

Is it possible that an object outside of FMDB is leaking, created from memory allocated from FMDB?

**Comment by mic215fa** [comment]
Finally, I checked that the running method of the thread was wrong.  It made the objects couldn't be released and let the memory be persisted.
