### ISSUE TITLE
FBDB does not work with SQLCipher 4.0.0

### ISSUE THREAD

**Issue by mezhevikin** [ccgus/fmdb#720]
After update SQLCipher from 3.4.2 to 4.0.0, i'm getting an error "File is not database".

**Comment by billymeltdown** [comment]
Hi there @mezhevikin, the version 4.0.0 release has some pretty extensive changes, we've got some information about that in our blog post:

https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/

The compatibility section has information about opening and upgrading databases created by previous versions of SQLCipher:

> Many of these changes provide a much higher level of security than previous versions of SQLCipher. However, the new page size of 4096, 256,000 KDF iterations, use of PBKDF2-HMAC-SHA512 and HMAC-SHA512 all modify important database settings. Thus, SQLCipher 4 will not open older databases by default.

**Comment by billymeltdown** [comment]
I should add, if you're having trouble upgrading a database, feel free to stop by our forum: https://discuss.zetetic.net/c/sqlcipher

**Comment by mezhevikin** [comment]
@billymeltdown thank you for response
