### ISSUE TITLE
help

### ISSUE THREAD

**Issue by flyOfYW** [ccgus/fmdb#731]
How can you sort text, or other types of sorting @ccgus

**Comment by ccgus** [comment]
Add an `order by` clause in your sqlite query.

**Comment by flyOfYW** [comment]
I'm sorry, I might have misstated it, I mean, how do I customize the collation

**Comment by ccgus** [comment]
FMDB doesn't expose any interface to sqlite3_create_collation, you'll have to do that yourself.
