### ISSUE TITLE
FMDB/SQLCipher 3.x to 4.x migration issue

### ISSUE THREAD

**Issue by suprajadarisa** [ccgus/fmdb#732]
Hi Team,

I am using FMDB/SQLCipher for encrypting my database. I have an old version of the application running on the 3.x version of SQLCipher. When trying to install a new update(which is running on the 4.x version of SQLCipher), we got the file is not a database error. 

We tried to migrate the Cipher version by using cipher_migrate, tried for backward compatibility using cipher_compatibilty, tried creating a new database and copying the old data, but nothing worked. 

Please let me know how can I solve this issue

**Comment by ccgus** [comment]
Sorry, this isn't an FMDB issue, rather it's a SQLCipher issue. You'll have to talk with them.

**Comment by suprajadarisa** [comment]
Thanks for the information.
Is there anyway that we can restrict fmdb to download a particular version SQLCipher

**Comment by ccgus** [comment]
Not that I'm aware of. I assume you're using cocoa pods? I'd skip that and download what you need and integrate it manually.

**Comment by jlcool** [comment]
@ccgus Teach me how to do it
