### ISSUE TITLE
Non-public API usage

### ISSUE THREAD

**Issue by cj768025549** [ccgus/fmdb#739]
ITMS-90338: Non-public API usage - The app references non-public selectors in Dev: databasePool:didAddDatabase:, databasePool:shouldAddDatabaseToPool:,

**Comment by robertmryan** [comment]
Sounds like one of Apple’s many false positives re private API. I’d suggest you contest the denial as such.

**Comment by ccgus** [comment]
You could also take out the FMDatabasePool classes if you aren't using them.
