### ISSUE TITLE
Static target 'FMDB' does not enable the 'CLANG_ENABLE_OBJC_ARC' flag, causing compilation issues due to -finalize methods

### ISSUE THREAD

**Issue by LeoNatan** [ccgus/fmdb#740]
As title states, it seems the `FMDB` target is the only one not to enable the `CLANG_ENABLE_OBJC_ARC` compiler flag in the build settings. This, coupled with `CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS` and `GCC_TREAT_WARNINGS_AS_ERRORS`, causes Xcode to complain about the `-finalize` methods peppered throughout.

**Comment by LeoNatan** [comment]
Submit a PR?

**Comment by ccgus** [comment]
Sure.

**Comment by LeoNatan** [comment]
Two PRs already submitted :)

**Comment by ccgus** [comment]
And merged. Thanks!

**Comment by LeoNatan** [comment]
Thanks
