### ISSUE TITLE
FMDatabasePool causes data confusion

### ISSUE THREAD

**Issue by Lidalu** [ccgus/fmdb#744]
I use FMDatabasePool to achieve multi-threaded access to the database. When I am reading table A, there are other threads writing table A, which will cause the data I read to be confusing. Is there any good solution?
FMDatabaseQueue performance is very low at high concurrent read and write.

**Comment by ccgus** [comment]
There's no good solutions built in, other than using the queue.

**Comment by robertmryan** [comment]
@Lidalu

> `FMDatabaseQueue` performance is very low at high concurrent read and write.

Are you 100% sure that the performance issue is, indeed the attempt at concurrency and not, for example, a lack of transactions when doing many SQL statements. Transactions can have remarkable impact on performance when doing many updates...

**Comment by Lidalu** [comment]
Yeah, I have a 6G db file. When I use Transactions doing many updates with FMDatabaseQueue . At the same time, I do some select statements, select operating will wait the previous operation is completed. It will cause the poor user experience. So I use the FMDatabasePool to achieve multi-threaded access to the database.

**Comment by Lidalu** [comment]
Sorry, It's my mistake, I wrote a wrong code. FMDB is OK! @ccgus @robertmryan
