### ISSUE TITLE
How to Insert array of rows in to the table in Swift?

### ISSUE THREAD

**Issue by Suneel-Gunupudi** [ccgus/fmdb#745]
I am facing one issue as multi-threading while inserting and fetching data from a table. My Question is when inserting an array of data into a table, we need to open and close the database every row in an array or it should be one time to open database and after the execution all query and then close all and vice versa? I am using a singleton class for inserting and retrieving data. Kindly suggest to me.

**Comment by ccgus** [comment]
Just open the database connection once. Use a the serial queue to keep things in order across threads.
