### ISSUE TITLE
查询表中全部数据，数据丢失？

### ISSUE THREAD

**Issue by 183959633** [ccgus/fmdb#746]
在这个 while ([ResultSet next]) { }方法中调用 【ResultSet resultDictionary】可以看到遍历得到每一项的数据，但是添加到数组中后，最终打印结果，数据丢失，缺失！！！

**Comment by xingheng** [comment]
Have you tried to figure out what exactly the bug is? Refer to [this](https://github.com/ccgus/fmdb#reporting-bugs).

Call stack? Repo steps?

**Comment by 183959633** [comment]
> 您是否试图找出错误究竟是什么？参考[这个](https://github.com/ccgus/fmdb#reporting-bugs)。
> 
> 调用堆栈？回购步骤？

我是在while（[ResultSet next]方法中，将【ResultSet resultDictionary】返回的字典添加到可变数组中，在while内部打印数据正常，在方法外打印数据部分丢失，缺失，只能打印出6条数据左右，如果在方法内部不调用【ResultSet resultDictionary】而是原始的model模型，将model模型添加到可变数组中，那么最终数据是正常的！所以，我怀疑【ResultSet resultDictionary】模型转字典内部出错了！！！

**Comment by SeanChense** [comment]
This issue can be closed.
