### ISSUE TITLE
Support for Swift Package Manager?

### ISSUE THREAD

**Issue by kevray** [ccgus/fmdb#750]
Are there plans for supporting the Swift Package Manager anytime soon?

**Comment by BSFishy** [comment]
Well, according to the readme,
> You can use FMDB in Swift projects too.
> 
> To do this, you must:
> 
> 1. Copy the relevant .m and .h files from the FMDB src folder into your project.

Based on that and the fact that the project itself is written in Objective-C, I wouldn't assume that the project will eventually get support for anything like that, but then again, I am relatively new to Apple development, and could be mistaken, in that it is possible to put an Objective-C project on the Swift Package Manager.

**Comment by ccgus** [comment]
I'm happy to have swift package manager support for FMDB. Someday, I might get around to it- or someone else could submit a PR.

From what I understand, the project doesn't need to be in swift to be part of the spm.

**Comment by kevray** [comment]
Objective-C is supposed to work with SPM. I tried to add it to FMDB, but couldn't seem to get it to work. I was hoping someone smarter than I would look into it...

**Comment by Nelyus** [comment]
I confirm it should be possible for fmdb to be an spm package.
I might look into it someday.

**Comment by lynns** [comment]
Support for SPM would be really helpful.

**Comment by pcmanik** [comment]
anything new?

**Comment by ccgus** [comment]
Nope, I haven't had the inclination to dig into it, and nobody has offered PR's for it.

**Comment by Nelyus** [comment]
I managed to have a working library target.
I didn't spend much time on it, but I couldn't make a working test target.

**Comment by ccgus** [comment]
I've merged it. Now I need to find time to test it :)

**Comment by gsabran** [comment]
Once you have, could you share the config you used? I've tried `.package( url: "https://github.com/ccgus/fmdb.git", from: "2.7.5")` but Xcode says `https://github.com/ccgus/fmdb.git has no Package.swift manifest for version 2.7.5`

**Comment by Nelyus** [comment]
The revision with the package manifest has not been tagged yet. So there is no version you can put after `from:` that would work, but you can still point to a specific commit:
```
.package(url: "https://github.com/ccgus/fmdb",
         .revision("9b100cc3dd83ff88a17a4da8718eab4b08e2fe67")),
```

**Comment by turtlemaster19** [comment]
The revision in question above would be 9b100cc3dd83ff88a17a4da8718eab4b08e2fe67 which does in fact work. Hopefully it can be tagged soon! ;)

**Comment by ccgus** [comment]
Would just adding a tag on the master branch be OK?

**Comment by turtlemaster19** [comment]
I think so. It would just need to be a new version so that installing the master branch would choose the new version. 😉

**Comment by kevray** [comment]
@Nelyus thank you for getting this working! I have SPM pointed at the master branch and so far its working great.

**Comment by turtlemaster19** [comment]
@ccgus Yes. Can you please do this?

**Comment by ccgus** [comment]
@turtlemaster19 The tag "sw01master" has been added.

**Comment by turtlemaster19** [comment]
@ccgus Is there any way to use a number instead of letters like that?

**Comment by ccgus** [comment]
@turtlemaster19 Of course, but could you explain to me why? letters are nice, since they let me know what the tag is for.

**Comment by turtlemaster19** [comment]
@ccgus Not at home, but I believe if it is a number, it will count as a version and we can just close this. ;)

**Comment by jaerod95** [comment]
Also by using a semantic number will allow it to be used easily by Accio.

**Comment by ccgus** [comment]
I have no idea what Accio is. At any rate- I've added a tag that's a number: 1612

**Comment by turtlemaster19** [comment]
@ccgus https://github.com/JamitLabs/Accio
It seems to be a package manager based on SwiftPM

**Comment by waterskier2007** [comment]
@ccgus any update on this?

**Comment by ccgus** [comment]
@waterskier2007 Someone else is going to have to drive this. I don't use package managers and I haven't dug into the swift package manager at all. I'm happy to merge stuff and add tags where needed. I've just bumped the version again and added a tag. (2.7.6)

**Comment by turtlemaster19** [comment]
@ccgus Thank you. Feel free to close this issue now!

**Comment by turtlemaster19** [comment]
@ccgus P.S. Would you mind removing the `sw01master` and `1612` tags? They don't seem to serve any purpose anymore and it just seems kind of weird in the version history. Thank you!
