### ISSUE TITLE
ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by leejtom** [ccgus/fmdb#751]
ITMS-90338: Non-public API usage:

databasePool:didAddDatabase:
databasePool:shouldAddDatabaseToPool:

in: FMDatabasePoolDelegate 
```
- (BOOL)databasePool:(FMDatabasePool*)pool shouldAddDatabaseToPool:(FMDatabase*)database;
- (void)databasePool:(FMDatabasePool*)pool didAddDatabase:(FMDatabase*)database;
```

**Comment by leejtom** [comment]
Now let me put a prefix on it：
```
- (BOOL)fm_databasePool:(FMDatabasePool*)pool shouldAddDatabaseToPool:(FMDatabase*)database;
- (void)fm_databasePool:(FMDatabasePool*)pool didAddDatabase:(FMDatabase*)database;
```

**Comment by robertmryan** [comment]
Or you can just reply to the “non-public API usage” rejection with a clarification that you are not using any private API, but rather just a similarly named method in a well-established third library that has been around for years. 

Or, if you’re not using the database pool, just exclude it from the sources entirely.

**Comment by leejtom** [comment]
> Or you can just reply to the “non-public API usage” rejection with a clarification that you are not using any private API, but rather just a similarly named method in a well-established third library that has been around for years.
> 
> Or, if you’re not using the database pool, just exclude it from the sources entirely.

Thx.
I need this library, and if I don't deal with this problem, there will be no build version on appstoreconnect....
Recommended to focus on such issues

**Comment by shauket** [comment]
still no fix for this one?

**Comment by ccgus** [comment]
@shauket There's no fix to be made. FMDB isn't using SPIs.

**Comment by AlphaRunTime** [comment]
what's the problem?
