### ISSUE TITLE
Transaction using huge memory

### ISSUE THREAD

**Issue by suprajadarisa** [ccgus/fmdb#755]
I am running into an issue which uses 1.5 GB of memory every time I run a load.
Also observed the memory is consumed by a single transaction which has a loop in it.

DispatchQueue.global(qos: .default).async(execute: {
                            self?.queue?.inTransaction({(db: FMDatabase?, rollback: UnsafeMutablePointer<ObjCBool>?) in  			
	for obj in objArray { 				
	Inserts data into 8 different tables 		
	Deletes data from 5 different tables
}
})
})

My app is trying to loop through 165 records inside the transaction and the memory goes to >1.5GB and app gets killed.

I am using FMDB with SQLCipher. FMDB - 2.6.2 and SQLCipher - 4.2.0

This issue is blocking me to use the application. Any help is appreciated

**Comment by ccgus** [comment]
What does instruments say the memory is coming from?

**Comment by R4N** [comment]
@suprajadarisa

Try testing this behavior without database encryption (i.e. either test on a database without keying it to disable encryption, or using FMDB without the SQLCipher subspec).

If the same behavior doesn't occur without SQLCipher you may want to experiment with disabling the `cipher_memory_security` to see if it has any affect.

The [SQLCipher 4.0.0 release](https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/) introduced full memory wiping which is enabled by default.  You can disable this feature for performance when the feature is not required by using [PRAGMA cipher_memory_security](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_memory_security)
