### ISSUE TITLE
I got different result with same sql in iOS11 and iOS13

### ISSUE THREAD

**Issue by byztl** [ccgus/fmdb#757]
I use fmdb to storagechat content.  And now i got a problem. 
I use 
``select * from 'table_qiuxuankai' group by communicationID order by id desc``
to refresh my chat list. In iOS11, it works. I can get result which divide by  communicationID and are newset messages. 
but in iOS13. i excuted same sql. i can only get oldest message, all throught they are divided by "communicationID" but that's not what i want.  
iOSVersion: 13.1.2.
Xcode: v.11.1
FMDB: v.2.7

**Comment by ccgus** [comment]
You're better off checking on the sqlite mailing lists or various online forums. This isn't FMDB specific.
