### ISSUE TITLE
High cpu usage issue

### ISSUE THREAD

**Issue by humoroutlaw** [ccgus/fmdb#759]
My question is, 
when I log in my app, fmdb will works, and every time i use db open and db close, here the problem comes, under high  frequency action for log in, maybe every 1s per time, my cpu will be pretty high, and I use Instruments to check, seeing the most “Self Weight” part is [FMDatabase openWithFlags] and [FMDatabase close],so need I open and close each I am using database???
![91D0E222-D1FD-4CCA-8CF4-EB8A47094904](https://user-images.githubusercontent.com/17940371/67613277-2e1d8e00-f7de-11e9-8776-7232ee9516be.png)

**Comment by ccgus** [comment]
No, just open your database once, and use it over and over.

**Comment by humoroutlaw** [comment]
Aware, thanks for your reply!
