### ISSUE TITLE
[FMDatabaseQueue dealloc] when  app run in background mode.

### ISSUE THREAD

**Issue by CNHarrySun** [ccgus/fmdb#760]
I use it like this: 
```
+ (BOOL)openDB:(NSString *)path {
    [self closeDB];
    if (path.length > 0) {
        dbQueue = [FMDatabaseQueue databaseQueueWithPath:path flags:SQLITE_OPEN_FULLMUTEX | SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE];
    }
    return (dbQueue != nil);
}

+ (void)closeDB {
    if (dbQueue) {
        [dbQueue close];
    }
    dbQueue = nil;
}
```

**Comment by ccgus** [comment]
I don't have enough info here to help diagnose, sorry. Sounds like you've got a general memory management problem somewhere though.

**Comment by CNHarrySun** [comment]
Thanks Reply.
Look at this picture, Is this my use wrong?
![image](https://user-images.githubusercontent.com/16249166/67838254-d9ef1280-fb2b-11e9-859a-f8074d495d6e.png)

**Comment by CNHarrySun** [comment]
My database queue is a static.
![image](https://user-images.githubusercontent.com/16249166/67928511-2a32a700-fbf6-11e9-9f59-bf9b6ca477e9.png)

**Comment by ccgus** [comment]
That doesn't mean it's retained- it's obviously being dealloced somehow (based on the stack trace you sent)

**Comment by CNHarrySun** [comment]
OK, Thank you. Let me see for myself.
