### ISSUE TITLE
How lively is the project?

### ISSUE THREAD

**Issue by Max-Job** [ccgus/fmdb#765]
We want to use your project for your own application.
Is the project abandoned or is it working perfectly now and does not require improvements? Do you plan further support?

**Comment by ccgus** [comment]
Well, it's used by possibly thousands of applications at this point? FMDB is pretty solid, and I fix bugs wherever they crop up. I have plans for a future update, but really nobody is pushing for anything new and awesome these days since it's already solid as is.

Support continues of course.

**Comment by robertmryan** [comment]
@Max-Job - The next time you want to see how “lively” a git repo is, just look at its [commit history](https://github.com/ccgus/fmdb/commits/master). That gives you a good indication of whether its reasonably actively maintained.
