### ISSUE TITLE
XPC connection interrupted

### ISSUE THREAD

**Issue by qiucen** [ccgus/fmdb#770]
This issue occurs when jumping to the model creating method. I've located  the error in these two lines:
"NSArray *array = [NSArray arrayWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"photos.plist" ofType:nil]];
    NSMutableArray *arrM = [NSMutableArray arrayWithCapacity:10];"
It confused me for several hours, but I don't know how to solve it. Can somebody help me out? thx a lot!

**Comment by ccgus** [comment]
This has nothing to do with FMDB, sorry.
