### ISSUE TITLE
Accessing an ivar of an atomic property makes the property nonatomic

### ISSUE THREAD

**Issue by alexandern17** [ccgus/fmdb#772]
This is simply a code "betterment" suggestion, no real issue with the code thus far in using it in our application.

Ran infer static analyzer (https://fbinfer.com/) and it produced many warnings on accessing the ivars directory in the class code.  

i.e.

`Libraries/FMDB/FMDatabase.m:1687: warning: DIRECT_ATOMIC_PROPERTY_ACCESS
  Direct access to ivar `_statement` of an atomic property at line 1687, column 9. Accessing an ivar of an atomic property makes the property nonatomic.
  1685.       if (_statement) {
  1686.           sqlite3_finalize(_statement);
  1687. >         _statement = 0x00;
  1688.       }
  1689.   `

Like the warning says, doing this makes an atomic property nonatomic.

**Comment by ccgus** [comment]
I'm not worried about it.
