### ISSUE TITLE
Delete not executed when IN keyword is used in WHERE statement

### ISSUE THREAD

**Issue by leospace** [ccgus/fmdb#784]
I want to batch delete some row onetime, I call [db executeUpdate:sql withArgumentsInArray:propValues];
it returns YES, but NO any row can be deleted.
I trace the sql command: 
`
<FMDatabase: 0x2820dcc00> executeUpdate: delete from xxxx  where id IN(?)
obj: '2cf6b699-f528-4989-9801-d4f1440838e6','e888bdc4-7db9-4aa3-9fdc-c7b3a479aa7d'
`

I try to execute this sql command directly in SQLite can delete two rows data:
`delete from xxxx  where id IN('2cf6b699-f528-4989-9801-d4f1440838e6','e888bdc4-7db9-4aa3-9fdc-c7b3a479aa7d')`

Did I use the function ‘executeUpdate’ the wrong way when IN keyword is used in WHERE statement?
Or how the IN keyword should be used?

Thanks

**Comment by ccgus** [comment]
This is more of an SQLite problem, not so much FMDB- I'm not sure you can bind variables like this. You might try bringing it up on the SQLite mailing list.

**Comment by leospace** [comment]
> This is more of an SQLite problem, not so much FMDB- I'm not sure you can bind variables like this. You might try bringing it up on the SQLite mailing list.

Today, I try to build following sql command again, and then it worked:
`<FMDatabase: 0x2837bbde0> executeUpdate: delete from PRSDeviceCommandLog  where logId IN(?,?,?,?,?)`

I still call the method `[db executeUpdate:sql withArgumentsInArray:propValues]`, and the propValues 
 array contains the same number of  '?' in `IN(?,?,?,?,?)`, like 5 items.

I think will many people have the similar questions about IN keyword when they call the method `[db executeUpdate:sql withArgumentsInArray:propValues]`, so I suggest you can add the usage method for IN keyword into the Sample codes, thanks.
