### ISSUE TITLE
1 prepared statement with many row data

### ISSUE THREAD

**Issue by CharlieReece** [ccgus/fmdb#786]
This may more likely be a feature request.
I have been using just 1 prepared statement and insert multiple data one after another by just using: 
- BEGIN transaction
- LOOP
- - **sqlite3_bind_***
- - **sqlite3_step**
- - **sqlite3_reset**
- COMMIT/ROLLBACK transaction

I could not find something similar in FMDB, am I missing something here? (As far as I see, I have to send the full query again and again, regardless of its being in a transaction or not.)

**Comment by CharlieReece** [comment]
At least, something _like_ the following could work, which would internally do bind,step,reset:
```
        [db executeQuery:@"REPLACE INTO mytable (col1,col2) VALUES(?,?)",
         @[
             @[@"row1a",@"row1b"],
             @[@"row2a",@"row2b"]
         ]
        ];
```

**Comment by robertmryan** [comment]
It strikes me that turning on `shouldCacheStatements` is a database-level thing, and we really should be allowing rebinding at the query-level. Conceptually, renditions of `executeQuery` and `executeUpdate` that takes no parameters, and returns a `FMResultSet`, and adding a method to (a) bind values; and (b) perform the query via `sqlite3_step`, e.g.:

```objc
NSString *sql = @"INSERT INTO book (title, name) VALUES (?, ?)";

FMResultSet *rs = [db executeQuery:sql];
for (Book *book in books) {
    BOOL success = [rs stepWithValues:@[book.title, book.author]];
    if (!success) {
        // handle errors here, e.g. duplicate keys, etc.
    }
}
```

Or, if we don’t like the single function call handling both the binding and the performing of the query, just have a `bindValues` method on `FMResultSet`, e.g.:

```objc
NSString *sql = @"INSERT INTO book (title, name) VALUES (?, ?)";

FMResultSet *rs = [db executeQuery:sql];
for (Book *book in books) {
    [rs bindValues:@[book.title, book.author]];
    if (![rs step]) {
        // handle errors here, e.g. duplicate keys, etc.
    }
}
```

I’m happy to take a crack at that (as properly PR; lol) if you’d like, @ccgus.

**Comment by ccgus** [comment]
This is reasonable, but instead of overusing `executeQuery:` and `executeUpdate:` I'd rather see something the along the line of `prepareQuery:` and `prepareUpdate:`. It'll means we won't have to add more complexity to `executeQuery:`, and to my eyes it's more obvious to the caller as to what is going to happen.

I like the second example a bit more than the first, with the call to `[rs bindValues]` and then the `step` to execute.
