### ISSUE TITLE
install FMDB && FMDB / SQLCipher code will be error

### ISSUE THREAD

**Issue by niuxinhuai** [ccgus/fmdb#795]
version number

Xcode (v11.3 (11C29))

FMDB (v2.7.5)

FMDB / SQLCipher (FMDB v2.7.5, SQLCipher v3.1.0)

In the project, I used a mixture of native and flutter development. The native project used FMDB / SQLCipher to process the encrypted database, and the flutter code used FMDB to perform another database operation, which caused the database decryption process in the native project to fail. , The reason is the same as the Demo currently provided, In the case where both FMDB and FMDB / SQLCipher introduce pods, I cannot solve the error problem that appears, I hope you can help me solve this problem

Below is the Demo address, hope you can help me
https://github.com/niuxinhuai/fmdb_example

**Comment by R4N** [comment]
From a SQLCipher standpoint, this is an unsupported scenario. See this document for reference: https://www.zetetic.net/sqlcipher/ios-tutorial/#option-2-cocoapod-integration -- specifically the note there:

> Note: We DO NOT SUPPORT using SQLCipher with a project that includes a separate sqlite3 dependency, including via CocoaPods. That sort of configuration carries multiple inherent risks, including undefined behavior, deadlocks, loss of data, loss of encryption functionality. That said, one way to prevent undefined linking behavior or silent failures is to ensure that SQLCipher is linked into the application first. Please see this post for recommendations: Important Advisory: SQLCipher with Xcode 8 and new SDKs

We have had a couple of requests for SQLCipher for Flutter, but don't have immediate plans for it at this point: https://discuss.zetetic.net/t/sqlcipher-for-flutter/3790

**Comment by niuxinhuai** [comment]
> From a SQLCipher standpoint, this is an unsupported scenario. See this document for reference: https://www.zetetic.net/sqlcipher/ios-tutorial/#option-2-cocoapod-integration -- specifically the note there:
> 
> > Note: We DO NOT SUPPORT using SQLCipher with a project that includes a separate sqlite3 dependency, including via CocoaPods. That sort of configuration carries multiple inherent risks, including undefined behavior, deadlocks, loss of data, loss of encryption functionality. That said, one way to prevent undefined linking behavior or silent failures is to ensure that SQLCipher is linked into the application first. Please see this post for recommendations: Important Advisory: SQLCipher with Xcode 8 and new SDKs
> 
> We have had a couple of requests for SQLCipher for Flutter, but don't have immediate plans for it at this point: https://discuss.zetetic.net/t/sqlcipher-for-flutter/3790

Thank you for your reply, I will modify my code
