### ISSUE TITLE
Compilation errors with Xcode 12 beta

### ISSUE THREAD

**Issue by noberasco** [ccgus/fmdb#800]
Hi,

we have a project where we use CocoaPods to add FMDB/SQLCipher as a dependency.
Everything works when using latest stable versions of Xcode and iOS SDK.

Using latest XCode and iOS 14 SDK betas, compilation fails with various 'redefinition' errors:
[https://lab.zirak.it/test/shot1.png](https://lab.zirak.it/test/shot1.png)
[https://lab.zirak.it/test/shot2.png](https://lab.zirak.it/test/shot2.png)

From what I could see, iOS 14 SDK updated SQLite from version 3.28.0 to 3.32.3, which has extra symbols defined in `sqlite3ext.h`.

Example:
```
   /* Version 3.32.0 and later */
  char (*create_filename)(const char,const char*,const char*,
                           int,const char**);
  void (free_filename)(char);
  sqlite3_file (*database_file_object)(const char);
```

These changes clash with the version of the same headers brought in by pod FMDB/SQLCipher.

**Comment by robertmryan** [comment]
I've updated the two image links above.

What versions of FMDB and SQLCipher were installed from `pod install`? (Check your `Podfile.lock`.)

I just did tested in Xcode 12.0.1 (12A7300) and got no such warning. Help us reproduce the problem by creating [MCVE](https://stackoverflow.com/help/mcve), a simple blank project that manifests the problem you describe.

**Comment by R4N** [comment]
I also wasn't able to reproduce this in a simple test project with just `FMDB/SQLCipher` using Xcode 12.2 (12B5018i). Are you including other pods/libs/frameworks which depend on standard sqlite?

**Comment by noberasco** [comment]
We managed to resolve this internally by moving our sqlite3 includes to the bridging header.
Evidently XCode 12 changed something in the order in which it parses / compiles things.

Thank you for your time and support :-)
