### ISSUE TITLE
pod install fail

### ISSUE THREAD

**Issue by AlexanderPan** [ccgus/fmdb#801]
```
[!] CocoaPods could not find compatible versions for pod "FMDB":
  In Podfile:
    FMDB (~> 2.7.7)

None of your spec sources contain a spec satisfying the dependency: `FMDB (~> 2.7.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by R4N** [comment]
I believe 2.7.7 may not have been published to cocoa pods. 2.7.5 looks like it was the latest version which was published.

**Comment by justinvallely** [comment]
Workaround until 2.7.7 is pushed to the cocoapods spec repo:
```
pod 'FMDB', :git => 'https://github.com/ccgus/fmdb.git', :commit => '61e51fd'
```

**Comment by cbess** [comment]
When will the latest version be published to CocoaPods? If the pod approach is abandoned for SPM, I totally understand.

**Comment by ccgus** [comment]
I don't have an answer for that, sorry. The best way to get it is to just download the latest release from here.
