### ISSUE TITLE
Second Order SQL Injection

### ISSUE THREAD

**Issue by DineshThakur** [ccgus/fmdb#804]
Hi Team,

We have used FMDB in our project. In security scan we got “Second Order SQL Injection” as critical issue for following line in **FMResultSet** :-
**const char *c = (const char *)sqlite3_column_text([_statement statement], columnIdx);
 - **RelevantPart: sqlite3_column_text**

```
- (NSString*)stringForColumnIndex:(int)columnIdx {
    
    if (sqlite3_column_type([_statement statement], columnIdx) == SQLITE_NULL || (columnIdx < 0)) {
        return nil;
    }
    **const char *c = (const char *)sqlite3_column_text([_statement statement], columnIdx);**
    if (!c) {
        // null row.
        return nil;
    }
    return [NSString stringWithUTF8String:c];
}
```

Pls let me know if there is any solution for this?

**Comment by ccgus** [comment]
I guess I don't see what the problem it's flagging is?

**Comment by robertmryan** [comment]
That’s undoubtedly a false positive. You only get SQL injection attacks (or second order SQL injection attacks) if you take values and build subsequent SQL statements from those strings. But FMDB doesn’t do that. And we encourage the use of `?` placeholders everywhere that you supply a value to a SQL statement, and that eliminates all injection attacks. (Obviously, if you start manually inserting values as you build your own strings that will be used as SQL statements, then that’s on you.)

That having been said, given that this is likely a false positive, I’d reach out to the vendor and figure out how their concluding there is a second order SQL injection (and, ideally, their prescription for fixing it). Only when we know how they’re determining that there is a second order SQL injection risk can we either (a) consider changes to mitigate the risk; or (b) go back to the vendor and inform them of the false positive. 

The `sqlite3_column_text` is the correct way to retrieve values from a SQLite database, so I’m fascinated by how they concluded there was a risk and what their prescription is.

**Comment by DineshThakur** [comment]
@robertmryan I am checking this with Security team, I will update you once I got the update from them.

**Comment by DineshThakur** [comment]
@robertmryan  The issue was not with FMResultSet, but it was the way we was creating the DB query. We have made the required changes and now it's fixed.

Thank you so much for your support.
