### ISSUE TITLE
Can I install FMDB + sqlcipher via Swift Package Manager?

### ISSUE THREAD

**Issue by mezhevikin** [ccgus/fmdb#813]
Hi, guys!

Are there any workarounds to install FMDB + SQLCipher via Swift Package Manager?

I wanted to get rid of cocapods but stuck with this limitation.

I would be grateful for any information.

**Comment by mezhevikin** [comment]
I found package SQLCipher https://github.com/antwork/SQLCipher
But I don't have idea how to implement it to FMDB.

**Comment by BinarySatan** [comment]
I have the same problem

**Comment by brindy** [comment]
@mezhevikin - you closed this out pretty quickly :)  did you find a solution?

**Comment by mezhevikin** [comment]
I didn't find the solution. I closed the issue because I think this is SPM problem. SPM does not support submodules like Cocaopods.

I added the source of FMDB to my project manually. Sqlchiper I use like spm dependency. It’s works fine. But this is hack.
