### ISSUE TITLE
Replace asserts with foundation asserts (potential issue affecting millions)

### ISSUE THREAD

**Issue by xoridius** [ccgus/fmdb#816]
Current version of FMDB uses `assert` during initialization:
[`assert(sqlite3_threadsafe())`](https://github.com/ccgus/fmdb/blob/3e5efdf6690cf7dce0a914c370507deee8740d33/src/fmdb/FMDatabase.m#L73)

As opposed to foundation asserts those are not stripped in release builds. Many ad networks including UnityAds, Vungle, StartApp and Pangle use FMDB as is in their SDKs. If for some reason result of sqlite3_threadsafe will change in the future, this will blow up thousands of applications affecting millions of users.

I kindly ask to replace this and all other occurrences of `assert` with foundation asserts (NSAssert).

**Comment by ccgus** [comment]
I'm well aware that these will cause crashes. That is precisely the point, and it doing so is because of a programming or environment error and a crash is way better than silently corrupting data.

**Comment by xoridius** [comment]
@ccgus Thank you for reply.

But the crash can be caused by auxiliary SDK, leaving the app and its primary features completely broken. Since some SDKs initialize itself (and FMDB) on +load or by swizzling launch routines there will be constant crash on app launch.

What if there is no way to publish immediate update on the App Store? Isn't it better to fail and give a chance for developer to display an error to user? Or at least let the app run without touching the data?

**Comment by ccgus** [comment]
It's not been a problem in over a decade, and I think the position I'm taking on this is completely reasonable. Unless there's some evidence of this actually being a problem?

**Comment by xingheng** [comment]
Suggest using `@throw [NSException new]` instead of `assert` if you really want to app developers aware that error in both debug and release product, this makes app developers catchable in high level code with `@try {} @catch {}`, right?

`@throw [NSEeception new]` is kindly useful for library (developers).

**Comment by xoridius** [comment]
@ccgus I have no evidence that it caused or will cause an issue. But so we though about Facebook SDK, which crashed badly two times last year, so that TikTok, Spotify and many others just were not able to launch.
What if `sqlite3_threadsafe` assertion is removed from initializer and instead checked in `open` method to return false unless `sqlite3_threadsafe`? Would it be enough to avoid data corruption?

@xingheng No, quite the opposite. I suggested using `NSParameterAssert` (foundation assertion) instead of `assert`, so that would be stripped in release builds without any modifications required from end user of FMDB.
