### ISSUE TITLE
Xcode 13 beta: Classes with identical names as some classes in fmdb

### ISSUE THREAD

**Issue by byohay** [ccgus/fmdb#823]
While running tests in Xcode 13 beta (13A5154h) I noticed these messages were printed to the console:

> objc[26586]: Class FMResultSet is implemented in both /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiomeFlexibleStorage.framework/BiomeFlexibleStorage (0x7fff89481288) and ****. One of the two will be used. Which one is undefined.
objc[26586]: Class FMDatabase is implemented in both /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiomeFlexibleStorage.framework/BiomeFlexibleStorage (0x7fff894811e8) and ****. One of the two will be used. Which one is undefined.
objc[26586]: Class FMStatement is implemented in both /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiomeFlexibleStorage.framework/BiomeFlexibleStorage (0x7fff89481210) and ****. One of the two will be used. Which one is undefined.
objc[26586]: Class FMDatabasePool is implemented in both /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiomeFlexibleStorage.framework/BiomeFlexibleStorage (0x7fff894812d8) and ****. One of the two will be used. Which one is undefined.
objc[26586]: Class FMDatabaseQueue is implemented in both /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiomeFlexibleStorage.framework/BiomeFlexibleStorage (0x7fff89481328) and ****. One of the two will be used. Which one is undefined.

`****` was put instead the actual path as to not expose private names.

I tested it only on simulators, and it seems to happen only on iOS 15 (On iOS 14.4 it doesn't happen).

**Comment by ccgus** [comment]
This seems super bad. I'm not running the beta yet- but you really really really should file a bug with Apple.

If they ship FMDB as part of a linkable framework (super cool!) but don't change the class names (super f'n bad!) then that's going to cause a whole bunch of issues for a metric ton of developers.

**Comment by byohay** [comment]
thanks, I filed a bug 😄

**Comment by rmpurp** [comment]
Looks like this is fixed with the new betas: they prefixed the class names with `_bm` 👍

**Comment by ccgus** [comment]
Sweet.
