### ISSUE TITLE
[FMDatabase executeQuery:withArgumentsInArray:orDictionary:orVAList:] Crash

### ISSUE THREAD

**Issue by mahong125** [ccgus/fmdb#826]
Hello, we encountered a problem during use. In low-memory devices, there will be frequent crashes. I would like to ask, is there any good liberation plan? Thanks.
Below is the error stack information
![CD15CB7EC5465682D2D4C42300702463](https://user-images.githubusercontent.com/8706963/137458802-7d5e3118-eaaa-46f9-9e75-c09880ce7a1d.jpg)

**Comment by ccgus** [comment]
This question is a bit out of the scope of FMDB, sorry.
