### ISSUE TITLE
Application getting crashed on FMDB: -[FMResultSet nextWithError:] + 48

### ISSUE THREAD

**Issue by pradipaub36** [ccgus/fmdb#831]
Our users are facing the app crash issue on the production app while they try to open the app. 
I use the latest version of FMDB / FTS in my project to handle the local database operations.

What we do while opening the app is:
1) Read data from the local database using FMDB on the app starts
2) Writes data to HealthApp

Application is getting crashed while reading data from the local database as per Apple crash reports!  
![FMDB](https://user-images.githubusercontent.com/54441132/172563788-76170032-49c7-449d-a4a4-2e1f1f4a37b7.png)
![Screenshot 2022-06-08 at 1 42 44 PM](https://user-images.githubusercontent.com/54441132/172567080-895bfaaa-2259-403c-ba26-69e859602738.png)
![Screenshot 2022-06-08 at 1 43 06 PM](https://user-images.githubusercontent.com/54441132/172567104-c0c8c819-b4b4-4346-80ce-31798e61fc96.png)

We have integrated the Firebase Crashlytics but we didn't receive this crash there hence I don't have the Stack trace report for the same.

We did several tries to reproduce the issue on our end but we couldn't get success.

Any help would be appreciated!

**Comment by lzcuriosity** [comment]
您的邮件已经收到，我会尽快查阅，谢谢！Best Wishes!

**Comment by ccgus** [comment]
All threads should be using the same database queue. It looks like your main thread is using a result set that was possibly made on another thread? That's a bad idea, and will lead to crashes.
