### ISSUE TITLE
online crash 

### ISSUE THREAD

**Issue by songhongkang** [ccgus/fmdb#833]
![image](https://user-images.githubusercontent.com/13045795/179699864-8dd957b5-f741-4575-85be-c8f40ce89cb5.png)

**Comment by lzcuriosity** [comment]
您的邮件已经收到，我会尽快查阅，谢谢！Best Wishes!

**Comment by ccgus** [comment]
There's not enough info to go on here. But, I'm guessing you're doing something with FMDB or SQLite in another thread at the same time. Try using FMDatabaseQueue to manage your updates and queries.
