### ISSUE TITLE
Swift: result of executeUpdate() - did it update or not? Count of updated records?

### ISSUE THREAD

**Issue by rzolin** [ccgus/fmdb#835]
This is probably related to #688. But my question is somewhat more general.
I am trying to update a record with some condition (time based). And I need to know whether it succeed or failed. And it would be nice to know the number of updated records.
And at the moment I cannot figure out how to do so. executeQuery doesn't return any result (and probably shouldn't).

**Comment by ccgus** [comment]
There's the -(int)changes; method on FMDatabase that calls sqlite3_changes ( https://www.sqlite.org/c3ref/changes.html ), which will get you the number of updated records.

Will that get you what you're after?

**Comment by rzolin** [comment]
It looks like I can use "PRAGMA count_changes=ON" to get counts for update. I tried to use executeQuery("PRAGMA count_changes=ON", values: nil). Setting it ON before update and OFF after. But then the executeUpdate gives me a generic error. So this doesn't work apparently

**Comment by rzolin** [comment]
@ccgus Thanks! That's what I was looking for. Two consecutive updates produce different `changes`, first is 1, second is 0
