### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by lalogada** [ccgus/fmdb#840]
I notice that fmdb was last released on May 13, 2020. I know that fmdb is a mature and stable software, but I still want to ask why fmdb has not released a new version recently and whether there is any future release plan.

**Comment by ccgus** [comment]
There's not really been a reason to release a new version yet. If there's something that we've add you'd like - it's right there on the main branch and you can grab it that way…

**Comment by lalogada** [comment]
> There's not really been a reason to release a new version yet. If there's something that we've add you'd like - it's right there on the main branch and you can grab it that way…

tanks
