### ISSUE TITLE
Error with Xcode 14.3 because of deployment_target (9.0)

### ISSUE THREAD

**Issue by gerken-tss** [ccgus/fmdb#844]
I am using `fmdb` as a transitive dependency of a Flutter package ([sqflite](https://pub.dev/packages/sqflite)).

Whenever I try to compile the application, Xcode complains about FMDB pod with this error:

>Error (Xcode): File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a
>
>Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
>
>Could not build the application for the simulator.
>Error launching application on iPhone 14 Pro Max.

According to [SO](https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3) this issue is connected to `deployment_target` being too low (requires 11.0 at least).

I'm hesitating to accept the solution being mentioned in the SO post as it uncontrollably overrides all the `deployment_target` properties of every pod (this doesn't seem right).

A better solution would be for the author every pod with outdated `deployment_target` to willingly increase it.

**Comment by kyle-seongwoo-jun** [comment]
same problem here

**Comment by Yck-Dakucha** [comment]
same
