### ISSUE TITLE
Can the current version be used stably?

### ISSUE THREAD

**Issue by beibeiGeng** [ccgus/fmdb#847]
My project requires the software, but the current version has not been updated for a long time. Can the 2.7.7 version be used for commercial use?
Is there any release plan for this software? No new version has been released in three years.

**Comment by ccgus** [comment]
Yes, you can sue the current version. Or you can just use what's on the main branch! It's all good.

**Comment by beibeiGeng** [comment]
Is there any release plan for this software?

**Comment by ccgus** [comment]
Not at this time. If it gets some major new features or fixes, then sure. But we're not there right now.
