### ISSUE TITLE
Support for visionOS

### ISSUE THREAD

**Issue by serajahmad01** [ccgus/fmdb#850]
Hi Team,

Is there any timeline or ETA for the support of VisionOS (Apple's new device) on FMDB?

Thanks,
Seraj

**Comment by ccgus** [comment]
Does it not work? I haven't tried, but I bet they just compile fine.

**Comment by serajahmad01** [comment]
Hi All,

Adding "visionOS" in the Supported Platform and rebuilding worked for me.

<img width="848" alt="image" src="https://github.com/ccgus/fmdb/assets/22234359/476a64be-7b6a-4bce-be26-cb4c24df7b4b">

**Comment by medabida** [comment]
@serajahmad01 Thank you.
I am not a big fan of forking the repo and doing those changes manually because i would loos the auto-update in case a new version of FMDB gets released.. 
@ccgus any plans on applying this fix on the FMDB repo ? ill be happy to create an MR myself to fix this..

**Comment by ccgus** [comment]
Fixes + pull requests are appreciated.

**Comment by medabida** [comment]
Pull request -> https://github.com/ccgus/fmdb/pull/851
