### ISSUE TITLE
Apple Privacy Manifest

### ISSUE THREAD

**Issue by manahilov** [ccgus/fmdb#852]
Hi team,
Is there a plan to include the PrivacyInfo.xcprivacy manifest as required by Apple?
ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Boyan

**Comment by shonorio** [comment]
@manahilov is Apple asking for this to be included in your project due to its use of this particular library?

**Comment by manahilov** [comment]
Hi @shonorio, Apple suggests every framework, swift package or library to contain their own Privacy Manifest.
[Apple documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
`Third-party SDKs need to provide their own privacy manifest files that record the types of data they collect. Your app’s privacy manifest file doesn’t need to cover data collected by third-party SDKs that your app links to.`

From the other hand the application that uses the frameworks should create its own Privacy manifest for the data that the app collects excluding the frameworks.

**Comment by ccgus** [comment]
I've added one for the heck of it.

**Comment by trickart** [comment]
Thank you for supporting the Privacy Manifest!

By the way, do you have any plans to release a version that supports Privacy Manifest?

I am installing FMDB from CocoaPods.
It seems that CocoaPods has not yet released a version that supports Privacy Manifest.

**Comment by manahilov** [comment]
Yo are awesome @ccgus, thank you!

**Comment by ccgus** [comment]
@trickart I just "released" a new version based off the main branch.

**Comment by trickart** [comment]
@ccgus 
Thanks for release 2.7.8!
I would like to ask the CocoaPods package maintainers if they plan to release a new version.

**Comment by ccgus** [comment]
@trickart Good luck with that. The CocoaPods things are not my thing and I don't have any way to test it. I'm happy to take patches though.

**Comment by alextekartik** [comment]
I'll be a happy tester of the cocoa pods. I'm the author of sqflite for flutter and its iOS/MacOS implementation is based on FMDB through cocoapods and it seems that most flutter plugins uses this too (as basically you don't even need to open Xcode to setup dependencies). Although iOS/MacOS in general are not my thing (ha ha) if there is any way I can help, let me know. I don't know how cocoapod publishing work and who is the maintainer of FMDB there.

Thanks for maintaining FMDB @ccgus !

**Comment by lokii49** [comment]
App got rejected with below reason:
ITMS-91065: Missing signature - Your app includes “Frameworks/FMDB.framework/FMDB”, which includes FMDB, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK

The privacy file is bundled inside SQLCipher.bundle.
