### ISSUE TITLE
无法通过git clone下载到本地

### ISSUE THREAD

**Issue by qq26835124** [ccgus/fmdb#855]
Cloning into 'fmdb'...
fatal: unable to access 'https://github.com/ccgus/fmdb.git/': Failed to connect to github.com port 443 after 75025 ms: Couldn't connect to server

**Comment by ccgus** [comment]
This is a problem with your connection to GitHub, not FMDB. I'm not sure who you need to contact about this.

**Comment by qq26835124** [comment]
Yes, it was a GitHub connection issue. It has been fixed, thanks




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ccgus ***@***.***&gt;
发送时间: 2024年1月18日 01:01
收件人: ccgus/fmdb ***@***.***&gt;
抄送: qq26835124 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ccgus/fmdb] 无法通过git clone下载到本地 (Issue #855)





 
This is a problem with your connection to GitHub, not FMDB. I'm not sure who you need to contact about this.
