### ISSUE TITLE
FMDB 2.7.8 is not available on cocoapods 

### ISSUE THREAD

**Issue by bytebai920** [ccgus/fmdb#857]
FMDB 2.7.8 is not available on cocoapods 
![image](https://github.com/ccgus/fmdb/assets/14013454/2062082f-9bd2-4843-91d3-1354459ccce7)

**Comment by wintelsui** [comment]
i copy a FMDB.podspec.json to my Specs, change the "FMDB.podspec.json"'s tag from "2.7.8" to "v2.7.8", than i can pod install '2.7.8' version to my progects, 无语子

**Comment by incanus** [comment]
This was fixed in https://github.com/ccgus/fmdb/issues/860.
