### ISSUE TITLE
The subspec 'SQLCipher' required privacy file location declaration

### ISSUE THREAD

**Issue by alwayswith** [ccgus/fmdb#866]
s.subspec 'SQLCipher' do |ss|
   ss.dependency 'SQLCipher'
   ss.source_files = 'src/fmdb/FM*.{h,m}'
   ss.exclude_files = 'src/fmdb.m'
   ss.header_dir = 'fmdb'
   ss.resource_bundles = {'SQLCipher' => ['privacy/PrivacyInfo.xcprivacy']} // missing this line
   ss.xcconfig = { 'OTHER_CFLAGS' => '$(inherited) -DSQLITE_HAS_CODEC -DHAVE_USLEEP=1 -DSQLCIPHER_CRYPTO', 'HEADER_SEARCH_PATHS' => 'SQLCipher' }
  end

Without privacy file declaration in subspec, The privacy file will not be include in pod project if i just use `pod 
'FMDB/SQLCipher'`

**Comment by incanus** [comment]
This makes sense to me @alwayswith. Will be fixed in next release.
