### ISSUE TITLE
Can you publish new release 2.7.11

### ISSUE THREAD

**Issue by lolgear** [ccgus/fmdb#867]
It is very unexpected that release 2.7.10 was published and later someone force-pushed release tag 2.7.10 to newer commit.

Can you fix it and publish new release 2.7.11?

Thanks

**Comment by lolgear** [comment]
@incanus 
Any updates?

**Comment by GLinnik21** [comment]
@incanus 
Gentle reminder.

**Comment by ccgus** [comment]
I'll try and get this going sometime soon. Travel and work have gotten in the way.

**Comment by lolgear** [comment]
Can you publish 2.7.11?

**Comment by incanus** [comment]
```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  FMDB (2.7.11) successfully published
 📅  May 23rd, 13:11
 🌎  https://cocoapods.org/pods/FMDB
 👍  Tell your friends!
--------------------------------------------------------------------------------
```
