### ISSUE TITLE
Capacitor Version of a player

### ISSUE THREAD

**Issue by SimonAlpha40** [ccgus/fmdb#876]
Hello i am using capacitor to build an ios app and a player plugin which is able to download video : 
each time i am launching an error i have an error indicates that 
-[FMDatabase intForQuery:]: unrecognized selector sent to instance 0x302961800
(
	0   CoreFoundation                      0x000000019ea70f2c 76A3B198-3C09-323E-8359-0D4978E156F5 + 540460
	1   libobjc.A.dylib                     0x000000019691f2b8 objc_exception_throw + 60
	2   CoreFoundation                      0x000000019eb7a480 76A3B198-3C09-323E-8359-0D4978E156F5 + 1627264
	3   CoreFoundation                      0x000000019ea0dfb4 76A3B198-3C09-323E-8359-0D4978E156F5 + 135092
	4   CoreFoundation                      0x000000019ea0d8d0 _CF_forwarding_prep_0 + 96
	5   CordovaPlugins                      0x00000001034b2a4c -[FmdbMigrationManager currentVersion] + 92
	6   CordovaPlugins                      0x00000001034b276c -[FmdbMigrationManager initializeSchemaMigrationsTable] + 108
	7   CordovaPlugins                      0x00000001034b2be4 -[FmdbMigrationManager initWithDatabasePath:] + 144
	8   CordovaPlugins                      0x00000001034b2638 +[FmdbMigrationManager executeForDatabasePath:withMigrations:] + 64
	9   CordovaPlugins                      0x00000001034ba330 -[VGPStorageDatabase migrateToLatest] + 208
	10  CordovaPlugins                      0x00000001034ba3a0 -[VGPStorageDatabase open] + 68
	11  CordovaPlugins                      0x00000001034ba410 -[VGPStorageDatabase getDownloadsIndex] + 20
	12  CordovaPlugins                      0x00000001034b417c -[VGPDownloadService downloadsIndex] + 48
	13  CordovaPlugins                      0x00000001034b4dcc -[VGPDownloadService addDownload:mediaItem:trackOverrides:metadataOs:drmLicenseRequestInfoDelegate:contentKeyIds:] + 212
	14  CordovaPlugins                      0x00000001034b8da8 -[VGPOfflineDownloadsTracker addDownload:mediaItem:metadataOs:trackOverrides:drmLicenseRequestInfoDelegate:contentKeyIds:] + 168
	15  CordovaPlugins                      0x0000000103410a00 -[VGPOfflineDownloadsTrackerInterfaceProxy add_download:] + 2380
	16  Capacitor                           0x00000001030289c8 $s9Capacitor0A6BridgeC19handleCordovaJSCall4callyAA0E0V_tF + 2436
	17  Capacitor                           0x00000001030a05a8 $s9Capacitor24WebViewDelegationHandlerC21userContentController_10didReceiveySo06WKUsergH0C_So15WKScriptMessageCtF + 5272
	18  Capacitor                           0x00000001030a0714 $s9Capacitor24WebViewDelegationHandlerC21userContentController_10didReceiveySo06WKUsergH0C_So15WKScriptMessageCtFTo + 68
	19  WebKit                              0x00000001b3d028ac C91B052C-4258-3771-B54F-68BAE97E992C + 911532
	20  WebKit                              0x00000001b3c42e9c C91B052C-4258-3771-B54F-68BAE97E992C + 126620
	21  WebKit                              0x00000001b3c42788 C91B052C-4258-3771-B54F-68BAE97E992C + 124808
	22  WebKit                              0x00000001b3d438ac C91B052C-4258-3771-B54F-68BAE97E992C + 1177772
	23  WebKit                              0x00000001b3c4e770 C91B052C-4258-3771-B54F-68BAE97E992C + 173936
	24  WebKit                              0x00000001b3c48e30 C91B052C-4258-3771-B54F-68BAE97E992C + 151088
	25  WebKit                              0x00000001b3c5e774 C91B052C-4258-3771-B54F-68BAE97E992C + 239476
	26  JavaScriptCore                      0x00000001b4bffa70 2800076A-7D5A-38DC-AFA7-23FA080301B6 + 371312
	27  JavaScriptCore                      0x00000001b4c00998 2800076A-7D5A-38DC-AFA7-23FA080301B6 + 375192
	28  CoreFoundation                      0x000000019ea43834 76A3B198-3C09-323E-8359-0D4978E156F5 + 354356
	29  CoreFoundation                      0x000000019ea437c8 76A3B198-3C09-323E-8359-0D4978E156F5 + 354248
	30  CoreFoundation                      0x000000019ea41298 76A3B198-3C09-323E-8359-0D4978E156F5 + 344728
	31  CoreFoundation                      0x000000019ea40484 76A3B198-3C09-323E-8359-0D4978E156F5 + 341124
	32  CoreFoundation                      0x000000019ea3fcd8 CFRunLoopRunSpecific + 608
	33  GraphicsServices                    0x00000001e348d1a8 GSEventRunModal + 164
	34  UIKitCore                           0x00000001a1079ae8 9DA0D273-5506-3712-B73D-E0149D74C13C + 4238056
	35  UIKitCore                           0x00000001a112dd98 UIApplicationMain + 340
	36  App                                 0x0000000102158e30 main + 64
	37  dyld                                0x00000001c2217154 52039C94-4DA1-3638-BD52-020A0B5FA399 + 250196
)
Really don't know what can i do : it works with cordova framework
do i need to downgrade FMDB version ? in my podfile ? 
The best

**Comment by ccgus** [comment]
Make sure you're compiling FMDatabaseAdditions.m with your app. That's where the implementation for this method is.
