### ISSUE TITLE
IOS Capacitor : unrecognized selector sent to instance 0x3023f9c20

### ISSUE THREAD

**Issue by SimonAlpha40** [ccgus/fmdb#877]
Hello ,
**IOS only** ( works on Android )
I am using a Capacitor App with a cordova plugin ( i don't have the source of the plugin ) : the plugin is using FMDB  : i am facing some  issue when i launch my app with Capacitor Framework : it's a video player :
i have this issue when i am using capacitor : if i use Cordova Framework it works perfectly .
etting source on player: <VGPStream: 0x3029fcd80>
Exception in setSource: -[FMDatabase intForQuery:]: unrecognized selector sent to instance 0x3023f9c20 | Stack Trace: (
	0   CoreFoundation                      0x000000018ee9cf2c 76A3B198-3C09-323E-8359-0D4978E156F5 + 540460
	1   libobjc.A.dylib                     0x0000000186d4b2b8 objc_exception_throw + 60
	2   CoreFoundation                      0x000000018efa6480 76A3B198-3C09-323E-8359-0D4978E156F5 + 1627264
	3   CoreFoundation                      0x000000018ee39fb4 76A3B198-3C09-323E-8359-0D4978E156F5 + 135092
	4   CoreFoundation                      0x000000018ee398d0 _CF_forwarding_prep_0 + 96
	5   CordovaPlugins                      0x000000010595fe78 -[FmdbMigrationManager currentVersion] + 92
	6   CordovaPlugins                      0x000000010595fb98 -[FmdbMigrationManager initializeSchemaMigrationsTable] + 108
	7   CordovaPlugins                      0x0000000105960010 -[FmdbMigrationManager initWithDatabasePath:] + 144
	8   CordovaPlugins                      0x000000010595fa64 +[FmdbMigrationManager executeForDatabasePath:withMigrations:] + 64
	9   CordovaPlugins                      0x00000001059677e8 -[VGPStorageDatabase migrateToLatest] + 208
	10  CordovaPlugins                      0x0000000105967858 -[VGPStorageDatabase open] + 68
	11  CordovaPlugins                      0x00000001059678c8 -[VGPStorageDatabase getDownloadsIndex] + 20
	12  CordovaPlugins                      0x00000001059615a8 -[VGPDownloadService downloadsIndex] + 48
	13  CordovaPlugins                      0x00000001059636b4 -[VGPDownloadService getDownloadSync:] + 104
	14  CordovaPlugins                      0x0000000105963874 -[VGPDownloadService localURLForDownloadId:] + 52
	15  CordovaPlugins                      0x000000010597d3c8 -[VGPPlayer setSource:options:] + 240
	16  CordovaPlugins                      0x00000001058c5dcc __29-[VGPPlayerProxy set_source:]_block_invoke + 136
	17  libdispatch.dylib                   0x0000000105248b98 _dispatch_call_block_and_release + 32
	18  libdispatch.dylib                   0x000000010524a7bc _dispatch_client_callout + 20
	
	
	I am totally lost ;) 
	Any idea will be so precious for me ;)
My capacitor config :

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

**Comment by ccgus** [comment]
Make sure you're compiling `FMDatabaseAdditions.m` into your project. That's where `intForQuery` is defined.
